### DISCUSSION TITLE
Two different maps?

### DISCUSSION THREAD

**Discussion by bendavis** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#108] [Q&A] [answered]
Is it possible to get two maps to display from two different vacuums? I have an upstairs & downstairs vacuum.

**Comment by PiotrMachowski** [comment, marked as answer]
@bendavis sure, you just have to provide `name` in your config

**Comment by digitalit** [comment]
Hi guys,

I just bought another Roborock and i wonder how i shall do this in config file?

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret vacuum_host_s5
    token: !secret vacuum_token_s5
    username: !secret vacuum_username_s5
    password: !secret vacuum_password_s5
    name: "Roborock S5 Max"
    draw: ["all"]
    attributes:
      - calibration_points
      - room_numbers
  - platform: xiaomi_cloud_map_extractor
    host: !secret vacuum_host_s7
    token: !secret vacuum_token_s7
    username: !secret vacuum_username_s7
    password: !secret vacuum_password_s7
    name: "Roborock S7 Max"
    draw: ["all"]
    attributes:
      - calibration_points
      - room_numbers
```

Please point me in the right direction :)
