### DISCUSSION TITLE
Path Shown Instead of Image

### DISCUSSION THREAD

**Discussion by royaltongue** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#116] [Q&A] [answered]
First off, sorry if this has been brought up before- I looked but didn't see any issues pertaining to this.

Configuration.yaml:
```
# Xiaomi Map Extractor
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.37
    token: [redacted]
    username: [redacted]
    password: [redacted]
    draw: ['all']
    attributes:
      - calibration_points
```

After adding the entity to my Lovelace UI with attribute `Entity Picture`, it shows this:
![image](https://user-images.githubusercontent.com/61848270/118705008-b4952880-b7e5-11eb-97e0-4597b2983f4d.png)

If I click on the path, it shows the image:
![image](https://user-images.githubusercontent.com/61848270/118705135-dabac880-b7e5-11eb-969f-6721ea1c1346.png)

 I'd like the image to be displayed outright. Is this possible?
