### DISCUSSION TITLE
small map

### DISCUSSION THREAD

**Discussion by brunokelo** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#161] [Q&A] [answered]
hello, my map is too small, does anyone know what parameter i should use to increase the map scale? make it bigger on the screen?

thanks.

[](https://prntscr.com/1iu5auk)
![Screenshot at Aug 03 20-54-52](https://user-images.githubusercontent.com/41593081/128100916-82142838-ca1c-48ec-8697-4832521f1c28.png)

**Comment by PiotrMachowski** [comment, marked as answer]
You have to configure [map trimming](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#map-transformation-configuration), your values should be similar to the following:
```
    map_transformation:
      scale: 2
      trim:
        top: 50
        bottom: 20
        left: 20
        right: 40
```
