### DISCUSSION TITLE
No zones showing up

### DISCUSSION THREAD

**Discussion by filikun** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#164] [Q&A]
So I'm playing around with this and got it all working with the map and I can see the different zones colored and seems to match what the Mi home app is showing but I don't get any option to choose a zone to clean? Was that only if you pre-defined zones?

Also I added `zones` to attributes but that renders null but rooms do work. What command can I use to send my vacuum cleaner to that specific room for cleaning? `room_numbers` is rendering null but `rooms` have 5 entries and that match the actual rooms we got. 

Thanks m8 for an awesome custom component, I have been lurking wanting to try this for a while but it seemed fiddly with custom firmware and stuff but with this custom component it's really easy to get going!

Here's my config. I'm using a S5 vacuum cleaner
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
      - rooms
      - room_numbers
      - vacuum_room_name
      - vacuum_room
      - zones
    map_transformation:  
      rotate: 90
      trim:
        left: 23.3
        right: 23.3
        top: 22
        bottom: 17
```

![image](https://user-images.githubusercontent.com/9947929/129572560-564d74a9-e73b-4298-bc89-12f0718c5489.png)
![image](https://user-images.githubusercontent.com/9947929/129572702-d2d287af-32cd-4c5b-9006-c0fa3fe4f5ec.png)
