### DISCUSSION TITLE
Low map resolution

### DISCUSSION THREAD

**Discussion by sesardelaisla** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#166] [Q&A] [answered]
Hello there!

First of all, thank you so much Piotr for this great component!

Everything works pretty good. However, after adjusting trimming, map looks not as sharp as when trimming is set to zero:

**ZERO TRIMMING**
![Captura de pantalla 2021-08-24 a las 20 44 09](https://user-images.githubusercontent.com/81921573/130672372-6ae53935-11f8-4ef0-8a64-c28fb810f75d.jpg)
```
map_transformation:
      scale: 1
      trim:
        top: 0
        bottom: 0
        left: 0
        right: 0
```

**ADJUSTED TRIMMING**
![Captura de pantalla 2021-08-24 a las 20 41 58](https://user-images.githubusercontent.com/81921573/130672420-05a9a9b0-f5d6-4184-af6a-88a4134cbb98.jpg)
```
map_transformation:
      scale: 1
      trim:
        top: 20
        bottom: 10
        left: 20
        right: 25
```

Is there any way to optimize resolution? I can live with this, but it would be great to display the map even better! :)

Cheers!
Sésar
