### DISCUSSION TITLE
Using with 2 or more vacuums

### DISCUSSION THREAD

**Discussion by sunebuhl** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#198] [Q&A] [answered]
Hi.

I have 2 vacuums in my house but I'm unsure how to use the map extractor with both. Would it be to add both in configuration.yaml like this? 

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: secret....
    token: secret....
    username: secret....
    password: secret....
    name: "S5 Max Camera"
    draw: ['all']
    attributes:
      - calibration_points    
      
  - platform: xiaomi_cloud_map_extractor
    host: secret....
    token: secret....
    username: secret....
    password: secret....
    name: "S5  Camera"
    draw: ['all']
    attributes:
        calibration_points    
```
