### DISCUSSION TITLE
Cloud map extractor: "Failed to retrieve device"

### DISCUSSION THREAD

**Discussion by Eckart0** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#240] [Q&A] [answered]
Hi ,
I have installed the mi home integration, Xiaomi Cloud map Extractor and lovelace card - step by step as described. I have two Xiaomi Vacuum Cleaner V1. 
I can command them from the lovelace card, but I fail to get the map. The card displays in a blue area: "Failed to retrieve device".
Where can I look for the failure?
Thank you for any hint!
Regards, Eckart

PS: My configuration:
configuration.yaml:
```
camera:
    # Vacuum Cleaner Map EG
  - platform: xiaomi_cloud_map_extractor
    name: "vacuum_eg_map"
    host: !secret xiaomi_vacuum_host_eg
    token: !secret xiaomi_vacuum_token_eg
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    attributes:
      - calibration_points
    # Vacuum Cleaner Map OG
  - platform: xiaomi_cloud_map_extractor
    name: "vacuum_og_map"
    host: !secret xiaomi_vacuum_host_og
    token: !secret xiaomi_vacuum_token_og
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    attributes:
      - calibration_points
```
Lovelace Card (here just one, the second one with "entity: vacuum.k68_robot_vacuum_og":
```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.k68_robot_vacuum_eg
title: Staubsauger EG
vacuum_platform: default
map_source:
  camera: camera.vacuum_eg_map
calibration_source:
  camera: true
```
