### DISCUSSION TITLE
HA sensor with coordinates.

### DISCUSSION THREAD

**Discussion by sheminasalam** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#269] [Q&A] [answered]
Is it possible to expose the current location of the vacuum as a sensor in home assistant so that it could be used to build automations like switching the lights or ceiling fans on/off in particular areas?

**Comment by PiotrMachowski** [comment, marked as answer]
It's available in attributes as `vacuum_position`, you can extract it using a template sensor as well.
[Documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#attributes-configuration)

**Reply by sheminasalam** [reply]
I have checked the attributes but its not there even after draw all is there in config. The following is the atttributes.

```
access_token: b
calibration_points:
  - vacuum:
      x: 0
      'y': 0
    map:
      x: 700
      'y': 698
  - vacuum:
      x: 1
      'y': 0
    map:
      x: 735
      'y': 698
  - vacuum:
      x: 0
      'y': 1
    map:
      x: 700
      'y': 663
model: viomi.vacuum.v10
used_api: viomi
entity_picture: >-
  /api/camera_proxy/camera.robovacmap?token=b
friendly_name: Robovac
supported_features: 1
```

**Reply by PiotrMachowski** [reply]
You have to enable it.
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
      - vacuum_position
```
