### DISCUSSION TITLE
How do you extract a map

### DISCUSSION THREAD

**Discussion by raigeiki55** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#301] [Q&A] [answered]
Hello I would like to extract the map and already made a tmp folder for it here is my code:
```yaml
    - platform: xiaomi_cloud_map_extractor
      host:  xxx.xxx.xxx.xxx
      token: xxxxxxxxxxx
      username: xxxx@xxxxx.com
      password: xxxxxxxx
      draw: ['all']
      attributes:
        - calibration_points  
        - rooms
      scan_interval:
        seconds: 10          
      auto_update: true
      store_map_raw: true
      store_map_image: true
      store_map_path: "/tmp"
```
when i open the tmp folder it is empty, do i need to do this manually? I'm just planning to do a multi floor setup with my vacuum. Thank you
