### DISCUSSION TITLE
Is it possible to persist the zoomed in view of a locked map?

### DISCUSSION THREAD

**Discussion by ThatTallGuy21** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#307] [Q&A] [answered]
I have a vacuum map card on one of my dashboards, and I love that I can zoom in and lock the map so it's a more zoomed in version. However, when I navigate away from the page and return, the map is unlocked and zoomed out again. Is there anyway to persist the locked setting so I can leave the page and return and still see the same zoomed in version of the map?

**Comment by PiotrMachowski** [comment, marked as answer]
In Map Extractor: [map trimming](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#map-transformation-configuration)

In Map Card: [map cropping](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card#cropping-options)

**Reply by ThatTallGuy21** [reply]
That did the trick. Thank you!

**Reply by Brightsid3** [reply]
Hey! So sorry I am new to all of this. I am wanting to do the same but I don't understand the instructions
do I just type: trim: top25 in the editor? I guess I am confused how to format the code. any help would be greatly appreciated!

**Reply by PiotrMachowski** [reply]
@Brightsid3 
```yaml
    map_transformation:
      trim:
        top: 25
        bottom: 20
        left: 30
        right: 40
```

**Reply by Brightsid3** [reply]
Thanks so much for your quick response! That's what I thought, for some reason its still not working for me though. The numbers are red so I am not Sure if there's something wrong there? 
```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.stanley
vacuum_platform: default
map_transformation:
  scale: 2
  rotate: 180
  trim:
    top: 10
    bottom: 20
    left: 30
    right: 40
```
