### DISCUSSION TITLE
Can I remove default status - battery/speed - value on map card?

### DISCUSSION THREAD

**Discussion by JayChun** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#333] [Q&A] [answered]
Hello,
Thanks for great integration!
I've been renewing the layout Dashboard recently.
I want to make a simple map card, Can I remove a red box below?

![image](https://user-images.githubusercontent.com/71179304/187844056-772b13ef-9774-4152-aeb8-259672eaedae.png)

**Comment by PiotrMachowski** [comment, marked as answer]
This is not my card, so I can't answer your question 😉

**Reply by JayChun** [reply]
This is your card, but it is on Custom:button card.
I show you another outside Custom button card. 
![Screenshot_20220901-180734_Home Assistant](https://user-images.githubusercontent.com/71179304/187877331-3e321a95-3ad3-49d4-b106-0917fb2e8a68.jpg)

**Reply by PiotrMachowski** [reply]
Can you show yaml config?

**Reply by JayChun** [reply]
Card yaml
```yaml
type: custom:vacuum-card
entity: vacuum.rockrobo_vacuum_v1
image: default
map: camera.xiaomi_cloud_map_extractor
compact_view: false
show_status: false
show_toolbar: false
show_name: false
```

![Screenshot_20220901-185411_Chrome](https://user-images.githubusercontent.com/71179304/187886728-f6890f9b-fcf5-40e2-b946-c6a25a90bfdf.jpg)
