### DISCUSSION TITLE
Retrieving raw map data

### DISCUSSION THREAD

**Discussion by PiotrMachowski** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#355] [FAQ]
To retrieve map data you have to:
1. Add following lines to config of map extractor:
    ```yaml
    store_map_raw: true
    store_map_path: /config # recommended for installations other than HA core
    ```
    <details>
    <summary>Example config</summary>

    ```yaml
    camera:
      - platform: xiaomi_cloud_map_extractor
        host: !secret xiaomi_vacuum_host
        token: !secret xiaomi_vacuum_token
        username: !secret xiaomi_cloud_username
        password: !secret xiaomi_cloud_password
        store_map_raw: true
        store_map_path: /config
    ```

    </details>

2. Reload Xiaomi Cloud Map Extractor domain using `xiaomi_cloud_map_extractor.reload` service or by restarting HA.
    [![Open your Home Assistant instance and show your service developer tools with a specific service selected.](https://my.home-assistant.io/badges/developer_call_service.svg)](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_cloud_map_extractor.reload)
3. Map file should appear in path that you have specified in your configuration
4. You can send me retrieved raw map file at `piotr.machowski.dev [at] gmail.com`
