### DISCUSSION TITLE
Potential memory leak

### DISCUSSION THREAD

**Discussion by SavageLionCoder** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#370] [General]
Hi, I use Xiaomi-Cloud-Map-Extractor and Vacuum Map card, thank you for your great work.
I'm new to the world of Home Assistant (2 weeks), I've been setting up my devices, different brands and different integrations.

But since yesterday I regularly lose all access to the Home Assistant interface.
When I connected in SSH to my device (Raspberry PI 4 2GB, with the official Home Assistant image), I saw 
"Out of Memory:Killed process xxxxxxxx (python3)." 
While searching on the internet, I saw that it was due to memory leaks related to the different integrations. So I uninstalled them one by one until the memory usage stabilizes.

Finally, it was by deleting Xiaomi Cloud Map Extractor that the memory stabilized. (
I am attaching the memory usage graph. Until uninstall Cloud Map Extractor)
By reinstalling it and disabling the auto refresh I do not observe any leaks.

Could you look on your side to see if you observe the same behavior as me?

Thank you for your help :)

![image](https://user-images.githubusercontent.com/116677880/203082406-3e8a6817-97d7-438f-adb9-678a6825930e.png)

**Comment by PiotrMachowski** [comment]
Can you share your config of Map Extractor?

**Reply by SavageLionCoder** [reply]
Here is the configuration:
```yaml
# Xiaomi_cloud_map_extractor
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    map_transformation:
      scale: 2
    sizes:
      charger_radius: 3
      vacuum_radius: 4
    attributes:
      - calibration_points
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - walls
      - zones
    auto_update: false

**Reply by PiotrMachowski** [reply]
This problem seem to happen when HA can't keep up with refreshing the map. It should go away with this config:

```yaml
# Xiaomi_cloud_map_extractor
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    map_transformation:
      scale: 2
    sizes:
      charger_radius: 3
      vacuum_radius: 4
    attributes:
      - calibration_points
    scan_interval: "00:00:20"
```
Removing unnecessary entries from `attributes` section should also improve memory usage.
