### DISCUSSION TITLE
Need help to calibrate points

### DISCUSSION THREAD

**Discussion by mebitek** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#394] [Q&A]
Hi,
I want to use a custom map image on my card but I have problems with calibration pointss.
flovevac is not working for my dreame_p2041o and I'm not unable to use app_goto_target from HA:

using this service
```
service: xiaomi_miot.send_command
data:
  entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
  method: app_goto_target
  params:
    - 25500
    - 25500
```
I get no response from my robot vacuum

could someone help me?
thanks

**Comment by PiotrMachowski** [comment]
Do you use map from map extractor?

**Reply by mebitek** [reply]
i'm using this config:

```
type: custom:xiaomi-vacuum-map-card
map_source:
  image: >-
    https://nextcloud.mebitek.com/index.php/apps/files_sharing/publicpreview/rs57iAqeyNTFFnW?file=/&fileId=403745&x=1920&y=1080&a=true
calibration_source:
  calibration_points:
    - vacuum:
        x: 9883
        'y': 11230
      map:
        x: 1806
        'y': 503
    - vacuum:
        x: -12723
        'y': -9505
      map:
        x: 190
        'y': 1585
    - vacuum:
        x: 4604
        'y': 6357
      map:
        x: 3408
        'y': 1585
    - vacuum:
        x: -45821
        'y': -37062
      map:
        x: 918
        'y': 320
entity: vacuum.dreame_p2041o_8819_robot_cleaner
vacuum_platform: al-one/hass-xiaomi-miot
```

**Reply by mebitek** [reply]
I'm using this in configuration:
```
    store_map_raw: true
    store_map_image: true
    store_map_path: "/tmp"
```
but I have nothing in /tmp folder
I was thinking to get the rrmap file and map it via gimp image coordinates

**Reply by mebitek** [reply]
finally getting map_data_dreame.vacuum.p2041o.b64 - how to use it?

**Reply by PiotrMachowski** [reply]
You won't get anything from `map_data_dreame.vacuum.p2041o.b64` file. You can check out calibration from `camera` entity and map it to your image by changing "map" coordinates to matching ones on your image

**Reply by mebitek** [reply]
where I can find calibration from camera entity? if I search on entities it has just the image, no other info or attributes

**Reply by PiotrMachowski** [reply]
They are visible in dev tools in attributes

**Reply by mebitek** [reply]
ok, this is the calibration points:
calibration_points: 
```
- vacuum:
    x: 0
    'y': 0
  map:
    x: 58
    'y': 85
- vacuum:
    x: 1000
    'y': 0
  map:
    x: 78
    'y': 85
- vacuum:
    x: 0
    'y': 1000
  map:
    x: 58
    'y': 65
```
so I  open with gimp the map extractor image and the new image.
try to find point 58-85 in the map extractor map and getting new coordinates from the new image pointing in the same area.
I repeated for each point but it is not working: no robot in the map, if I try to send the robot to a spot it returns immediatly to the base

**Reply by PiotrMachowski** [reply]
Vacuum is drawn by the map extractor, not the card, so it won't be shown on your image.
Can you show your full config?

**Reply by mebitek** [reply]
if vacuum and other stuff like path lines are not drawed by the card I think that using image is not so usefull. thanks.
I still have problems changing some colors:

```
camera:
  - platform: xiaomi_cloud_map_extractor
    host:  ****
    token: *****
    username: ****
    password: *****
    country: "de"
    draw: ['all']
    colors:
        color_charger: [47, 186, 36]
        color_charger_outline: [26, 146, 16]
        color_robo: [94, 94, 94]
        color_robo_outline: [126,126,126]
        color_map_wall: [128,128,128]
        color_path: [255, 255, 255]
    room_colors:
        1: [188, 157, 62]
        2: [108, 141, 195]
        3: [88, 161, 176]    
    map_transformation:
        scale: 3
        rotate: 90
    sizes:
        charger_radius: 4
        vacuum_radius: 6        
    attributes:
      - calibration_points
      - rooms
      - walls
      - cleaned_rooms
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - zones
    force_api: dreame
    store_map_raw: true
    store_map_image: true
    store_map_path: "/media"
```
the main problem is color_charger_outline
