### DISCUSSION TITLE
Help with follow path script

### DISCUSSION THREAD

**Discussion by mebitek** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#397] [Q&A] [answered]
I'm trying to implement a change to the follow path script that support also xiaomi_miot al_one template but I have problems passing the final json to the service.
here's the simplfy follow path script code:

```
alias: Vacuum follow path
variables:
  path:
    - - 228
      - 2323
  entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
sequence:
  - repeat:
      count: "{{ path | length }}"
      sequence:
        - service: xiaomi_miot.call_action
          data:
            siid: 4
            aiid: 1
            entity_id: "{{ entity_id }}"
            params:
              - piid: 1
                value: 20
              - piid: 10
                value: >-
                  {% set json = "{\"points\":[[" ~ path[repeat.index-1][0] ~ ","
                  ~ path[repeat.index-1][1] ~ ",1,1,1]]}" %} {{ json |
                  to_json}}                 
            force_params: true
        - wait_template: "{{ is_state(entity_id, 'cleaning') }}"
          timeout: "00:00:30"
          continue_on_timeout: false
        - delay: "00:00:01"
        - wait_template: "{{ is_state(entity_id, 'idle') or is_state(entity_id, 'paused') }}"
          timeout: "00:05:00"
          continue_on_timeout: false
mode: single
icon: mdi:robot-vacuum
```
variables are hardcoded for testing purpose, the issue comes in piid 10 value data.
on trace I get this:
```
Executed: 27 gennaio 2023 07:56:42
Result:
params:
  domain: xiaomi_miot
  service: call_action
  service_data:
    siid: 4
    aiid: 1
    entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
    params:
      - piid: 1
        value: 20
      - piid: 10
        value: '"{\"points\":[[228,2323,1,1,1]]}"'
    force_params: true
  target: {}
running_script: false
limit: 10
```
so the problem is `'"{\"points\":[[228,2323,1,1,1]]}"'` cause I need to get `"{\"points\":[[228,2323,1,1,1]]}"` without `'` character

how to solve it?

**Comment by PiotrMachowski** [comment]
This version might work
```yaml
alias: Vacuum follow path
variables:
  path:
    - - 228
      - 2323
  entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
sequence:
  - repeat:
      count: "{{ path | length }}"
      sequence:
        - service: xiaomi_miot.call_action
          data:
            siid: 4
            aiid: 1
            entity_id: "{{ entity_id }}"
            params:
              - piid: 1
                value: 20
              - piid: 10
                value: |-
                  {{ "{\"points\":[[" ~ path[repeat.index-1][0] ~ "," ~ path[repeat.index-1][1] ~ ",1,1,1]]}" }}
            force_params: true
        - wait_template: "{{ is_state(entity_id, 'cleaning') }}"
          timeout: "00:00:30"
          continue_on_timeout: false
        - delay: "00:00:01"
        - wait_template: "{{ is_state(entity_id, 'idle') or is_state(entity_id, 'paused') }}"
          timeout: "00:05:00"
          continue_on_timeout: false
mode: single
icon: mdi:robot-vacuum
```

**Reply by mebitek** [reply]
it doesn't:

execution:
```
Executed: 27 gennaio 2023 13:36:46
Result:
params:
  domain: xiaomi_miot
  service: call_action
  service_data:
    siid: 4
    aiid: 1
    entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
    params:
      - piid: 1
        value: 20
      - piid: 10
        value:
          points:
            - - 228
              - 2323
              - 1
              - 1
              - 1
    force_params: true
  target: {}
running_script: false
limit: 10
```

value should be a string like `"{\"points\":[[228,2323,1,1,1]]}"`

**Reply by PiotrMachowski** [reply]
How about this one:
```yaml
alias: Vacuum follow path
variables:
  path:
    - - 228
      - 2323
  entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
sequence:
  - repeat:
      count: "{{ path | length }}"
      sequence:
        - service: xiaomi_miot.call_action
          data:
            siid: 4
            aiid: 1
            entity_id: "{{ entity_id }}"
            params:
              - piid: 1
                value: 20
              - piid: 10
                value: |-
                  {{ '{\\"points\\":[[' ~ path[repeat.index-1][0] ~ ',' ~ path[repeat.index-1][1] ~ ',1,1,1]]}' }}
            force_params: true
        - wait_template: "{{ is_state(entity_id, 'cleaning') }}"
          timeout: "00:00:30"
          continue_on_timeout: false
        - delay: "00:00:01"
        - wait_template: "{{ is_state(entity_id, 'idle') or is_state(entity_id, 'paused') }}"
          timeout: "00:05:00"
          continue_on_timeout: false
mode: single
icon: mdi:robot-vacuum
```

**Reply by PiotrMachowski** [reply]
More options:
```
                  {{ '{"points":[[' ~ path[repeat.index-1][0] ~ ',' ~ path[repeat.index-1][1] ~ ',1,1,1]]}' }}
```

```
                  {{ ('{"points":[[' ~ path[repeat.index-1][0] ~ ',' ~ path[repeat.index-1][1] ~ ',1,1,1]]}') | string }}
```

**Reply by mebitek** [reply]
no one works, result is always the same:

```
 params:
      - piid: 1
        value: 20
      - piid: 10
        value:
          points:
            - - 228
              - 2323
              - 1
              - 1
              - 1
```

**Reply by PiotrMachowski** [reply]
Let's try something a little more extreme:
```yaml
        - service: xiaomi_miot.call_action
          data:
            siid: 4
            aiid: 1
            entity_id: "{{ entity_id }}"
            params: |-
              [{"piid":1,"value":20},{"piid":10,"value":"{{ "{\\\"points\\\":[[" ~ path[repeat.index-1][0] ~ "," ~ path[repeat.index-1][1] ~ ",1,1,1]]}" }}"}]
            force_params: true
```

**Reply by mebitek** [reply]
yeah it works,

here th efull working code:

```
alias: Vacuum follow path
fields:
    path:
      name: Path
    entity_id:
      name: Vacuum entity
sequence:
  - repeat:
      count: "{{ path | length }}"
      sequence:
        - service: xiaomi_miot.call_action
          data:
            siid: 4
            aiid: 1
            entity_id: "{{ entity_id }}"
            params: >-
              [{"piid":1,"value":20},{"piid":10,"value":"{{ "{\\\"points\\\":[["
              ~ path[repeat.index-1][0] ~ "," ~ path[repeat.index-1][1] ~
              ",1,1,1]]}" }}"}]
            force_params: true
        - wait_template: "{{ is_state(entity_id, 'cleaning') }}"
          timeout: "00:00:30"
          continue_on_timeout: false
        - delay: "00:00:01"
        - wait_template: "{{ is_state(entity_id, 'idle') or is_state(entity_id, 'paused') or is_state(entity_id, 'returning') }}"
          timeout: 00:05:00
          continue_on_timeout: false
mode: single
icon: mdi:robot-vacuum
```

maybe you can integrate it on xiaomi miot template?

**Reply by PiotrMachowski** [reply]
Every vacuum that uses Xiaomi Miot has a different service call schema, so I don't think I will include this in the card. You can post it here (or I can do it):
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/406

Please also mark this thread as an answer

**Comment by mebitek** [comment]
not yet. I see that we need `'{"points":[[228,2323,1,1,1]]}'`

with your last version I get:

```
Executed: 27 gennaio 2023 14:19:54
Result:
params:
  domain: xiaomi_miot
  service: call_action
  service_data:
    siid: 4
    aiid: 1
    entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
    params:
      - piid: 1
        value: 20
      - piid: 10
        value: '{\"points\":[[228,2323,1,1,1]]}'
    force_params: true
  target: {}
running_script: false
limit: 10
```

**Comment by mebitek** [comment, marked as answer]
full working script

```
alias: Vacuum follow path
variables:
  path:
    - - 228
      - 2323
  entity_id: vacuum.dreame_p2041o_8819_robot_cleaner
sequence:
  - repeat:
      count: "{{ path | length }}"
      sequence:
        - service: xiaomi_miot.call_action
          data:
            siid: 4
            aiid: 1
            entity_id: "{{ entity_id }}"
            params:
              - piid: 1
                value: 20
              - piid: 10
                value: |-
                  {{ '{\\"points\\":[[' ~ path[repeat.index-1][0] ~ ',' ~ path[repeat.index-1][1] ~ ',1,1,1]]}' }}
            force_params: true
        - wait_template: "{{ is_state(entity_id, 'cleaning') }}"
          timeout: "00:00:30"
          continue_on_timeout: false
        - delay: "00:00:01"
        - wait_template: "{{ is_state(entity_id, 'idle') or is_state(entity_id, 'paused') }}"
          timeout: "00:05:00"
          continue_on_timeout: false
mode: single
icon: mdi:robot-vacuum
```
