### DISCUSSION TITLE
Crop map image of unneeded empty pixels

### DISCUSSION THREAD

**Discussion by lageorgem** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#486] [General]
Hey, I have a Roborock S6 and the map generated seems to have a lot of extra pixels. This is a bit annoying because the map card doesn't have a default zoom setting, so I'm interested in figuring out a way to cut the extra pixels around the map that are empty.

**Comment by PiotrMachowski** [comment]
[Map transformation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#map-transformation-configuration)
```yaml
    map_transformation:
      scale: 2
      trim:
        top: 10
        bottom: 20
        left: 30
        right: 40
```
> This is a bit annoying because the map card doesn't have a default zoom setting

[it does](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card#cropping-options)
