### DISCUSSION TITLE
Additional presets/load multi map does not update map

### DISCUSSION THREAD

**Discussion by nemezis1** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#511] [Q&A] [answered]
Hi.
I have configured vacuum map but it does not update while I've change floors. Map is not update then i change preset or by press icons.
```yaml
type: custom:xiaomi-vacuum-map-card
preset_name: Makumba Parter
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.makumba
vacuum_platform: default
title: ''
activate_on_switch: true
activate:
  service: vacuum.send_command
  service_data:
    entity_id: vacuum.makumba
    command: load_multi_map
    params: 1
append_icons: true
icons:
  - icon: mdi:home-floor-0
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: load_multi_map
        params: 1
        entity_id: vacuum.makumba
  - icon: mdi:home-floor-1
    tap_action:
      action: call-service
      service: vacuum.send_command
      service_data:
        command: load_multi_map
        params: 0
        entity_id: vacuum.makumba
map_locked: true
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - 16623
            - 22366
            - 26814
            - 28602
  - template: vacuum_goto
additional_presets:
  - preset_name: Makumba Piętro
    entity: vacuum.makumba
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
    map_locked: true
    append_icons: false
    icons: []
    activate_on_switch: true
    activate:
      service: vacuum.send_command
      service_data:
        entity_id: vacuum.makumba
        command: load_multi_map
        params: 0
    map_modes:
      - template: vacuum_clean_zone
      - template: vacuum_goto
```

configuration.yaml setup:
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    auto_update: false
    attributes:
      - calibration_points
      - rooms
    store_map_raw: true
```
But map is updated when i call: 
```yaml
type: button
tap_action:
  action: call-service
  service: homeassistant.update_entity
  target:
    entity_id: camera.xiaomi_cloud_map_extractor
```
I also have configured Update Map Extractor camera blueprint.
