### DISCUSSION TITLE
Failed to retrieve map from vacuum

### DISCUSSION THREAD

**Discussion by diegofrances** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#530] [Q&A]
Hello @PiotrMachowski,

I am using your integration but I keep receiving the error "Failed to retrieve map from vacuum" on the Dashboard.

![imagen](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/119085726/60711006-01f0-4535-a37e-bb152b3951dd)

As you have suggested I am using your blueprint "https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/blob/master/blueprints/automation/update_map_extractor.yaml".

![imagen](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/119085726/3ab82d45-0e51-42ad-b534-40401b1fa11e)

Please find also the content on my configuration.yaml file:

```
############################
#       Roborock S5        #
############################

camera:
  - platform: xiaomi_cloud_map_extractor
    host: XX.XX.XX.XX
    token: 12345.....
    username: user@mail.com
    password: password
    country: "de"
    name: "La Kelly"
    draw: ["all"]
    attributes:
      - calibration_points
    auto_update: false
    store_map_raw: false
    store_map_image: true
    store_map_path: "/tmp"
    force_api: xiaomi

```
Can you please help me to fix the issue?

Thank you in advance.

**Comment by PiotrMachowski** [comment]
Is map available in Xiaomi Home?

**Reply by diegofrances** [reply]
Yes, just tested and I can retrieve it

**Reply by PiotrMachowski** [reply]
Which vacuum model do you have? Is there anything in HA logs?

**Reply by diegofrances** [reply]
Roborock S5 but does not work with Roborock app I have to manage it with the Xiaomi Home one.

Logs regarding the word map in HA:

Este error se originó a partir de una integración personalizada.

Registrador: custom_components.xiaomi_cloud_map_extractor.camera
Fuente: custom_components/xiaomi_cloud_map_extractor/camera.py:356
integración: xiaomi_cloud_map_extractor (documentación, problemas)
Ocurrió por primera vez: 11 de mayo de 2024, 03:45:15 (2 ocurrencias)
Último inicio de sesión: 09:14:06

Unable to retrieve map data

Logs regarding the word vacuum in HA:
Registrador: homeassistant.helpers.frame
Fuente: helpers/frame.py:190
Ocurrió por primera vez: 10 de mayo de 2024, 23:31:51 (3 ocurrencias)
Último inicio de sesión: 10 de mayo de 2024, 23:32:27

Detected that custom integration 'vacuum_zones' accesses hass.helpers.discovery. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from discovery directly at custom_components/vacuum_zones/__init__.py, line 25: hass.async_create_task(hass.helpers.discovery.async_load_platform(, please report it to the author of the 'vacuum_zones' custom integration
Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

**Reply by PiotrMachowski** [reply]
Try rebooting the vacuum and then reloading Map Extractor from the HA Dev tools

**Comment by diegofrances** [comment]
Hello,

I forgot to mention that after removing the lines “scan_interval:” and “seconds: 30” I am not facing the issue anymore, there was an issue at the “configuration.yaml” file.

I created some shortcuts with a one touch action buttons to make the area cleaning even easier:

***@***.***

Thank you for your support

Diego

"Those who cannot remember the past, are condemned to repeat it"


De: Piotr Machowski ***@***.***>
Enviado el: domingo, 12 de mayo de 2024 21:52
Para: PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor ***@***.***>
CC: diegofrances ***@***.***>; Author ***@***.***>
Asunto: Re: [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor] Failed to retrieve map from vacuum (Discussion #530)


Try rebooting the vacuum and then reloading Map Extractor from the HA Dev tools

**Comment by dluX-au** [comment]
Hi there,

Just wanted to tack onto this thread as I am facing a similar issue.

I have everything setup as you have described with your blueprint to prevent pinging the API (didn't run it when I first installed and got locked from accessing the map for a couple of days)

I can get everything to work however once I leave it overnight, when I check HA the next morning it has gone back to 'failed to retrieve map from vacuum'. It still displays correctly in the Xiaomi app. Running the service "xiaomi_cloud_map_extractor: Reload" does not fix it. When I disable the automation and run the service however, it does fix the issue. Then it all works as described until I leave it overnight, and get up the next day and it fails to receive the map again.

config.yaml:

```
# Roborock S6 Pure #
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
    auto_update: false
```

automation:

```
alias: Update Map Extractor camera
description: ""
use_blueprint:
  path: PiotrMachowski/update_map_extractor.yaml
  input:
    vacuum: vacuum.roborock_vacuum_a08
    camera: camera.xiaomi_cloud_map_extractor
    mode_to_handle: two_intervals
    interval_docked: 8000
    interval_cleaning: 10
```

I do have this in the log that occurred overnight:

```
Logger: homeassistant.components.xiaomi_miio
Source: helpers/update_coordinator.py:321
integration: Xiaomi Miio (documentation, issues)
First occurred: 3:22:34 AM (2 occurrences)
Last logged: 7:13:34 AM

Timeout fetching roborock.vacuum.a08 data
```


Any ideas? Thanks in advance.
