### DISCUSSION TITLE
Updated map in Mi Home app. Rooms ids and coordinates didn't update.

### DISCUSSION THREAD

**Discussion by GedasBu** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#556] [Q&A]
Hello, I have remapped my house with mi home map. How can update new rooms ids and coordinates in home assistant? Tried to push Generate rooms config, but all rooms configuration doesn't update. On code editor it show old room configuration. Thanks

**Comment by PiotrMachowski** [comment]
You have to remove the predefined_selections config from the card and generate rooms again

**Reply by GedasBu** [reply]
removed predefined_selections.
Pressed: Generate rooms config.
In the config i get this picture
![image](https://github.com/user-attachments/assets/19550255-02bb-4c5c-b169-d742c20b9fde)

**Reply by PiotrMachowski** [reply]
what is the config of map extractor?

**Reply by GedasBu** [reply]
![image](https://github.com/user-attachments/assets/8219b524-30ed-409d-a74a-014c09266aee)

**Reply by GedasBu** [reply]
The map picture is the same, like in mi home app. I only cannot get rooms in HA to tell robot what to clean.

**Reply by PiotrMachowski** [reply]
Try removing lines 13 and 14 from card's config and generate rooms config again

**Reply by GedasBu** [reply]
Nothing happens:
![image](https://github.com/user-attachments/assets/5f61d153-2a71-4dc7-824f-7681b0cd9726)

**Reply by PiotrMachowski** [reply]
Can you show attributes of camera entity? Is the map card inside any other card?

**Reply by GedasBu** [reply]
Not sure how to view atrributes.

**Reply by PiotrMachowski** [reply]
Here:
[![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/)

**Reply by GedasBu** [reply]
```yaml
access_token: ######
calibration_points:
  - vacuum:
      x: 25500
      "y": 25500
    map:
      x: 287
      "y": 232
  - vacuum:
      x: 26500
      "y": 25500
    map:
      x: 307
      "y": 232
  - vacuum:
      x: 25500
      "y": 26500
    map:
      x: 287
      "y": 212
rooms:
  "16":
    x0: 21400
    y0: 23150
    x1: 26200
    y1: 29750
  "17":
    x0: 17950
    y0: 28650
    x1: 21350
    y1: 32100
  "18":
    x0: 21400
    y0: 29650
    x1: 22550
    y1: 31150
  "19":
    x0: 22450
    y0: 28800
    x1: 27750
    y1: 32050
  "20":
    x0: 19500
    y0: 19700
    x1: 21400
    y1: 24850
  "21":
    x0: 16900
    y0: 22200
    x1: 19650
    y1: 24950
  "22":
    x0: 14900
    y0: 24900
    x1: 21200
    y1: 28400
vacuum_room: 16
model: roborock.vacuum.s5e
used_api: xiaomi
entity_picture: >-
  /api/camera_proxy/camera.xiaomi_cloud_map_extractor?token=#####
friendly_name: Xiaomi Cloud Map Extractor
supported_features: 1
```
