### DISCUSSION TITLE
Automate the cleaning of the selected room

### DISCUSSION THREAD

**Discussion by menfis911** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#566] [Q&A]
Hey, everybody! 
I would like to thank for this development, very nice thanks.
But I have a question, I do not quite understand how to run in the automation that the robot would clean in a particular room, can anyone advise?
Problems with unloading rooms no, everything works.

**Comment by PiotrMachowski** [comment]
Answer to this question depends on the integration that you use to control the vacuum and vacuum model.

**Comment by proasnet** [comment]
Hi @menfis911 ,
I have a buttons for cleaning specific room. You need find a numbers for rooms.
Method 1 is to get it from the cloud, but I couldn't do that.
Method 2 is to use a command and try the numbers one by one. In my case it only worked from number 16.
I have this command in scripts, 1 script for each room. What I have in the script, you can have in automation.

```
alias: Clean Living Room
sequence:
  - action: xiaomi_miio.vacuum_clean_segment
    target:
      device_id: f2ce46d3e5cac66fca93cbdce6bbeebd
    data:
      segments: 18
description: ""
```

As you see, in my example for one specific room is number 18. In my case, I have more scripts, named as "clean_living_room" or others, with range from 16 to 26. In your case may be numbers in other range.
