### DISCUSSION TITLE
Config for color_path

### DISCUSSION THREAD

**Discussion by proasnet** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#587] [Q&A]
Dears, please help me to config color path. I need color of a cleaned path as white.
I have this config
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    color_path: [0xFF,0xFF,0xFF]
    draw: ['all']
    attributes:
      - calibration_points  
```

After check, I get this message: 
`Invalid config for 'xiaomi_cloud_map_extractor' from integration 'camera' at configuration.yaml, line 93: 'color_path' is an invalid option for 'camera.xiaomi_cloud_map_extractor', check: color_path`

Thanks very much.

**Comment by PiotrMachowski** [comment]
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points  
    colors:
      color_path: [0xFF,0xFF,0xFF]

```
