### DISCUSSION TITLE
Map loads, but will not actually update (i.e. not show vaccum position/snail trail) unless I open Mi Home app

### DISCUSSION THREAD

**Discussion by amit-nz** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#614] [Q&A] [answered]
Hello everyone. I've got this issue where I can see my map, send my bot to clean specific rooms/selections etc and it all works great. However, the map will not update at all until I open up the Mi Home app and tap on my bot to view the map. Its almost like this action forces the map to redraw, then that is downloaded by the integration and displayed?

It would be great if I could see in near real time where my bot was plus the "snail trail" it leaves (which is the white line that indicates where it has been this cleaning cycle).

Ever since I set this integration up I have had this issue. It has been a minor inconvenience but I thought I"d check and see if it is some silly config issue I may have made?

I'm on cloud map integration v2.2.3 (via HACS), and HA OS 2025.4.4 (latest at time of writing), and my bot is a Xiaomi Robot Vacuum Mop 1C, and my config is as below.

```
# Xiaomi Cloud Map Extractor
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    attributes:
      - charger
      - cleaned_rooms
      - goto
      - ignored_obstacles
      - map_name
      - no_go_areas
      - no_mopping_areas
      - vacuum_position
      - zones
      - calibration_points
      - rooms
```

**Comment by PiotrMachowski** [comment]
What model code does your vacuum have?

**Reply by amit-nz** [reply]
Model: STYTJ01ZHM
Charging Dock Model: CDZ1902
SKU: SKV4093GL

**Reply by PiotrMachowski** [reply]
I meant the one in the following format: `dreame.vacuum.mc1808`

**Reply by amit-nz** [reply]
Good guess, that is the one I have! 
![image](https://github.com/user-attachments/assets/f718014a-e200-40dd-b932-df6aed3bd45f)

**Reply by PiotrMachowski** [reply]
In such case here's the issue you're interested in: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/299

**Reply by amit-nz** [reply, marked as answer]
Finally had the opportunity to come back to this. The below action is working to update the map. 

```
action: xiaomi_miot.call_action
data:
  entity_id: vacuum.dreame_mc1808_dea3_robot_cleaner
  siid: 23
  aiid: 1
  params:
    - piid: 2
      value: '{"req_type":1,"frame_type":"I","force_type":1}'
```

**When firing this event, try not to fire it too often, because if you do that you may get blacklisted from the API server** - see issue #422 

If anyone has issues figuring this out, the way I did it was I went to the miot spec site & found my vac:

https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:dreame-mc1808:1

From there I searched for "map", the siid for which was 23. Then I was able to infer the `siid`, `aiid` and `piid` basically via trial and error. From there I setup an automation that only fires when the vaccum state != charging/docked.

Thanks for the pointer @PiotrMachowski !
