### ISSUE TITLE
Please add ability to place random text on the map

### ISSUE THREAD

**Issue by leva3000** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#12]
It would be nice to allow render random text on the map to place some labels for the rooms. Something like:
```
labels:
  - name: Kitchen
    x: 120
    y: 50
    size: 10
  - name: Living room
    x: 240
    y: 110
    size: 10
```
Or probably it's possible to get room names from Mi Cloud and render them as it does in Mi Home.
