### ISSUE TITLE
Support for Roidmi vacuums

### ISSUE THREAD

**Issue by PiotrMachowski** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#127]
Vacuums confirmed to use this API:
* `roidmi.vacuum.v60` (Roidmi EVE Plus)
* `viomi.vacuum.v18` (Viomi S9)

You can help in implementation of this feature by sending your map file and a screenshot from Xiaomi app at 

`piotr.machowski.dev [at] gmail [dot] com`.

To get raw map file you have to use following config:
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    store_map: true
    force_api: roidmi
```
and then follow steps provided in documentation: [Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map).
