### ISSUE TITLE
Camera prints "OK" and no errors

### ISSUE THREAD

**Issue by Julrouxxx** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#147]
Hello,

I've installed this component via HACS. Here is my configuration.yaml

``` yaml 
camera:
    - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.84
    token: !secret xiaomi_s5_token
    username: !secret xiaomi_email
    password: !secret xiaomi_password
    draw: ['all']
    attributes:
      - calibration_points
```

And here's what I've on Hassio:
![image](https://user-images.githubusercontent.com/6631207/124855946-01a5a780-dfaa-11eb-9598-f20414b30159.png)

I've no errors on log (appart from Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds)
My vacuum is a Rockrobo S5

**Comment by PiotrMachowski** [comment]
@Julrouxxx can you check if v1.1.1 works for you?

**Comment by Julrouxxx** [comment]
With 1.1.1 the camera entity is showing nothing at all

**Comment by PiotrMachowski** [comment]
Can you check version from [this branch](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/tree/dev_roidmi_support) with enabled debug logging?

```yaml
logger:
  default: info
  logs:
    custom_components.xiaomi_cloud_map_extractor: debug
```
