### ISSUE TITLE
Invalid config for [camera.xiaomi_cloud_map_extractor]: string value is None for dictionary value @ data[‘password’]. Got None. (See ?, line ?).

### ISSUE THREAD

**Issue by kikofhm** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#167]
my secrets.yaml 

```
# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
some_password: welcome
xiaomi_vacuum_host: XPTO
xiaomi_vacuum_token: XPTO
xiaomi_cloud_username: BLABLABLA
xiaomi_cloud_password: BLABLABLA
```
my configuration.yaml

```
# roborock s5 max
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
```

### _Check configuration_

Configuration invalid

`Invalid config for [camera.xiaomi_cloud_map_extractor]: string value is None for dictionary value @ data[‘password’]. Got None. (See ?, line ?).`

What I'm doing wrong?? How to fix?
