### ISSUE TITLE
Picture Entity Card: some component options don't work / break

### ISSUE THREAD

**Issue by igorsantos07** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#175]
I was testing out the component with a Picture Entity Card, but the map is too small for it. I then tried using `map_transformation.scale` and `trim`, but...

- `trim` doesn't seem to make any difference. Whatever values I input for `top` or `bottom`, the entity shows the same way. Isn't it supposed to get shorter, or make the map content bigger?
![image](https://user-images.githubusercontent.com/532299/133727547-7aafc2de-576d-472e-a0ea-1a38537391a7.png)

- `scale` seems to....... cause successive restarts to HA? I tried a couple of values: `0.5` and `2` doesn't seem to make any difference as well, but `5` seems to cause HA to crash / restart forever.

-----------

Current config that causes those issues:
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_host
    token: !secret xiaomi_token
    username: !secret xiaomi_user
    password: !secret xiaomi_pwd
    draw: ['all']
    map_transformation:
      rotate: 90
      scale: 5
      trim:
        top: 50
        bottom: 50
```
