### ISSUE TITLE
Set map colours based on theme

### ISSUE THREAD

**Issue by bremor** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#187]
Hi, love this component, absolutely fantastic work here.

One thing I was wondeirng, if we could access the colours in the theme, so for example, set the background colour of my maps, to match the background colour of my theme. This way, the map will always match in with any light/dark theme I have.
```
camera:
  - platform: xiaomi_cloud_map_extractor
    map_transformation:
      colors:
        color_map_outside: var(--primary-background-color)
```
