### ISSUE TITLE
Undefined in configuration check

### ISSUE THREAD

**Issue by victoroos** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#188]
Hi all,
I get an undefined error when checking the config after adding the recommended lines.

```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret 192.168....
    token: !secret 4b397063c6f5820a6c30346d4f4576
    username: !secret victor_something@hotmail.com
    password: !secret something
    draw: ['all']
    attributes:
      - calibration_points   
```

I tried all the variants, but sometimes HA just keeps checking but doesn't show a green check. I'm doing something wrong for sure..but what?
thanks
Vic
