### ISSUE TITLE
Support for several vacuum cleaners

### ISSUE THREAD

**Issue by tempmaseg** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#190]
I have two xiamoi vacuum cleaners, however I can only run the map extractor for one of them. At start up, it skips the second setup of configuration. 

Is it possible to add support for two or more vacuum cleaners? 

```yaml
camera:
## Vacuum 1##
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiamoi_ip_1
    token: !secret xiamoi_token_1
    username: !secret xiamoi_user
    password: !secret xiamoi_pwd
    draw: ['all']
    attributes:
      - calibration_points 

## Vacuum 2##
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiamoi_ip_2
    token: !secret xiamoi_token_2
    username: !secret xiamoi_user
    password: !secret xiamoi_pwd
    draw: ['all']
    attributes:
      - calibration_points 
```

**Comment by PiotrMachowski** [comment]
It is already possible, you just have to add `name` to at least one of them:
```yaml
camera:
## Vacuum 1##
  - platform: xiaomi_cloud_map_extractor
    name: Vacuum 1
    host: !secret xiamoi_ip_1
    token: !secret xiamoi_token_1
    username: !secret xiamoi_user
    password: !secret xiamoi_pwd
    draw: ['all']
    attributes:
      - calibration_points 

## Vacuum 2##
  - platform: xiaomi_cloud_map_extractor
    name: Vacuum 2
    host: !secret xiamoi_ip_2
    token: !secret xiamoi_token_2
    username: !secret xiamoi_user
    password: !secret xiamoi_pwd
    draw: ['all']
    attributes:
      - calibration_points 
```
