### ISSUE TITLE
Roborock S6 MaxV - room name is not extracted

### ISSUE THREAD

**Issue by new-kirte** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#210]
Hi,
Here is what I am getting when I am checking room names:
```yaml
access_token: **************
calibration_points:
  - vacuum:
      x: 25500
      'y': 25500
    map:
      x: 243
      'y': 381
  - vacuum:
      x: 26500
      'y': 25500
    map:
      x: 263
      'y': 381
  - vacuum:
      x: 25500
      'y': 26500
    map:
      x: 243
      'y': 361
charger:
  x: 25932
  'y': 25138
cleaned_rooms: null
country: tw
goto: null
goto_path: null
goto_predicted_path: null
ignored_obstacles: null
ignored_obstacles_with_photo: []
image:
  size: 301678
  offset_y: 326
  offset_x: 267
  height: 566
  scale: 1
  rotation: 0
  width: 533
is_empty: false
map_name: roboroommap%2F321577025%2F0
no_go_areas:
  - x0: 21150
    y0: 37950
    x1: 22100
    y1: 37950
    x2: 22100
    y2: 37500
    x3: 21150
    y3: 37500
  - x0: 20600
    y0: 27600
    x1: 21300
    y1: 27600
    x2: 21300
    y2: 26900
    x3: 20600
    y3: 26900
  - x0: 30150
    y0: 33450
    x1: 30950
    y1: 33450
    x2: 30950
    y2: 32550
    x3: 30150
    y3: 32550
  - x0: 21606
    y0: 23016
    x1: 23109
    y1: 23016
    x2: 23109
    y2: 22152
    x3: 21606
    y3: 22152
no_mopping_areas: []
obstacles: null
obstacles_with_photo: []
path:
  point_length: 0
  point_size: 4
  angle: 0
  path: []
room_numbers:
  **'16': null
  '17': null
  '18': null
  '19': null
  '20': null
  '21': null
  '22': null
  '23': null**
rooms:
  '16':
    x0: 19200
    y0: 21300
    x1: 33400
    y1: 25650
  '17':
    x0: 27950
    y0: 21450
    x1: 29700
    y1: 23650
  '18':
    x0: 22600
    y0: 31700
    x1: 29700
    y1: 42350
  '19':
    x0: 27350
    y0: 33500
    x1: 31800
    y1: 39450
  '20':
    x0: 30000
    y0: 26750
    x1: 35900
    y1: 34500
  '21':
    x0: 15400
    y0: 24950
    x1: 33000
    y1: 40650
  '22':
    x0: 26200
    y0: 25700
    x1: 27850
    y1: 26900
  '23':
    x0: 29250
    y0: 31850
    x1: 31550
    y1: 36800
vacuum_position:
  x: 25784
  'y': 25240
  a: 4294967262
vacuum_room: 21
vacuum_room_name: null
walls:
  - x0: 28150
    y0: 23650
    x1: 28900
    y1: 23650
  - x0: 27800
    y0: 26600
    x1: 27800
    y1: 25700
model: roborock.vacuum.a10
used_api: xiaomi
entity_picture: >-
  /api/camera_proxy/camera.roborock_vacuum?token=***************
friendly_name: Roborock Vacuum
supported_features: 1
```
But Mi Home shows room names without any issues.
