### ISSUE TITLE
After RC4 update no map extaction

### ISSUE THREAD

**Issue by Jo-Jo1987** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#217]
Hi,

Yesterday i faced issues all over the place with Xiaomi cloud DE servers.
Now this has been fixed in Xiaomi miot auto and as well in your xiaomi cloud map extractor.

I use a roborock S7 , but after all the updates. I lost my map and it does not start up correct
Also my home assistant keeps starting , and waiting on something right now and became very slow
```yaml
xiaomi_miot:
  username: 
  password: 
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 
    token: 
    username:
    password: 
    draw: ['all']
    attributes:
      - calibration_points
```   
Using above settings in my config.yaml
