### ISSUE TITLE
Failed to retrieve device

### ISSUE THREAD

**Issue by sir90ha** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#219]
Good afternoon lately on two devices I get an error:
Failed to retrieve device
![IMG_20220104_080845](https://user-images.githubusercontent.com/71610337/148012211-b756e733-ec02-4023-88b1-9a70405874ae.jpg)

```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.40
    token: !secret vacuum
    username: !secret vacuumlog
    password: !secret vacuumpass
    draw: ['all']
    attributes:
      - calibration_points
```
