### ISSUE TITLE
Map/room colors from the README

### ISSUE THREAD

**Issue by pannal** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#226]
Hey,

I love the color configuration for the custom colors in the README:
![image](https://user-images.githubusercontent.com/1359593/150520535-f2ad793e-0296-4b7f-92b2-62c09dc8a1b4.png)

Could you provide us with the config to achieve the same?

I've tried but I never really matched that beautiful image.

Thanks!

**Comment by PiotrMachowski** [comment]
My vacuum doesn't have room support, so you probably will have to override room colors as well
```yaml
  colors:
    color_map_inside: [50, 50, 50]
    color_map_outside: [0, 0, 0, 128]
    color_map_wall: [255,255,255]
```
