### ISSUE TITLE
Always warning on update over x seconds

### ISSUE THREAD

**Issue by sasukebinbin** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#236]
Always receive below 2 msg

Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds

**Comment by Mick51** [comment]
![Screenshot_20220208-234837_Home Assistant](https://user-images.githubusercontent.com/40418405/153088823-3d435c41-95e6-461e-a18f-145d2be3fa71.jpg)
`Logger: homeassistant.components.camera
Source: helpers/entity_platform.py:719
Integration: Caméra (documentation, issues)
First occurred: 21:54:41 (36 occurrences)
Last logged: 23:43:29

Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05`

**Comment by elad-bar** [comment]
any update on that issue?
map is being sampled every 10 seconds, when device is not connected having the error appear in logs will not assist anything,
I think that the code that samples the cloud or device should continue sample it the same but without relation to the camera component, meaning it should be isolated to some kind of coordinator which will do the fetch data, while camera component is just taking the last state from the coordinator,
can you please fix it?

thanks

**Comment by PiotrMachowski** [comment]
@elad-bar won't the coordinator cause similar entries in logs?

**Comment by elad-bar** [comment]
@PiotrMachowski the warning messages are part of the base component, meaning if there is no response in {scan_interval}, it will throw message - every time it tries to update,
with the coordinator, you control which message to throw, so essentially, you can write it once to log when the status is being changed from avialable to not avialble.
In addition, the coordinator is holding the state, meaning the camera component will not need to wait for response, it will return the latest stored in the coordinator.

**Comment by elad-bar** [comment]
right, but you can catch the exception and only log it if previous state was different

**Comment by elad-bar** [comment]
Please review the PR (#289)

**Separation between the camera component and data provider**

-	Add vacuum manager to handle all the logic
-	Camera component will use the latest state of the vacuum manager
-	Map status to log messages - every time status is being changed, it will be logged accordingly, no need to call logger
-	Map device to handlers instead of IF statement

**Comment by tomlut** [comment]
For some reason this has become much more of an isuue after updating to the core-2022.7.0b0 beta version. 

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:712
First occurred: 12:37:06 (2 occurrences)
Last logged: 12:40:12

Update of camera.upstairs_vacuum is taking over 10 seconds
Update of camera.downstairs_vacuum is taking over 10 seconds
------
This error originated from a custom integration.

Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:356
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 12:05:02 (10 occurrences)
Last logged: 13:58:02

Unable to retrieve map data
```

There does not seem to be an issue with the cameras though:

![Screenshot 2022-07-01 at 14-04-15 Administration – Home Assistant](https://user-images.githubusercontent.com/10679300/176821246-fbe70bd4-9a41-4ec4-bb2e-035067d34c4d.png)

cameras.yaml
```
- platform: xiaomi_cloud_map_extractor
  name: Upstairs Vacuum
  host: 10.1.1.13
  token: !secret vacuum_token_2
  username: !secret vacuum_user
  password: !secret vacuum_passwd
  draw: ['all']
  auto_update: true
  scan_interval:
    seconds: 60
  colors:
    color_map_outside: [0, 0, 0, 0]
  map_transformation:
    rotate: 270
  attributes:
    - calibration_points

- platform: xiaomi_cloud_map_extractor
  name: Downstairs Vacuum
  host: 10.1.1.12
  token: !secret vacuum_token_1
  username: !secret vacuum_user
  password: !secret vacuum_passwd
  draw: ['all']
  auto_update: true
  scan_interval:
    seconds: 60
  colors:
    color_map_outside: [0, 0, 0, 0]
  attributes:
    - calibration_points
```
