### ISSUE TITLE
Error: Update for camera.vacuum_extractor_camera fails

### ISSUE THREAD

**Issue by HepoH3** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#249]
It's weird but I don't remember that I changed or updated anything related but now I've got this repeatedly (thouthands times) error:

> Update for camera.vacuum_extractor_camera fails
<details>
  <summary>Traceback (most recent call last):</summary>

    File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in async_update_ha_state await self.async_device_update()
    File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 725, in async_device_update raise exc
    File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs)
    File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 261, in update self._handle_map_data(map_name)
    File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 318, in _handle_map_data map_data, map_stored = self._device.get_map(map_name, self._colors, self._drawables, self._texts,
    File "/config/custom_components/xiaomi_cloud_map_extractor/common/vacuum.py", line 28, in get_map map_data = self.decode_map(response, colors, drawables, texts, sizes, image_config)
    File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/vacuum.py", line 15, in decode_map return MapDataParserViomi.parse(unzipped, colors, drawables, texts, sizes, image_config)
    File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/map_data_parser.py", line 157, in parse MapDataParserViomi.parse_section(buf, 'unknown2', map_id)
    File "/config/custom_components/xiaomi_cloud_map_extractor/viomi/map_data_parser.py", line 313, in parse_section raise ValueError(

    ValueError: error parsing section unknown2 at offset 0xaa198: magic check failed. Magic: 0x1000ece7, Map ID: 0x0
</details>

My vacuum is STYJ02YM. Config is here:
```
- platform: xiaomi_cloud_map_extractor
  name: vacuum_extractor_camera
  host: !secret kraken_ip
  token: !secret kraken_token
  username: !secret xiaomi_username
  password: !secret xiaomi_password
  country: cn
  draw: ["all"]
  attributes:
    - calibration_points
  store_map_raw: true
  map_transformation:
    scale: 4
    rotate: 270
    trim:
      top: 40
      bottom: 43
      left: 40
      right: 44
```
