### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by septarchy** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#250]
I've added the following to my config:

# Xiaomi
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret 192.168.1.229
    token: !secret obfuscated
    username: !secret obfuscated
    password: !secret obfuscated
    draw: ['all']
    attributes:
      - calibration_points

But i keep getting the following message:
Failed to call service homeassistant/restart. The system cannot restart because the configuration is not valid: Error loading /home/homeassistant/homeassistant/configuration.yaml: Secret 192.168.1.229 not defined

What am i doing wrong? I just copied the config and edited it...

**Comment by appel** [comment]
Try removing `!secret` from the host parameter:

```platform: xiaomi_cloud_map_extractor
host: 192.168.1.229
token: !secret obfuscated
username: !secret obfuscated
password: !secret obfuscated
draw: ['all']
attributes:
calibration_points

**Comment by septarchy** [comment]
> Try removing `!secret` from the host parameter:

I already tried that but it's just giving me the same error over and over again.

**Comment by appel** [comment]
Have you tried it like this?

configuration.yaml:

````
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
````
secrets.yaml (add your own details):

````
xiaomi_vacuum_host: 192.168.1.xxx
xiaomi_vacuum_token: "your_token_here_within_quotes"
xiaomi_cloud_username: "your_userid_here_within_quotes"
xiaomi_cloud_password: "your_password_here_within_quotes"
````

This is what worked for me (set it up just now).
