### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by simgunz** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#254]
I have trouble make the integration login:

This is my configuration:
configuration.yaml
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    map_transformation:
      rotate: 0
    attributes:
      - calibration_points
```

secrets:
```
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
xiaomi_vacuum_token: unquoted_token
xiaomi_vacuum_host: unquoted_ip
xiaomi_cloud_username: unquoted_email or xiaomi_id
xiaomi_cloud_password: unquoted_password
```

The token and ip are correct because I obtained them with token extractor and tested with `mirobo`.
I have tried my email and xiaomi id as a username.

I have tried with two-factor auth on and off.

I had some trouble making the token extractor work because it was getting the captcha. After loggining in from the browser to the xiaomii account a few times and solving the captcha I managed to make the token extractor work.

What else can I try?
