### ISSUE TITLE
Two different Roborocks

### ISSUE THREAD

**Issue by digitalit** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#257]
Hi guys,

I just bought another Roborock and i wonder how i shall do this in config file?

```
camera:
    platform: xiaomi_cloud_map_extractor
    host: !secret vacuum_host_s5
    token: !secret vacuum_token_s5
    username: !secret vacuum_username_s5
    password: !secret vacuum_password_s5
    name: "Roborock S5 Max"
    draw: ["all"]
    attributes:
        calibration_points
        room_numbers
    platform: xiaomi_cloud_map_extractor
    host: !secret vacuum_host_s7
    token: !secret vacuum_token_s7
    username: !secret vacuum_username_s7
    password: !secret vacuum_password_s7
    name: "Roborock S7 Max"
    draw: ["all"]
    attributes:
        calibration_points
        room_numbers
```

Please point me in the right direction :)
