### ISSUE TITLE
Can't add two different maps

### ISSUE THREAD

**Issue by mmanchev** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#261]
I'm having problems to add two different maps sources. I have 2 vaccum robot cleners (S7 and S5 max) but I can see only one map.
```yaml
  - platform: xiaomi_cloud_map_extractor
    name: RoborockS7Camera
    host: 192.168.10.111
    token: XXXXXXXXXXX
    username: XXXXXXXXXXX
    password: XXXXXXXXXXX
    draw: ['all']
    attributes:
      - calibration_points

  - platform: xiaomi_cloud_map_extractor
    name: RoborockS5MaxCamera
    host: 192.168.10.111
    token: XXXXXXXXXXX
    username: XXXXXXXXXXX
    password: XXXXXXXXXXX
    draw: ['all']
    attributes:
      - calibration_points
```
<img width="938" alt="Screenshot 2022-03-13 at 15 10 58" src="https://user-images.githubusercontent.com/27730443/158061888-44b68667-6c6c-4739-a447-14d32c612723.png">
