### ISSUE TITLE
Error: unknown pixel_types: {5} 

### ISSUE THREAD

**Issue by jaegerschnitzel** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#275]
In my log file I get the following error:

```
Logger: custom_components.xiaomi_cloud_map_extractor.roidmi.image_handler
Source: custom_components/xiaomi_cloud_map_extractor/roidmi/image_handler.py:64
Integration: xiaomi_cloud_map_extractor ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues))
First occurred: 17:25:15 (140 occurrences)
Last logged: 17:36:50
unknown pixel_types: {5}
```

My robot vacuum is "roidmi.vacuum.v60" and my configuration:
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.100.x
    token: xxx
    username: xxx
    password: xxx
    country: de
    draw: ['all']
    force_api: roidmi
    attributes:
      - calibration_points
```

I'm running Home Assistant 2022.4.5 and activated debug logging in my configuration.yaml.
Let me know if you need further information.
