### ISSUE TITLE
Outdated map in Cloud Map Extractor

### ISSUE THREAD

**Issue by facetheheat** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#290]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hi there, 
I've got an issue with outdated map in plugin. With Roborock app or Mi app the map is fine.
But in the Xiaomi Cloud Map Extractor it's outdated.

I've created a 4 rooms(yellow, red, green, blue), but in the plugin its only 2 (yellow & green)

Correct map
![IMG_6834](https://user-images.githubusercontent.com/1582399/170069596-567fcc14-adc6-4dc2-bf21-904db1ecabb3.jpeg)

Wrong map
![IMG_6832](https://user-images.githubusercontent.com/1582399/170069624-56b51405-4501-46ea-86c4-664f9cd0444b.jpeg)

 

### What version of am integration has described problem?

v2.2.0

### What was the last working version of an integration?

v2.2.0

### What vacuum model do you have problems with?

roborock.vacuum.a15

### What version of Home Assistant do you use?

2022.5.5

### What type of installation are you running?

Home Assistant Supervised

### Camera's configuration

```yaml
# Roborock S7 Cloud Map
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
```

**Comment by PiotrMachowski** [comment]
How many rooms do you have in attributes when using this config?
```yaml
# Roborock S7 Cloud Map
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
      - rooms
```

**Comment by PiotrMachowski** [comment]
Ok, so the map is up to date, just accidentally room colors are the same for them, so they seem to be merged. You can define your own colors though:
```yaml
# Roborock S7 Cloud Map
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
      - rooms
    room_colors:
      16: [255, 0, 0]
      17: [0, 255, 0]
      18: [0, 0, 255]
      19: [255, 255, 0]
```
