### ISSUE TITLE
Introduce Dreame map refresh 

### ISSUE THREAD

**Issue by auanasgheps** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#299]
### Description

The current implementation for Dreame vacuums is not able to refresh the map on its own, but relies on the mobile app to do so.

This is the detailed behaviour.

- The HA Map card will never update unless you open the mobile app.
- Once the user opens the mobile app, the HA Map will update once.
- Even if you keep the app open, the HA Map doesn't refresh even if the app does update.
- To trigger a refresh, you have to exit the vacuum on the app and re-enter again to trigger another single refresh.

Unfortunately it means we are still heavily dependent by the mobile app.

I have grabbed the Mobile app's log to see what commands are send to the vacuum. I see a lot of calls regarding "get_properties" and these are MioT commands. 

I can share the logs privately with you if you provide an email address.

### Solution

When vacuum operations are started, implement a logic similar to the one in the app, so we can get the map refreshed independently. 

### Context

Other non-Dreame vacuums are able to refresh the map without relying on the app.

**Comment by PiotrMachowski** [comment]
Sure, you can send me log files. `piotr.machowski.dev [at] gmail.com`

**Comment by Tasshack** [comment]
I have the exact same issue with my Z10 Pro. I can provide more information if you need to.

**Comment by SpiGAndromeda** [comment]
I could also provide logs from a Dreame D9. I let it clean one room while watching the app and retrieved the logs. Should I send them via mail? Is there anything to remove from the logs beside the serial number?

The logs contain some undocumented PIIDs. There were no update-map actions and only some map-req actions at the beginning. The mult-map-state was request via get_properties very often. The mult-map-info sometimes (which seems to return an object).

By the way: maybe you could put the link to vevs Mi Home App into a 'Development' section of the Readme. It took me a while to find out how to get logs from the app. (or a pinned issue)

**Comment by PiotrMachowski** [comment]
@SpiGAndromeda sure, you can send them. The problem is that I don't have a Dreame vacuum, so I'm unable to test anything :/

**Comment by SpiGAndromeda** [comment]
I can test if for you. :) We can discuss the communication way via mail if you want.

**Comment by PiotrMachowski** [comment]
@SpiGAndromeda I think that the best way of communication would be HA forum, I can make a group conversation here to add everyone else as well
https://community.home-assistant.io/u/3_14

**Comment by SpiGAndromeda** [comment]
Perfect. My username is the same like here.

**Comment by auanasgheps** [comment]
Allright! My username in HA forum is the same, auanasgheps.

**Comment by Tasshack** [comment]
I fixed the map refresh problem by calling map-req action periodically with an automation while robot is cleaning the house.
I don't know this is the right solution, but it works good for now.

**Comment by Tasshack** [comment]
Gen2 Dreame robots (L10, Z10, W10) works different from the Gen1 like D9. New robots does not send map periodically to the cloud automatically. I have checked the valetudo firmware, found out that you need to send map-req action to trigger the map upload to cloud and that is how currently valetudo gets the map from the device.

https://github.com/Hypfer/Valetudo/blob/84de0ef9d869f5150c504fa13bcd49956c71bf4c/backend/lib/robots/dreame/DreameValetudoRobot.js#L54

I have custom miiot integration installed on my hass and that is how i send the map-req to the device currently.

```
service: xiaomi_miot.call_action
target:
  entity_id: vacuum.dreame.p2028
data:      
  siid: 6
  aiid: 1
  params:
    - piid: 2
      value: '{"frame_type":"I"}'

```

**Comment by PiotrMachowski** [comment]
@auanasgheps hmmm, this was my suggestion when you sent me your logs, but it didn't work for you, right?

**Comment by Tasshack** [comment]
@auanasgheps can you share the logs with me as well to ayigittopcu [at] gmail.com?

**Comment by Tasshack** [comment]
@PiotrMachowski my username in comminity is also same with here, can you add me to the conversation from there too.

**Comment by auanasgheps** [comment]
My query was slightly different:

```
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.battista
  siid: 6
  aiid: 1
  params:
  piid: 2
    value: '{"req_type":1,"frame_type":"I","force_type":1}'
```

I can confirm that the new query by @Tasshack works, the map gets updated just after a second the command is sent!
That's great!

So shall we implement this call (or the template to do so, not all Dreame need it according to Tasshack) every time the maps needs an update?

**Comment by Tasshack** [comment]
By the way i am trying to develop a custom integration (forked from D9 intregration) specific to those GEN2 robots but most of their new features that introduced on latest firmware are not documented at all. Even valetudo does not implemeted some of those features since it is not currently supported on latest firmware. I am struggling to find the specific siid/piid values with their extra parameter information to send to robot. 
For example; app can send cleaning room order to robot to store and when you press start even from the button, robot cleans whole house with that room order, but i couldn't find the aiid/piid values to do it from the integration.
The main problem is most of the developers still does not have one of those new GEN2 robots yet and because of that currenlty there is no information about them on the internet and how they work exactly.
I think we may have to wait a bit longer to fully integrate GEN2 robots to home assistant because it has been more than six months from release of the latest firmware and people still did not exploited the new features on Z10/L10 like only mopping while water tank is attached which is only documented on W10 api specs.

**Comment by PiotrMachowski** [comment]
@auanasgheps it shouldn't be hard for me to add it. Until that you can handle it with a simple automation

**Comment by auanasgheps** [comment]
@Tasshack your effort is incredible, but I am against custom integrations. There have been attempts in the past like this one, which 
quickly become outdated or unmaintained and users get lost.
Why not contribute directly to the MioT integration which is well supported and updated?

**Comment by auanasgheps** [comment]
@webjib the map by default updates every 5 to 10 seconds, so I won't go under 5 seconds to be honest.
What automation have you configured? My trigger does not detect when to start the automation, but I am a newbie with HA automations.

**Comment by webjib** [comment]
I'm using a custom Dreame D9 integration, for which I've created a new service called "vacuum_update_map" (it's derived from https://github.com/pooyashahidi/xiaomi_vacuum). So sharing the entire automation will not help.

But here is the trigger:

```
trigger:
  - platform: template
    value_template: '{{ is_state(''vacuum.aspirobot'', ''cleaning'') or is_state(''vacuum.aspirobot'',
      ''mopping'') or is_state(''vacuum.aspirobot'', ''returning'') }}'
```

**Comment by auanasgheps** [comment]
Thanks! I used the 'status' trigger within the UI, but it didn't work. I will try yours!

**Comment by Tasshack** [comment]
> @Tasshack your effort is incredible, but I am against custom integrations. There have been attempts in the past especially for Dreame robots, but quickly become outdated or unmaintained and users get lost. Why not contribute directly to the MioT integration which is well supported and updated? (BTW I still don't understand why the official Xiaomi integration does not support Dreame robots)

@auanasgheps Xiaomi says Dreame is part of their eco system but they acquired Dreame late after they started to develop robot vacuums. Because of that, not all api features are compatible with the rest of the eco system. Thats why miiot and python-miio are not fully supporting the dreame devices yet. Especially with the lack of documentation you need to do a lot of reverse engineering to support them and to do that you need to own the acual device.
The features that i have implemented to my integration can be achieved with miiot integration also but you have to write a lot of yaml and ninja scripts. I just prefer python, it is cleaner and more optimized.

**Comment by Tasshack** [comment]
> @webjib the map by default updates every 5 to 10 seconds, so I won't go under 5 seconds to be honest. What automation have you configured? My trigger does not detect when to start the automation, but I am a newbie with HA automations.

If you have Z10 or W10, you can check SIID: 15 PIID: 3 (dust-enable attribute) to check robot is docked or not. This attribute returns 1 when auto empting can be triggered from app and it is the only way to determine robot is docked or not when the battery is 100% (Not charging while docked).

**Comment by webjib** [comment]
@Tasshack actually, python-miio is already supporting some Dream Vacuums like the D9 or F9, but not all functions. The best situation would be to contribute first to the python-miio project to support more functions, and more models. Then, as the official HASS Miio integration is using python-miio project, it should be easy to officially support Dreame Vacuums. Lot of work.

**Comment by Tasshack** [comment]
@webjib yes python-miio recently added the Dreame support but the version that shipped with HASS not yet supports it. Also some utilities like mirobo still does not support Dreame yet. 
I think it is a good idea to contribute to python-miio but i am not so good at python to do that. I can provide information about undocumented features that i have gathered from valetudo firmware though.

**Comment by Tasshack** [comment]
@SpiGAndromeda how can i access the app logs, is there a guide that you can share with me?

**Comment by el-fredo** [comment]
I have a Dreame D9 and the map does not update for me either (only when I open the smartphone app). Could someone please explain to me in more detail how you solved the problem?

Do I have to create a script like this:
```
service: xiaomi_miot.call_action
target:
  entity_id: vacuum.xxxxx
data:      
  siid: 6
  aiid: 1
  params:
    - piid: 2
      value: '{"frame_type":"I"}'
```
and afterwards an automation that runs this script?

Thanks for your help.

**Comment by rbforelle** [comment]
@el-fredo I have set up an automation like this and it works to update the map for my Dreame W10
```yaml
alias: map_update
description: ""
trigger:
  - platform: time_pattern
    seconds: /5
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: vacuum.xxx
        state: cleaning
      - condition: state
        entity_id: vacuum.xxx
        state: Washing
      - condition: state
        entity_id: vacuum.xxx
        state: Go Washing
action:
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.xxx
      siid: 6
      aiid: 1
      params:
        - piid: 2
          value: "{\"req_type\":1,\"frame_type\":\"I\",\"force_type\":1}"
mode: single

```

**Comment by auanasgheps** [comment]
@rbforelle Thank you for the automation!
However, the way it's configured means that every 5 seconds HA will check if this automation should be running.
I'm not sure if this is is a best practise, I fear it can overload HA.
![image](https://user-images.githubusercontent.com/20586878/188440910-4daa79fc-b8f0-41e3-81b5-460bb9a06fcb.png)

**Comment by el-fredo** [comment]
Meanwhile I use this script:
```
alias: vacuum_update_map
sequence:
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.dreame_p2009_d3ec_robot_cleaner
      siid: 6
      aiid: 1
      params:
        - piid: 2
          value: "{\"req_type\":1,\"frame_type\":\"I\",\"force_type\":1}"
mode: single
```
If I manually start the script, the map gets updated. So I made following automation:
```
alias: Update Map
trigger:
  - platform: state
    entity_id: vacuum.dreame_d9
    to: cleaning
condition: []
action:
  - repeat:
      while:
        - condition: device
          device_id: f19b35c1ea84676cf97b91d70ab4a187
          domain: vacuum
          entity_id: vacuum.dreame_p2009_d3ec_robot_cleaner
          type: is_cleaning
      sequence:
        - service: script.1659276322175
          data: {}
mode: single
```
First it was a perfect solution, but during the last view weeks it stopped working. Don't know why...

**Comment by el-fredo** [comment]
Meanwhile I use this script:
```
alias: vacuum_update_map
sequence:
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.dreame_p2009_d3ec_robot_cleaner
      siid: 6
      aiid: 1
      params:
        - piid: 2
          value: "{\"req_type\":1,\"frame_type\":\"I\",\"force_type\":1}"
mode: single
```
If I manually start the script, the map gets updated. So I made following automation:
```
alias: Update Map
trigger:
  - platform: state
    entity_id: vacuum.dreame_d9
    to: cleaning
condition: []
action:
  - repeat:
      while:
        - condition: device
          device_id: f19b35c1ea84676cf97b91d70ab4a187
          domain: vacuum
          entity_id: vacuum.dreame_p2009_d3ec_robot_cleaner
          type: is_cleaning
      sequence:
        - service: script.1659276322175
          data: {}
mode: single
```
First it was a perfect solution, but during the last view weeks it stopped working. Don't know why...

**Comment by auanasgheps** [comment]
> Meanwhile I use this script:
> 
> ```
> alias: vacuum_update_map
> sequence:
>   - service: xiaomi_miot.call_action
>     data:
>       entity_id: vacuum.dreame_p2009_d3ec_robot_cleaner
>       siid: 6
>       aiid: 1
>       params:
>         - piid: 2
>           value: "{\"req_type\":1,\"frame_type\":\"I\",\"force_type\":1}"
> mode: single
> ```
> 
> If I manually start the script, the map gets updated. So I made following automation:
> 
> ```
> alias: Update Map
> trigger:
>   - platform: state
>     entity_id: vacuum.dreame_d9
>     to: cleaning
> condition: []
> action:
>   - repeat:
>       while:
>         - condition: device
>           device_id: f19b35c1ea84676cf97b91d70ab4a187
>           domain: vacuum
>           entity_id: vacuum.dreame_p2009_d3ec_robot_cleaner
>           type: is_cleaning
>       sequence:
>         - service: script.1659276322175
>           data: {}
> mode: single
> ```
> 
> First it was a perfect solution, but during the last few weeks it stopped working. Don't know why...

I was about to create a new automation when you posted this, which is what I had in mind. I'll do mine and let you know!

**Comment by PiotrMachowski** [comment]
@el-fredo I think you should add some kind of delay to your script/automation. Your current config sends a new command as soon as previous one has been sent

**Comment by el-fredo** [comment]
Unfortunately, I don't know much about creating scripts/automations manually. Where exactly should the delay be?

Feel free to post your finished code, then I will test it on my end as well.

**Comment by PiotrMachowski** [comment]
I should be enough:
```yaml
alias: Update Map
trigger:
  - platform: state
    entity_id: vacuum.dreame_d9
    to: cleaning
condition: []
action:
  - repeat:
      while:
        - condition: device
          device_id: f19b35c1ea84676cf97b91d70ab4a187
          domain: vacuum
          entity_id: vacuum.dreame_p2009_d3ec_robot_cleaner
          type: is_cleaning
      sequence:
        - service: script.1659276322175
          data: {}
        - delay: 5
mode: single
```

**Comment by el-fredo** [comment]
I understand. This will call the script only every 5 seconds. Will test it when I am back home.

I wanted to avoid HA permanently updating the map, but only when the robot is cleaning. Should be correct with my automation though, or what do you think?

**Comment by auanasgheps** [comment]
> I wanted to avoid HA permanently updating the map

Indeed. When I first created the automation, the end condition was wrong and the automation would never end. Result? After 3 days my HA host would crash because it filled the RAM lol

I am working on something like this. The idea is to trigger the update for every state change, but keep it going only when cleaning/mopping.

I still have to test if works, especially the state values for the "while" condition, which are not standard for each vacuum. I'll let you know later.

```yaml
alias: Vacuum - Map Update
description: ""
trigger:
  - platform: state
    entity_id:
      - vacuum.xxx
action:
  - repeat:
      while:
        - condition: or
          conditions:
            - condition: state
              entity_id: vacuum.xxx
              state: cleaning
            - condition: state
              entity_id: vacuum.xxx
              state: mopping
            - condition: state
              entity_id: vacuum.xxx
              state: returning
      sequence:
        - service: xiaomi_miot.call_action
          data:
            entity_id: vacuum.xxx
            siid: 6
            aiid: 1
            params:
              - piid: 2
                value: "{\"req_type\":1,\"frame_type\":\"I\",\"force_type\":1}"
        - delay:
            hours: 0
            minutes: 0
            seconds: 5
            milliseconds: 0
mode: single
```

**Comment by el-fredo** [comment]
Unfortunately, it still does not work as desired.

So when I start the script manually, the map is updated. And if I manually start the automation once, the map is also updated. But without my manual intervention, the map is not updated.

Therefore, I assume that the problem is with the start of the automation.

I also noticed that the map does not update every 5 seconds, but only every 10 - 15 seconds.

**Comment by rbforelle** [comment]
> @rbforelle Thank you for the automation! However, the way it's configured means that every 5 seconds HA will check if this automation should be running. I'm not sure if this is is a best practise, I fear it can overload HA. ![image](https://user-images.githubusercontent.com/20586878/188440910-4daa79fc-b8f0-41e3-81b5-460bb9a06fcb.png)

I think it just depends on how HA is implemented. Normally something like "trigger by sensor status change" is also implemented by polling. In this case there will be no difference, whether the status is explicitly checked every 5 seconds in automation or checked by HA every x seconds in the background.

This automation runs for 3 days/6 times on my RPI3B+, everything seems great so far. I will report again if there are any problems in the long-term operation

**Comment by auanasgheps** [comment]
> Unfortunately, it still does not work as desired.
> 
> So when I start the script manually, the map is updated. And if I manually start the automation once, the map is also updated. But without my manual intervention, the map is not updated.
> 
> Therefore, I assume that the problem is with the start of the automation.
> 
> I also noticed that the map does not update every 5 seconds, but only every 10 - 15 seconds.

@el-fredo My first test was successful with the automation posted above.
Cleaning was actually triggered by another automation, and the map started throughout the cleaning process.
Surely it does not update every 5 precise seconds, but it doesn't bother me.

I will let you know if the map will update again in the next clean, but I have no reason to believe it will stop.

**Comment by ShadowJonathan** [comment]
I can attest that the "Vacuum - Map Update" has helped my case, unfortunately it still takes more than 5 seconds to update the map each time, but at least it updates every so often now, which is better than i had before.

**Comment by auanasgheps** [comment]
> I can attest that the "Vacuum - Map Update" has helped my case, unfortunately it still takes more than 5 seconds to update the map each time, but at least it updates every so often now, which is better than i had before.

Try reducing the time in the delay section, but I don't think it can get much better than this.

**Comment by Tasshack** [comment]
I am working on a custom integration about three months and i have almost completely reverse engineered the mi home app to do that.
Turns out, newer firmware version vacuums does not upload complete map (I Frame) to cloud while it is moving. Instead, it uploads only changed sections (P Frame) of the map every three seconds. App only requests those frames from the cloud and renders ordered to their frame ids and updates the last map accordingly. 
App never sends request_map to the device when robot is running. Constantly requesting I frames over local api is strictly resticted from app because it has some awkard effects on robot performance and mapping. In my case requesting I frame every 3 seconds with an automation causes dissapearing walls between rooms and more often false positives with the 3d obstacle avoidance. I know this becase when i started parsing only P frames from cloud walls are fixed on my map. 
If robot doesn't know the current map (spot cleaning or fast mapping), it does not responds to force_type = 1 parameter instead request will time out and map will not be refreshed. If there is no saved or current map does not exists, app will always get the data from cloud instead of requesting it from the device. 

I am planning to release my integration at the end of this month and it will solve all map refresh issues for the new version dreame device users. Spoiler; it will have multi-map feature too.

**Comment by PiotrMachowski** [comment]
@Tasshack will it include live map camera?

**Comment by Tasshack** [comment]
> @Tasshack will it include live map camera?

It will have (almost) all features of the app including live map, saved map, auto generated room entities and many more.

![camera](https://user-images.githubusercontent.com/19640547/188971504-b9dd1746-de83-4c5b-958a-9a41ec9f786b.png)

This the map i rendered with the color index and center point finding algorithms directly extracted from the app.

**Comment by PiotrMachowski** [comment]
Will it work just with dreame vacuums or with all models that are supported by Xiaomi Home?

**Comment by Tasshack** [comment]
> Will it work just with dreame vacuums or with all models that are supported by Xiaomi Home?

It will only support Dreame second generation lidar vacuums (L10, Z10, W10, S10 and maybe new S9). Map on Dreame robots with vslam are implemented differently on the app but i didn't implemeted it on my integration because i don't have a vslam robot.
I can only develop for what i have at the moment but in theory my integration sould work with all vacuums that are using the same xiaomi home plugin. 
I just wanted to use your integration and maybe fix it but there are tons of logic involving rendering the map that tied to variety of robots status properties. Because of that i decided to include the map parsing and too on my integration. 
For example; I wanted to disable obstacle avoidance on certain rooms of my house with an automation. Since Dreame does not provide robots current room like on the roborock, i needed to know robots position and room coordinates. For determining robots current room, my integration needs to parse map data anyway even it does not renders the map. So i have added the whole map logic to my integration completely reverse engineered from the app just for 3 seconds refresh rate of robots position.

**Comment by Tasshack** [comment]
I can also render the map with different color pattern, icon set and with room names too.

![camera](https://user-images.githubusercontent.com/19640547/188979781-b223f3ab-cb7f-4a1f-b581-f40c72fa82da.png)

**Comment by PiotrMachowski** [comment]
Actually map extractor can also retrieve current room, it should work with all supported vacuums. 

It looks really nice 👍 

Do you plan to make it compatible with map card?

**Comment by Tasshack** [comment]
> Actually map extractor can also retrieve current room, it should work with all supported vacuums.
> 
> It looks really nice 👍
> 
> Do you plan to make it compatible with map card?

Yes map extractor can do that but refreshing issue with it is preventing to use robots current position.

Currently i am already using your map card for developing my integration and it will be compatible. Rendering map on server side uses too much cpu and takes some time with python (i have added a caching mechanism for each layer for improving the render time). Because of that i have also added the valetudo map support (it has own camera entitiy) but valetudo map card cannot render the cleaning sequence or room icons and uses different color index algorithm. So i will eventually develop javascript renderer that works on client side like the valetudo map card but it will render the same looking map with the backend renderer.

**Comment by PiotrMachowski** [comment]
> Rendering map on server side uses too much cpu and takes some time with python

Yeah, that's why maps generated by Map Extractor usually have a small resolution. Buuuuuut the map itself has quite low resolution as well, so it doesn't change that much (just overlays). Server-side rendering makes it possible to use map image in other places, not just a dedicated card (contrary to *Valetudo map card* approach), but also in notifications, built-in cards and others. There was an attempt to use a faster rendering library (instead of pillow), but right now I don't have time for migration.

**Comment by Tasshack** [comment]
> > Rendering map on server side uses too much cpu and takes some time with python
> 
> Yeah, that's why maps generated by Map Extractor usually have a small resolution. Buuuuuut the map itself has quite low resolution as well, so it doesn't change that much (just overlays). Server-side rendering makes it possible to use map image in other places, not just a dedicated card (contrary to _Valetudo map card_ approach), but also in notifications, built-in cards and others. There was an attempt to use a faster rendering library (instead of pillow), but right now I don't have time for migration.

Yes, actual map and map object can be rendered very small and upscaled easily but i cannot scale down the icons and texts to match the map size. Thats why i decided to render map very large for preventing icons being distorted but that is taking too much processing power now (i am concerned with the rpi users right now). App uses dynamic scaling of these object according to map zoom to solving that issue but if i do that, single icon will cover complete room on my map. I have also checked the other image processing libraries but implementing one of them is too much work and time for me too. Maybe i will render the base map on server-size, icons and texts on the client-side at the end, like you did.

**Comment by auanasgheps** [comment]
@PiotrMachowski can you please tell if the Map Update that is [described here ](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#updates) applies to Dreame vacuums via MiioT integration?

If it does apply, the blueprint should be updated to include the state "idle", used by Dreame via MiooT.
If it does not apply, I'll submit a PR stating that it does not apply.

**Comment by PiotrMachowski** [comment]
@auanasgheps It should apply to all vacuums, but it's not possible for me to know all possible statuses in all integrations.

Keep in mind that purpose of this blueprint is different than handling situation described in this issue.

**Comment by PiotrMachowski** [comment]
@Tasshack great work 👍 You might want to add your integration to [platforms supported by the Vacuum Map card](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/master/CONTRIBUTING.md#adding-new-platform). By the way, the card now can automatically get a list of rooms to clean in `vacuum_clean_segment` template using a button in the editor.

**Comment by PiotrMachowski** [comment]
It actually already uses `room_id` parameter, not index, you can check it out [here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/master/src/xiaomi-vacuum-map-card.ts#L901).

Anyway, let's not hijack this issue, can you create a dedicated discussion [here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/categories/general)? Alternatively you can also enable discussions in your repo

**Comment by auanasgheps** [comment]
@Tasshack by looking at the screenshots I don't like it at all... I love it! Will test it soon.

Will discuss in your repo.

@PiotrMachowski what should we do with this issue? I have implemented the automation which works well. If this can't be added in your integration, shall we document it maybe with a blueprint and call it?

**Comment by auanasgheps** [comment]
@Tasshack I am astonished by the amout of settings available. Definitely great job that deserves the praise!

I am "against" small integrations because they can be abandoned easily and HA evolves so quickly. python-miio is one of those large integrations that will _never_ be abandoned... but I hope yours will get the visibility it deserves! I'm gonna try it very soon.

**Comment by julienlarivee** [comment]
> @auanasgheps i have released my new custom component for Dreame vacuums with map support.
> 
> You should check it out https://github.com/Tasshack/dreame-vacuum/

Will this work with the Dreame D9 (p2009)?

**Comment by codamai** [comment]
> 

is there any way to down grade dreamehome app or bypass regional lock? if so, please help me to do so..

**Comment by lilumaria** [comment]
Also me I have a Dreame x20 pro plus and I cannot find a way to work It. Can you help on some way?

**Comment by lilumaria** [comment]
Thank you for the file but there is a description of the procedure that I need to do to use this program? I'm sorry I'm new to this 😄

**Comment by stehof2** [comment]
> https://github.com/Tasshack/dreame-vacuum/releases/tag/v2.0.0b8

Just for clarification, by installing the beta you should be able to bypass the region lock on a X20 ultra plus?

**Comment by StarterCraft** [comment]
As for me, I have the exact same problem with my `dreame.vacuum.mc1808`. Is there literally no way to make the map live?

**Comment by owlysk** [comment]
Have this issue with `viomi.vacuum.v8`. I am using account with shared home

**Comment by paulo-serrao** [comment]
Hello! is there any way to ask to update the map?

I made the installation of the latest dreame HCAS beta plugin after configuring the robot for the first time. it recognized it and I could see its status, etc. Then I asked the robot to do its initial mapping function. this is what HA shows me as map (entity `camera.dreamebot_l20_ultra_map`) and hasn't updated ever since, this was fetched while that initial map scanning was still ongoing. 

![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/35876077/bbcf3761-97a0-442b-b39f-751971eba0c8)

If I open the device integration page, I can see there is `camera.dreamebot_l20_ultra_map_1` entity with a different map which is a more complete version (but still not the latest I see on the app)

![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/35876077/279debb9-019c-45d0-a494-10f8a0f60e9e)

On the app meanwhile I added separated/merged areas, added, furniture, carpets, etc.

I've already completed a full house clean, but nothing updates on the map. 
Is there a way to force a map update? all the remaining entities seem to work just fine (e.g. battery level updates in real time, etc)

**Comment by Nafania** [comment]
@PiotrMachowski I've tried to read the whole thread but still didn't get it - is there any solution for map updates for dream vacuums (I have l10s pro or dreame.vacuum.r2228o)?

The map from this integration updates from time to time. Can't understand why at all. While from this one https://github.com/Tasshack/dreame-vacuum works in real time.

**Comment by auanasgheps** [comment]
Hi @Nafania 

There's no built in solution as of now.

The fix is to create an automation that does the refresh for you, when the Vacuum is running. It's not elegant, but it works.

Here's mine, you'll have to update the Vacuum Entity ID/Name.

<details>

```yaml
alias: Vacuum - Map Update
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.dreame_p2029_026d_status
condition:
  - condition: or
    conditions:
      - condition: device
        device_id: c58a5e7934bf9ddc56380a6e8e3313dc
        domain: vacuum
        entity_id: vacuum.battista
        type: is_cleaning
action:
  - repeat:
      while:
        - condition: or
          conditions:
            - condition: state
              entity_id: vacuum.battista
              state: cleaning
            - condition: state
              entity_id: vacuum.battista
              state: mopping
            - condition: state
              entity_id: vacuum.battista
              state: returning
      sequence:
        - service: xiaomi_miot.call_action
          data:
            entity_id: vacuum.battista
            siid: 6
            aiid: 1
            params:
              - piid: 2
                value: "{\"req_type\":1,\"frame_type\":\"I\",\"force_type\":1}"
        - delay:
            hours: 0
            minutes: 0
            seconds: 5
            milliseconds: 0
mode: queued
max: 10
```

</details>
