### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by FelixGraf404** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#305]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hey,

my problem: "Failed to login"

I use DuckDNS.

I attached some pics.

Did i an fault somewhere?

Thx Felix

![failedlogin1](https://user-images.githubusercontent.com/105812017/173230811-2907eb3f-d19d-4830-8613-d0b5c3ef8f2c.PNG)

![failedlogin2](https://user-images.githubusercontent.com/105812017/173230910-77869ddb-30b6-46db-90a2-70f8fb949570.PNG)

![failedlogin3](https://user-images.githubusercontent.com/105812017/173230911-7e6b981a-f785-4325-8f2e-e573a7febd38.PNG)

### What version of am integration has described problem?

2.2.0

### What vacuum model do you have problems with?

Roborock s50

### What version of Home Assistant do you use?

 2022.6.4

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_ip
    token: !secret xiaomi_token
    username: !secret mihome_user
    password: !secret mihome_pass
    name: "RobiFred"
    draw: ['all']
    attributes:
      - calibration_points
```
