### ISSUE TITLE
Vector image of the robot is misdrawn

### ISSUE THREAD

**Issue by arjungopisetty** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#306]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hello,

I'm encountering an issue with the new vector drawing of the robot vacuum. There's some missing pixels and the some lines seem to be skewed. Please see the following screenshot taken from my laptop: 

<img width="535" alt="Screen Shot 2022-06-13 at 8 46 52 PM" src="https://user-images.githubusercontent.com/5950166/173489955-63317097-1f57-42df-91d3-a97738e04693.png">

For comparison, I checked against the image in the pull request description for this feature: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/pull/246:
<img src="https://user-images.githubusercontent.com/49229287/153630657-a20e32d4-be73-4b0d-940a-cdd7cfe4ff2e.png">

Please advise, thanks!

### What version of am integration has described problem?

2.2.0

### What vacuum model do you have problems with?

roborock.vacuum.s6maxv

### What version of Home Assistant do you use?

core-2022.4.6

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    attributes:
      - calibration_points
      - charger
      - cleaned_rooms
      - country
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - ignored_obstacles
      - obstacles_with_photo
      - ignored_obstacles_with_photo
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - vacuum_room_name
      - walls
      - zones
```

**Comment by arjungopisetty** [comment]
Sorry, I inputted the wrong config in the PR description. I've updated it to be correct. Thanks!

**Comment by webjib** [comment]
I think you just need to scale the map to something greater than x1. Personally, I've setup a scale of 3 for the map, and a size of 18 for the vacuum. That way, everything will be more detailed.

```
map_transformation:
  scale: 3
sizes:
  vacuum_radius: 18
```
