### ISSUE TITLE
szkj.vacuum.mjfc01

### ISSUE THREAD

**Issue by lasry1** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#308]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

The vacuum szkj.vacuum.mjfc01 is not suported. 

https://es.aliexpress.com/item/1005004320473020.html?spm=a2g0o.productlist.0.0.4fd512ef7FJYSi&algo_pvid=d7958383-3764-43a5-9123-6d72814327c4&algo_exp_id=d7958383-3764-43a5-9123-6d72814327c4-2&pdp_ext_f=%7B%22sku_id%22%3A%2212000028743026238%22%7D&pdp_npi=2%40dis%21GBP%21%21405.9%21%21%21%21%21%402100bdf116554438931216619ec4fa%2112000028743026238%21sea

### What version of am integration has described problem?

v2.2.2

### What was the last working version of an integration?

v2.2.2

### What vacuum model do you have problems with?

szkj.vacuum.mjfc01

### What version of Home Assistant do you use?

2022.6.6

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
- platform: xiaomi_cloud_map_extractor
    host: 192.168.1.104
    token: 7046537a30785636517867527344776b
    username: andres.lasry@me.com
    password: !secret xiaomi_cloud_password
    draw: ['all']
    name: mapapro
    attributes:
      - calibration_points
```
