### ISSUE TITLE
Room / Segment Icons Off + Segment Cleaning Not Working

### ISSUE THREAD

**Issue by UrZdcw9** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#312]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hi there,

Im having some strange results integrating my second roborock s7.  the first one works fine with no issues.

the second one however has two issues - i cant tell if they are related...

1) Icon for Rooms off.  

I've rotated the map via map_transformation, but still the little broom icons are off.  Any ideas?

![image](https://user-images.githubusercontent.com/92231563/175765556-b18a4f8e-d282-45f7-bef6-c95e3d301edc.png)

2) Segment cleaning (when initiated via home assistant and a lovelace card fails.  it initiates but then returns to dock after about 5 seconds.

I have done a factory reset and remapped the floor a couple of times now to know avail.  

Interestingly after i initiate segment clean via lovelace, the map rendering fails for a few moments..  then the vac returns to its doc...

Any advice?

### What version of am integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

roborock.vacuum.a15

### What version of Home Assistant do you use?

core-2022.6.7

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
- platform: xiaomi_cloud_map_extractor
    name: Roxy
    host: 
    token:
    username: 
    password: 
    country: sg
    draw: ['all']
    map_transformation:
      rotate: 270
    sizes:
      charger_radius: 4
      vacuum_radius: 6.5
      obstacle_radius: 3
      ignored_obstacle_radius: 3
      obstacle_with_photo_radius: 3
      ignored_obstacle_with_photo_radius: 3
    attributes:
      - calibration_points
      - rooms
    scan_interval:
      seconds: 5
    auto_update: true
    store_map_raw: true
    store_map_image: true
    store_map_path: "/tmp"
    force_api: xiaomi
```

### Errors shown in the HA logs (if applicable)

```shell
Im getting these 

Logger: miio.miioprotocol
Source: /usr/local/lib/python3.9/site-packages/miio/miioprotocol.py:240
First occurred: 18:25:41 (18 occurrences)
Last logged: 18:33:52

Got error when receiving: timed out

and these

Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:356
Integration: xiaomi_cloud_map_extractor ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues))
First occurred: 18:28:21 (2 occurrences)
Last logged: 18:33:21

Unable to retrieve map data
```
