### ISSUE TITLE
Image has not been saved

### ISSUE THREAD

**Issue by Fillll** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#317]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

roborock.vacuum.s5

### What is its name?

Roborock S50

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

### Other info

Looks like it has successfully retrieved the map, and the map is available at `http://homeassistant:8123/api/camera_proxy_stream/camera.my_vacuum_camera?token=%TOKEN%`.

But it does not save the map in **png** image in `/tmp/` folder.

Here is the config:
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: "us"
    name: "My Vacuum Camera"
    store_map_image: true
    store_map_path: "/tmp"
    draw: ["all"]
    attributes:
      - calibration_points
    scan_interval:
      seconds: 30
    auto_update: true
```

To check, if it at least tries to save, I've added to `camera.py`, several debug prints.
```python
...
    def _store_image(self):
        if self._store_map_image:
            try:
                image = Image.open(io.BytesIO(self._image))
                _LOGGER.warning(f'FILE: {self._store_map_path}/map_image_{self._device.model}.png')
                image.save(f"{self._store_map_path}/map_image_{self._device.model}.png")
                _LOGGER.warning('File saved.')
            except:
                _LOGGER.warning("Error while saving image")
...
```

Here is what I see in the log:
```log
2022-07-10 15:17:22 WARNING (SyncWorker_2) [custom_components.xiaomi_cloud_map_extractor.camera] FILE: /tmp/map_image_roborock.vacuum.s5.png
2022-07-10 15:17:23 WARNING (SyncWorker_2) [custom_components.xiaomi_cloud_map_extractor.camera] File saved.
```

But the is nothing in `/tmp`. Appreciate your guidance!
