### ISSUE TITLE
two factor auth required (see logs)

### ISSUE THREAD

**Issue by steuerzentrale** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#319]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hi there

I use Home Assistant 2022.7.3, Supervisor 2022.07.0, Operating System 8.2 Frontend 20220707.0 - latest. Since yesterday I get the message to login to my Xiaomi-account and confirm the 2FA-authentication. I did that and the it confirmed it via an OK.

After that I restarted Home Assistant and still face the issue. I retried the 2FA-authentication again and always restarted the HA but nothing changes.

<img width="1315" alt="Bildschirmfoto 2022-07-12 um 20 15 30" src="https://user-images.githubusercontent.com/75168550/178565439-789a2417-6790-4dfc-9483-3616c5373f6f.png">
 

### What version of am integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

roborock_a15

### What version of Home Assistant do you use?

2022.7.3

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.5
    token: XXX
    username: !secret mihome_user
    password: !secret mihome_pass
    draw: ['all']
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
Logger: custom_components.xiaomi_cloud_map_extractor.common.xiaomi_cloud_connector
Source: custom_components/xiaomi_cloud_map_extractor/common/xiaomi_cloud_connector.py:89
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 15:25:16 (1 occurrences)
Last logged: 15:25:16
Additional authentication required. Open following URL using device that has the same public IP, as your Home Assistant instance: https://account.xiaomi.com/identity/authStart?sid=passport&context=XXXX
```
