### ISSUE TITLE
2 robots 

### ISSUE THREAD

**Issue by kiki3529-0** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#321]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hi

Is it possible to configure 2 Xiaomi vaccums ? And creat 2 maps for each?
How configure configuration.yaml
I have one on first floor and another at the second floor 

(It works good for the first)
Good bye
Mickaël ( France)

### What version of am integration has described problem?

V0.00

### What was the last working version of an integration?

V0.00

### What vacuum model do you have problems with?

Robot rock v1

### What version of Home Assistant do you use?

00

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 195.778.66.78
    token: 7898789789870778
    username: kiki
    password: hkjhuujjklh
    draw: ['all']
    attributes:
      - calibration_points
```

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/discussions/108

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 195.778.66.78
    name: vacuum1
    token: 7898789789870778
    username: kiki
    password: hkjhuujjklh
    draw: ['all']
    attributes:
      - calibration_points
  - platform: xiaomi_cloud_map_extractor
    host: 195.778.66.79
    name: vacuum2
    token: 7898789789870779
    username: kiki
    password: hkjhuujjklh
    draw: ['all']
    attributes:
      - calibration_points
```
