### ISSUE TITLE
Map not loading after update to Home Assistant 2022.8.1

### ISSUE THREAD

**Issue by eriklysoe** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#323]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Invalid entities:
camera.xiaomi_cloud_map_extractor

Camera is completely missing from the enteties, not deactivated or hidden. It was working in 2022.8.0, but I tried to go back to this version, with no luck.

### What version of am integration has described problem?

v2.2

### What vacuum model do you have problems with?

roborock s5

### What version of Home Assistant do you use?

2022.8.1 and 2022.8.0

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.170.8
    token: xxxx
    username: email
    password: xxxxx
    draw: ["all"]
    attributes:
      - calibration_points
      - rooms
```
