### ISSUE TITLE
IMILAB V1

### ISSUE THREAD

**Issue by arsenal3008** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#326]
### Checklist

- [x] I have updated the integration to the latest version available
- [X] I have checked if the vacuum/platform is already requested
- [ ] I have sent raw map file to `piotr.machowski.dev [at] gmail.com` ([Retrieving map](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#retrieving-map); please provide your GitHub username in the email)

### What vacuum model do you want to be supported?

IMILAB V1

### What is its name?

chuangmi.vacuum.hmi707

### Available APIs

- [ ] xiaomi
- [ ] viomi
- [ ] roidmi
- [ ] dreame

**Comment by PiotrMachowski** [comment]
You have to send me raw map file to make anything possible.
Add following lines to config of Map Extractor:
```yaml
store_map_raw: true
store_map_path: /config
```
After restart there should be a raw map file created in `/config` directory

**Comment by arsenal3008** [comment]
![2](https://user-images.githubusercontent.com/6509294/183749728-05f053de-2841-4ef0-8162-4cdd9649bbe4.png)
this is?

**Comment by PiotrMachowski** [comment]
Yup. You should get map file with extension `.unknown`

**Comment by arsenal3008** [comment]
there is nothing

**Comment by arsenal3008** [comment]
![3](https://user-images.githubusercontent.com/6509294/183753622-792886c4-2593-47d5-a5e5-dff97bf1c6b9.png)

**Comment by PiotrMachowski** [comment]
In this case there should be something in logs

**Comment by arsenal3008** [comment]
what log to give you?
home-assistant.log
home-assistant.log.1

**Comment by PiotrMachowski** [comment]
First one

**Comment by arsenal3008** [comment]
[home-assistant.log](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/files/9294379/home-assistant.log)

**Comment by arsenal3008** [comment]
[home-assistant.log.1.log](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/files/9294404/home-assistant.log.1.log)

**Comment by PiotrMachowski** [comment]
Try this config:
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
    store_map_raw: true
    store_map_path: /config
    force_api: roidmi
```
and check if a file appeared

**Comment by PiotrMachowski** [comment]
Also I think that you might have provided an invalid token. Can you confirm it is the same as one retrieved by [Tokens Extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/)?

**Comment by arsenal3008** [comment]
incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 43, column 5:
        : ['all']
        ^
![4](https://user-images.githubusercontent.com/6509294/183816751-89ccd37b-e026-4e2d-97e8-daf58a9e9adb.png)

**Comment by arsenal3008** [comment]
everything turned out you were right the token is not the same
[map_data_chuangmi.vacuum.hmi707.zip](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/files/9297076/map_data_chuangmi.vacuum.hmi707.zip)

**Comment by arsenal3008** [comment]
map_data_chuangmi.vacuum.hmi707.gz file appeared
[map_data_chuangmi.vacuum.hmi707.gz](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/files/9297724/map_data_chuangmi.vacuum.hmi707.gz)
![11](https://user-images.githubusercontent.com/6509294/183839942-c57373ea-acaa-45af-abec-5d3f362cc4f8.png)

**Comment by arsenal3008** [comment]
![11](https://user-images.githubusercontent.com/6509294/183840284-94b0e075-9730-4449-a48c-edb6a41fa038.png)

**Comment by arsenal3008** [comment]
there are more files
![333](https://user-images.githubusercontent.com/6509294/183850602-3c6319d6-0bcc-430d-a238-a02ee7cf4f7e.png)

**Comment by PiotrMachowski** [comment]
I see that the map appeared. Was it after you used `force_api: roidmi` in your config?

**Comment by arsenal3008** [comment]
yes

**Comment by PiotrMachowski** [comment]
Ok, I will add it to supported vacuums. 

> ![22](https://user-images.githubusercontent.com/6509294/183849862-0e82ad65-b7f0-4670-85b2-040e08b3db44.png)

This is a problem with your config of map card. What integration do you use to add vacuum to HA?

**Comment by arsenal3008** [comment]
token which is in mi home properties
or insert which Tokens Extractor?

**Comment by PiotrMachowski** [comment]
Nooo, not `camera`. How have you added your vacuum to HA? (not its map)

**Comment by arsenal3008** [comment]
Xiaomi MIoT

**Comment by PiotrMachowski** [comment]
I thought so... 
This integration is problematic to use with map card, you have to configure it manually by yourself.
Discussion: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/251
Example configs: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/406

**Comment by arsenal3008** [comment]
which file should be edited?

**Comment by PiotrMachowski** [comment]
It is in yaml config of Xiaomi Vacuum Map Card. Map Extractor part is done.

**Comment by arsenal3008** [comment]
![334](https://user-images.githubusercontent.com/6509294/183874144-a400f8a1-29ab-4923-bfad-c5c612e0cf68.png)

**Comment by PiotrMachowski** [comment]
No, this is a code of the card itself. You have to go to your dashboard, click open edit mode, edit map card and open YAML editor

**Comment by arsenal3008** [comment]
![324](https://user-images.githubusercontent.com/6509294/183875751-311d86dd-89bc-4fb7-b958-597717568551.png)

**Comment by PiotrMachowski** [comment]
Yup

**Comment by arsenal3008** [comment]
I'm afraid to spoil what I need to write?

**Comment by PiotrMachowski** [comment]
You won't break anything by editing this config. Unfortunately this is the part you need to do by yourself. Your config should look more or less like this:

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.xiaomi_vacuum
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
- template: vacuum_clean_segment
  max_selections: 1
  repeats_type: EXTERNAL
  max_repeats: 5
  service_call_schema:
    service: xiaomi_miot.call_action
    service_data:
      entity_id: '[[entity_id]]'
      siid: 2
      aiid: 6
      params:
        - piid: 9
          value: '[[[[selection_unwrapped]]]'
      force_params: true
  predefined_selections:
    # HERE YOU HAVE TO PROVIDE ROOMS
  
```

Getting rooms: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/317

**Comment by arsenal3008** [comment]
entity_id: '[[entity_id]]'                                              ?
        siid: 2                                                                ?
        aiid: 6                                                               ?
        params:
          - piid: 9                                                          ?
            value: '[[[[selection_unwrapped]]]'              ?
what to write here?

**Comment by PiotrMachowski** [comment]
nothing (I have updated it, there were mismatched brackets).
Documentation: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card#supported-templates

Please bear in mind that config I have pasted above is just a wild guess, I can't validate if it will work with your vacuum

**Comment by arsenal3008** [comment]
sorry, I'm not a programmer and I can't figure it out without the help of the one who wrote the code

**Comment by PiotrMachowski** [comment]
Ok, you can try to call `xiaomi_miot.call_action` with appropriate data using dev tools: [![Open your Home Assistant instance and show your service developer tools with a specific service selected.](https://my.home-assistant.io/badges/developer_call_service.svg)](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.call_action)

You can start with following config:
```yaml
    service: xiaomi_miot.call_action
    service_data:
      entity_id: vacum.hmi707_cloud_787133
      siid: 2
      aiid: 6
      params:
        - piid: 9
          value: '[1, 11, 14, 16]' # here you can provide IDs of your rooms
      force_params: true
```

When you succeed you can send service call data here and I will help with card setup.

**Comment by arsenal3008** [comment]
Failed to call service xiaomi_miot.call_action. Unable to find service xiaomi_miot.call_action

**Comment by PiotrMachowski** [comment]
Which integration do you use?
https://github.com/al-one/hass-xiaomi-miot
or
https://github.com/ha0y/xiaomi_miot_raw

**Comment by PiotrMachowski** [comment]
In this case there seems to be something wrong with your setup. You can create a discussion there

**Comment by PiotrMachowski** [comment]
Try this one:
```yaml
    service: xiaomi_miot.call_action
    data:
      entity_id: vacum.hmi707_cloud_787133
      siid: 2
      aiid: 6
      params:
        - piid: 9
          value: '[1, 11, 14, 16]' # here you can provide IDs of your rooms
      force_params: true
```

**Comment by arsenal3008** [comment]
I don't understand the syntax, but somewhere is an error
![4335](https://user-images.githubusercontent.com/6509294/183914811-ccc44d9b-5632-484a-915c-5328e48703bf.png)

**Comment by PiotrMachowski** [comment]
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacum.hmi707_cloud_787133
  siid: 2
  aiid: 6
  params:
    - piid: 9
      value: '[1, 11, 14, 16]'
  force_params: true
```

**Comment by arsenal3008** [comment]
service: xiaomi_miot.call_action
data:
  entity_id: vacu**### u**m.hmi707_cloud_787133
  siid: 2
  aiid: 6
  params:
    - piid: 9
      value: '[1, 11, 14, 16]'
  force_params: true
ok

**Comment by arsenal3008** [comment]
![6522](https://user-images.githubusercontent.com/6509294/183917008-b42d6a9b-1a10-4198-b493-cdb18570a988.png)

**Comment by arsenal3008** [comment]
![46558](https://user-images.githubusercontent.com/6509294/183917508-02c4c6d2-75e8-4737-9c10-99319db2b133.png)

**Comment by arsenal3008** [comment]
Failed to call service vacuum/send_command

**Comment by PiotrMachowski** [comment]
> Failed to call service vacuum/send_command

It won't work. You have to use `xiaomi_miot.call_action`

**Comment by arsenal3008** [comment]
I don't know where to write this

**Comment by arsenal3008** [comment]
Can you advise tomorrow afternoon?

**Comment by PiotrMachowski** [comment]
> ![6522](https://user-images.githubusercontent.com/6509294/183917008-b42d6a9b-1a10-4198-b493-cdb18570a988.png)

You already did it here. You should be able to get some help in https://github.com/al-one/hass-xiaomi-miot repository

**Comment by PiotrMachowski** [comment]
> Good evening, I found some codes for imilab v1
> https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:chuangmi-hmi707:1
> https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:chuangmi-hmi707:2
> https://home.miot-spec.com/s/chuangmi.vacuum.hmi707
> what are they for?

I don't know, you have to ask a question in a repo that links to this documentation (Xiaomi Miot Auto/Xiaomi Miot Raw)

> through which program is it better to install vacuum robot so that Xiaomi Cloud Vacuum Map Extractor works
> Xiaomi Miot Auto?
> Xiaomi MioT?
> or something else?

It already works with Map Extractor (you have a live map), additionally for Map Extractor it doesn't matter which integration you use. It is important for Map Card.
It works with some vacuums using https://github.com/al-one/hass-xiaomi-miot, I haven't seen a config for https://github.com/ha0y/xiaomi_miot_raw

**Comment by arsenal3008** [comment]
good evening, I can be a little arrogant and ask you to make a xiaomi-vacuum-map-card for me based on my data?

**Comment by arsenal3008** [comment]
у меня получилось сделать Xiaomi Cloud Map Extractor
![2022-08-24_22-05-25](https://user-images.githubusercontent.com/6509294/186502536-3fe4f65d-a9dc-4588-9945-ec8e19eab046.png)

**Comment by PiotrMachowski** [comment]
I have added a comment with clarification in your issue in Xiaomi Miot repo: https://github.com/al-one/hass-xiaomi-miot/issues/738#issuecomment-1226152933

**Comment by al-one** [comment]
@arsenal3008  Entity `vacuum.hmi707_cloud_787133` is not generated by component `Xiaomi Miot Auto` and cannot use service `xiaomi_miot.call_action`.

**Comment by arsenal3008** [comment]
need to install Xiaomi MIoT for Home Assistant?
[https://github.com/ha0y/xiaomi_miot_raw](url)

**Comment by arsenal3008** [comment]
![well](https://user-images.githubusercontent.com/6509294/186644400-2cb26035-183c-4884-8ea9-fa66b7515a8a.png)

**Comment by arsenal3008** [comment]
I'll be home in the evening and send you a file from mi home

**Comment by arsenal3008** [comment]
![ok](https://user-images.githubusercontent.com/6509294/186649077-8a568255-a781-409d-add0-82cae8274f90.png)

**Comment by arsenal3008** [comment]
Good evening, if you are still ready to help me, I post the data:
[log_vevs.txt](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/files/9426638/log_vevs.txt)
[my configuration.yaml.txt](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/files/9426640/my.configuration.yaml.txt)

**Comment by al-one** [comment]
@arsenal3008 Only the global cleaning action is found in the log. Please clean each room, perform zone cleaning, spot cleaning and other clean actions, and then obtain the log file again.

**Comment by arsenal3008** [comment]
good morning did:
[448787133.txt](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/files/9450307/448787133.txt)

**Comment by al-one** [comment]
```
2022-08-30 09:07:56 -> {"params":{"did":"448787133","siid":14,"aiid":1,"in":[2,"{\"mapId\":1661655224,\"segmentId\":[1]}"]}} /miotspec/action
2022-08-30 09:07:56 <- {"code":0,"message":"","result":{"did":"448787133","miid":0,"siid":14,"aiid":1,"code":0,"exe_time":0,"withLatency":0}}
2022-08-30 09:14:06 -> {"params":{"did":"448787133","siid":14,"aiid":1,"in":[2,"{\"mapId\":1661655224,\"segmentId\":[2]}"]}} /miotspec/action
2022-08-30 09:14:06 <- {"code":0,"message":"","result":{"did":"448787133","miid":0,"siid":14,"aiid":1,"code":0,"exe_time":0,"withLatency":0}}
2022-08-30 09:18:53 -> {"params":{"did":"448787133","siid":14,"aiid":1,"in":[2,"{\"mapId\":1661655224,\"segmentId\":[3]}"]}} /miotspec/action
2022-08-30 09:18:53 <- {"code":0,"message":"","result":{"did":"448787133","miid":0,"siid":14,"aiid":1,"code":0,"exe_time":0,"withLatency":0}}
```

```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.chuangmi_hmi707_9f51_robot_cleaner_2
  siid: 14
  aiid: 1
  params:
    - 2
    - '{"mapId":1661655224,"segmentId":[1]}'
```

**Comment by PiotrMachowski** [comment]
@al-one is "mapId" param required?

**Comment by arsenal3008** [comment]
![2022-08-30_15-32-12](https://user-images.githubusercontent.com/6509294/187437741-cfdfd4d3-6c75-453d-9583-6cb32f99c759.png)

**Comment by PiotrMachowski** [comment]
@arsenal3008 you have used invalid service and misformatted YAML.

1. Open this link: [![Open your Home Assistant instance and show your service developer tools with a specific service selected.](https://my.home-assistant.io/badges/developer_call_service.svg)](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.call_action)

2. Change to YAML mode

3. Copy and paste code from [this comment](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/326#issuecomment-1231400130). Indentations are important

**Comment by arsenal3008** [comment]
![Uploading 1.png…]()
![Uploading 2.png…]()
![Uploading 3.png…]()

**Comment by PiotrMachowski** [comment]
> ![1](https://user-images.githubusercontent.com/6509294/187445693-2a91ba50-c348-4b11-8489-799bf33429e7.png)

yes

> ![2](https://user-images.githubusercontent.com/6509294/187445717-32578c2b-ede9-4c0b-994e-2e9d66071444.png) 

the same

> ![3](https://user-images.githubusercontent.com/6509294/187445741-8be569cd-4e88-4ada-9716-c6893fcb2afb.png)

no

**Comment by arsenal3008** [comment]
The app I'm using (Xiaomi Miot Auto) is missing the vacuum_clean_zone setting, could this be a hindrance?

**Comment by PiotrMachowski** [comment]
> The app I'm using (Xiaomi Miot Auto) is missing the vacuum_clean_zone setting, could this be a hindrance?

Is it available in Xiaomi Home app on your phone?



> ![2](https://user-images.githubusercontent.com/6509294/187445717-32578c2b-ede9-4c0b-994e-2e9d66071444.png)

does this config work?

**Comment by arsenal3008** [comment]
if it's not difficult for you, can you go to AnyDesk and see what needs to be done?
634307456

**Comment by PiotrMachowski** [comment]
> if it's not difficult for you, can you go to AnyDesk and see what needs to be done? 634307456

It wouldn't help much. A response to these question would though

> > The app I'm using (Xiaomi Miot Auto) is missing the vacuum_clean_zone setting, could this be a hindrance?
> 
> Is it available in Xiaomi Home app on your phone?
> 
> > ![2](https://user-images.githubusercontent.com/6509294/187445717-32578c2b-ede9-4c0b-994e-2e9d66071444.png)
> 
> does this config work?

**Comment by PiotrMachowski** [comment]
It should start room cleaning

**Comment by arsenal3008** [comment]
> It should start room cleaning

no

**Comment by PiotrMachowski** [comment]
Does it do anything?

**Comment by arsenal3008** [comment]
Yes, I changed it to vacuum.chuangmi_hmi707_9f51_robot_cleaner

**Comment by arsenal3008** [comment]
clean zone 1

**Comment by PiotrMachowski** [comment]
Paste this in "Template" section in "Developer Tools"
    [![Open your Home Assistant instance and show your template developer tools.](https://my.home-assistant.io/badges/developer_template.svg)](https://my.home-assistant.io/redirect/developer_template/) and show the output 

```yaml
{# ----------------- PROVIDE YOUR OWN ENTITY IDS HERE ----------------- #}
{% set camera_entity = "camera.xiaomi_cloud_map_extractor" %}
{% set vacuum_entity = "vacuum.chuangmi_hmi707_9f51_robot_cleaner" %}
{# ------------------- DO NOT CHANGE ANYTHING BELOW ------------------- #}
{% set attributes = states[camera_entity].attributes %}
type: custom:xiaomi-vacuum-map-card
entity: {{ vacuum_entity }}
map_source:
  camera: {{ camera_entity }}
calibration_source:
  camera: true
map_modes:
  - template: vacuum_goto
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    predefined_selections:
{%- for room_id in attributes.rooms | default([]) %}
{%- set room = attributes.rooms[room_id] %}
{%- set keep_float = "." in (room["x0"] | string) %}
{%- set x = ([room["x0"], room["x1"]] | sum / 2) if keep_float else (([room["x0"], room["x1"]] | sum / 2) | int) %}
{%- set y = ([room["y0"], room["y1"]] | sum / 2) if keep_float else (([room["y0"], room["y1"]] | sum / 2) | int) %}
      - id: {{room_id}}
        label:
          text: Room {{ room_id }}
          x: {{ x }}
          y: {{ y }}
          offset_y: 35
        icon:
          name: "mdi:broom"
          x: {{ x }}
          y: {{ y }}
{%- endfor %}
```

**Comment by arsenal3008** [comment]
send_command?

**Comment by PiotrMachowski** [comment]
don't do anything in card, just evaluate the template that I have provided

**Comment by arsenal3008** [comment]
servce not found

**Comment by PiotrMachowski** [comment]
Not there. Here: [Dev tools - templatr](https://my.home-assistant.io/redirect/developer_template/)

**Comment by arsenal3008** [comment]
does not open
![Uploading 6.png…]()

**Comment by PiotrMachowski** [comment]
ok, in this case you can go to `<hass_url>/developer-tools/template` manually. (Developer Tools -> Template)

**Comment by arsenal3008** [comment]
ok zone cleans

**Comment by PiotrMachowski** [comment]
ok, so are we done here?

**Comment by arsenal3008** [comment]
> ok, so are we done here?
: ) are you already tired? still wanted points

**Comment by PiotrMachowski** [comment]
To make anything else possible you have to provide appropriate logs

**Comment by alexbilevskiy** [comment]
Reviving this thread!
Template for zone cleaning from comment above works fine https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/326#issuecomment-1231793743

> To make anything else possible you have to provide appropriate logs from Xiaomi Home app

Service calls for point and area are almost identical:
area:
```
2022-12-27 23:05:50 -> {"params":{"did":"448786707","siid":14,"aiid":1,"in":[2,"{\"MapId\":1668351201,\"ExtraAreas\":[{\"name\":\"划区\",\"id\":300,\"tag\":\"4\",\"vertexs\":[[-2492,-6458],[-1058,-6458],[-1058,-7525],[-2492,-7525]],\"active\":\"normal\",\"mode\":\"area\"}]}"]}} /miotspec/action
```
point:
```
2022-12-26 00:08:30 -> {"params":{"did":"448786707","siid":14,"aiid":1,"in":[4,"{\"MapId\":1668351201,\"ExtraAreas\":{\"name\":\"定点\",\"id\":301,\"tag\":\"5\",\"vertexs\":[[-1315,-3282],[685,-3282],[685,-5282],[-1315,-5282]],\"active\":\"normal\",\"mode\":\"point\"}}"]}} /miotspec/action
```

Here is my configuration for _point-as-zone_
```yaml
map_modes:
  - name: Zone
    icon: mdi:select-drag
    selection_type: MANUAL_RECTANGLE
    variables:
      map_id: 1668351201
    max_selections: 1
    repeats: NONE
    max_repeats: 5
    service_call_schema:
      evaluate_data_as_template: true
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 14
        aiid: 1
        params:
          - 4
          - >-
            {"MapId":[[map_id]],
            "ExtraAreas":{"name":"定点","id":301,"tag":"5","vertexs":[
            [{{[[selection]][0][0]}},{{[[selection]][0][3]}}],
            [{{[[selection]][0][2]}},{{[[selection]][0][3]}}],
            [{{[[selection]][0][2]}},{{[[selection]][0][1]}}],
            [{{[[selection]][0][0]}},{{[[selection]][0][1]}}]
            ],"active":"normal","mode":"point"}}
```

Probably stucture of `vertexs` would be a bit different if there are multiple areas selected, but i don't need that.


I only have couple of questions:
- Hardcoded map_id is frustrating. Maybe it is available in camera entity?
- Is there nicer way to build array of coordinate pairs? `[[selection_unwrapped]]` doesn't fit
- Is it possible to dynamically build rooms list for zones mode?
