### ISSUE TITLE
Configuration failed

### ISSUE THREAD

**Issue by grossmanns** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#33]
Hi, I have the following error in my log.
```
2020-10-26 10:15:16 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.my_robocop fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 471, in async_device_update
    await self.hass.async_add_executor_job(self.update)  # type: ignore
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 187, in update
    map_data = self._connector.get_map(map_name, self._colors, self._drawables, self._texts, self._sizes,
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 105, in get_map
    map_data = MapDataParser.parse(unzipped, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/map_data_parser.py", line 81, in parse
    ImageHandler.draw_texts(map_data.image, texts)
  File "/config/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 189, in draw_texts
    ImageHandler.__draw_text__(image, text_config[CONF_TEXT], x, y, text_config[CONF_COLOR],
  File "/config/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 235, in __draw_text__
    ImageHandler.__draw_on_new_layer__(image, draw_func)
  File "/config/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 249, in __draw_on_new_layer__
    draw_function(draw)
  File "/config/custom_components/xiaomi_cloud_map_extractor/image_handler.py", line 231, in draw_func
    font = ImageFont.truetype(font_file, font_size)
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 655, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 652, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 169, in __init__
    if core.HAVE_RAQM:
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 43, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed
```

I took 'de' country, because 'fr' is not available. 

Here is my configuration :
```
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.x.x
    token: 4xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    username: xxxxxxxxxx.xxxxxxxxxxxxx@gmail.com
    password: xxxxxxxxxxxxx
    country: de
    name: My Robocop
    colors:
      color_map_inside: [32, 115, 185]
      color_map_outside: [19, 87, 148]
      color_map_wall: [100, 196, 254]
      color_map_wall_v2: [93, 109, 126]
      color_grey_wall: [93, 109, 126]
      color_path: [147, 194, 238]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [75, 235, 149]
      color_unknown: [0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
    room_colors:
      1: [240, 178, 122]
      2: [133, 193, 233]
      3: [217, 136, 128]
      4: [52, 152, 219]
      5: [205, 97, 85]
      6: [243, 156, 18]
      7: [88, 214, 141]
      8: [245, 176, 65]
      9: [252, 212, 81]
      10: [72, 201, 176]
      11: [84, 153, 199]
      12: [133, 193, 233]
      13: [245, 176, 65]
      14: [82, 190, 128]
      15: [72, 201, 176]
      16: [165, 105, 18]
    draw:
      - charger
      - path
      - goto_path
      - predicted_path
      - no_go_zones
      - no_mopping_zones
      - vacuum_position
      - virtual_walls
      - zones
    texts:
      - text: "Room 1"
        x: 25
        y: 25
        color: [125, 20, 213]
      - text: "Room 2"
        x: 25
        y: 75
        color: [125, 20, 213, 127]
        font: "FreeSans.ttf"
        font_size: 25
    map_transformation:
      scale: 2
      rotate: 180
      trim:
        top: 10
        bottom: 20
        left: 30
        right: 40
    sizes:
      charger_radius: 4
      vacuum_radius: 6.5
    attributes:
      - calibration_points
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - walls
      - zones
    scan_interval:
      seconds: 10
    auto_update: true
```

**Comment by PiotrMachowski** [comment]
Just remove font: from texts section.

Duplicate of #20

**Comment by grossmanns** [comment]
Still this error now : 
`2020-10-26 10:30:02 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2795040456] 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 138, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1335, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1370, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 470, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 655, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 507, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 424, in async_turn_off
    await self.hass.async_add_executor_job(self.turn_off)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 420, in turn_off
    raise NotImplementedError()
NotImplementedError`
![vac1](https://user-images.githubusercontent.com/62830240/97156232-b9758a80-1776-11eb-838d-cc1182c914dc.png)

**Comment by PiotrMachowski** [comment]
It seems like you have called service `camera.turn_off`, which is not implemented in this integration.

**Comment by grossmanns** [comment]
I took it away : 
no map displayed. Is 'de' country the right one for me, in France ?
`2020-10-26 10:42:59 WARNING (SyncWorker_41) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map data`

**Comment by PiotrMachowski** [comment]
It's a country of a server. If you use European server you should use `de`, if you use Chinese server you should use `cn`. You can check which one you should use with [this](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor) tool.

**Comment by grossmanns** [comment]
great tool , 'de' is the right one, it found my two vacuums :
![vac2](https://user-images.githubusercontent.com/62830240/97158792-36eeca00-177a-11eb-8e97-7e30889e96d0.png)

An image is loaded when i configure a card like that : 
`type: picture-entity
entity: camera.xiaomi_cloud_map_extractor
tap_action:
  action: none
hold_action:
  action: none`

But when i configure your custom card like following, I see nothing : 
![vac3](https://user-images.githubusercontent.com/62830240/97162650-c6e34280-177f-11eb-96c7-b723e7f81008.png)

`type: 'custom:xiaomi-vacuum-map-card'
entity: vacuum.robocop
map_image: /local/custom_lovelace/xiaomi_vacuum_map_card/map.png
calibration_points:
  - vacuum:
      x: 25500
      'y': 25500
    map:
      x: 466
      'y': 1889
  - vacuum:
      x: 26500
      'y': 26500
    map:
      x: 730
      'y': 1625
  - vacuum:
      x: 25500
      'y': 26500
    map:
      x: 466
      'y': 1625
zones:
  - - - 25500
      - 25500
      - 26500
      - 26500
  - - - 24215
      - 28125
      - 29465
      - 32175
  - - - 24245
      - 25190
      - 27495
      - 27940
    - - 27492
      - 26789
      - 28942
      - 27889
  - - - 28972
      - 26715
      - 31072
      - 27915
    - - 29457
      - 27903
      - 31107
      - 29203
    - - 30198
      - 29215
      - 31498
      - 31215
    - - 29461
      - 31228
      - 31511
      - 32478
`
How to create the map file in /local/custom_lovelace/xiaomi_vacuum_map_card/map.png ?

**Comment by PiotrMachowski** [comment]
Use this configuration:
```
type: 'custom:xiaomi-vacuum-map-card'
entity: vacuum.robocop
map_camera: camera.xiaomi_cloud_map_extractor
camera_calibration: true
zones:
  - - - 25500
      - 25500
      - 26500
      - 26500
  - - - 24215
      - 28125
      - 29465
      - 32175
  - - - 24245
      - 25190
      - 27495
      - 27940
    - - 27492
      - 26789
      - 28942
      - 27889
  - - - 28972
      - 26715
      - 31072
      - 27915
    - - 29457
      - 27903
      - 31107
      - 29203
    - - 30198
      - 29215
      - 31498
      - 31215
    - - 29461
      - 31228
      - 31511
      - 32478
```

**Comment by grossmanns** [comment]
You did it !
Thanks so much for your job and your patience.
![vac4](https://user-images.githubusercontent.com/62830240/97166076-f21c6080-1784-11eb-8681-9d29bf8514c1.png)

**Comment by PiotrMachowski** [comment]
Just one more suggestion: you probably can simplify your camera config:
```
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.x.x
    token: 4xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    username: xxxxxxxxxx.xxxxxxxxxxxxx@gmail.com
    password: xxxxxxxxxxxxx
    country: de
    name: My Robocop
    draw: ['all']
    map_transformation:
      scale: 2
    attributes:
      - calibration_points
```
