### ISSUE TITLE
I get a calibration error and no map

### ISSUE THREAD

**Issue by r77s** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#331]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I get the error message like in the picture. HA and die map extractor addon is updatet to the latest version.

![image](https://user-images.githubusercontent.com/18601077/186115912-7e7edcff-c45b-4262-8ac3-2c70430ae059.png)

### What version of am integration has described problem?

2.2.0

### What vacuum model do you have problems with?

Xiaomi 1s

### What version of Home Assistant do you use?

2022.8.6

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.178.37
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    attributes:
      - calibration_points
```
