### ISSUE TITLE
Invalid calibration(Map Extractor don't show map)

### ISSUE THREAD

**Issue by atticus-lv** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#337]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

![image](https://user-images.githubusercontent.com/64118610/188869416-cb86befd-68d5-4620-902e-40581c35ac4c.png)
I have manual install the lovelace and the map extractor. but it didn't show corrently. 

### What version of am integration has described problem?

the latest

### What was the last working version of an integration?

None

### What vacuum model do you have problems with?

xiaomi vacuum.v14_cloud_929750

### What version of Home Assistant do you use?

 20220802.0 - latest

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
have no logs report about this
```

### Additional information

I've check the file, seems that it didn't generate the map
![image](https://user-images.githubusercontent.com/64118610/188870295-8966d15b-46fb-4503-bb5e-b27b918f1347.png)
![image](https://user-images.githubusercontent.com/64118610/188870329-ee091be9-230c-4f3d-bb5c-5288e5d2fd20.png)
