### ISSUE TITLE
Component causes dashboard to infinitely reload on iPhone on iOS 16

### ISSUE THREAD

**Issue by thomwiggers** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#339]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Since updating to iOS 16, this component is causing the HASS dashboard to crash and reload in both the HASS app and Safari, until it gives up. It's not happening on my iPad, which is still on iOS 15.6.

### What version of an integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

roborock.vacuum.s5

### What version of Home Assistant do you use?

2022.9.0

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
platform: xiaomi_cloud_map_extractor
host: !secret stoffie_host
token: !secret xiaomi_token_stoffie
username: !secret xiaomi_username
password: !secret xiaomi_password
colors:
  color_map_outside: [0, 0, 0, 0]
#map_transformation:
#  scale: 2
#  trim:
#    top: 20
#    bottom: 21
#    left: 21
#    right: 22
draw:
  - all
attributes:
  - calibration_points
  - rooms
  - charger
  - no_go_areas
  - vacuum_position
  - walls
  - zones
scan_interval:
  seconds: 10
```

### Errors shown in the HA logs (if applicable)

```shell
N/A
```
