### ISSUE TITLE
room_colors is not changing my room colors

### ISSUE THREAD

**Issue by Thorvarium** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#341]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I am using this configuration below and my room colors are not changing, the colors are persisted the default ones.
I am not sure if I am adding the correct setting.

### What version of an integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

roborock s7 maxv ultra

### What version of Home Assistant do you use?

 2022.9.4

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: xxxxxx
    token: xxxxxx
    username: xxxxxx
    password: xxxxxx
    draw: ["all"]
    colors:
      color_map_outside: [28, 28, 28]
    room_colors:
      1: [0, 0, 0]
      2: [0, 0, 0]
      3: [0, 0, 0]
      4: [0, 0, 0]
      5: [0, 0, 0]
      6: [0, 0, 0]
    map_transformation:
      rotate: 270
      trim:
        top: 0
        bottom: 20
        right: 15
        left: 45
    attributes:
      - calibration_points
```
