### ISSUE TITLE
Whole HA is constantly restarting when using map_transformation

### ISSUE THREAD

**Issue by radimsejk** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#342]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

When I use map_transformation in my configuration, whole Home Assistant is constantly restarting every 5 to 15 minutes.

### What version of an integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

viomi.vacuum.v8

### What version of Home Assistant do you use?

2022.9.4

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
# #Xiaomi vacuum
- platform: xiaomi_cloud_map_extractor
  host: xxxxxxxxx
  token: "xxxxxxxxxxxxxxxxxxxx"
  username: "xxxxxxxxxxxxxxx"
  password: "xxxxxxxxxxx"
  name: "My Vacuum Camera"
  # map_transformation:
  #    scale: 6
  #    rotate: 0
  #    trim:
  #      top: 20
  #      bottom: 30
  #      left: 30
  #      right: 10
  draw:
    - charger
    - cleaned_area
    - goto_path
    - ignored_obstacles
    - ignored_obstacles_with_photo
    - no_go_zones
    - no_mopping_zones
    - obstacles
    - obstacles_with_photo
    - path
    - predicted_path
    - room_names
    - vacuum_position
    - virtual_walls
    - zones
  attributes:
    - calibration_points
    - charger
    - cleaned_rooms
    - country
    - goto
    - goto_path
    - goto_predicted_path
    - image
    - is_empty
    - map_name
    - no_go_areas
    - no_mopping_areas
    - obstacles
    - ignored_obstacles
    - obstacles_with_photo
    - ignored_obstacles_with_photo
    - path
    - room_numbers
    - rooms
    - vacuum_position
    - vacuum_room
    - vacuum_room_name
    - walls
    - zones
  sizes:
    charger_radius: 10
    vacuum_radius: 12
    obstacle_radius: 3
    ignored_obstacle_radius: 3
    obstacle_with_photo_radius: 3
    ignored_obstacle_with_photo_radius: 3
  colors:
    color_map_inside: [32, 115, 185]
    color_map_outside: [19, 87, 148]
    color_map_wall: [100, 196, 254]
    color_map_wall_v2: [93, 109, 126]
    color_grey_wall: [93, 109, 126]
    color_ignored_obstacle: [0, 0, 0, 127]
    color_ignored_obstacle_with_photo: [0, 0, 0, 127]
    color_obstacle: [0, 0, 0, 127]
    color_obstacle_with_photo: [0, 0, 0, 127]
    color_path: [147, 194, 238]
    color_goto_path: [0, 255, 0]
    color_predicted_path: [255, 255, 0, 0]
    color_cleaned_area: [127, 127, 127, 127]
    color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
    color_zones_outline: [0xAD, 0xD8, 0xFF]
    color_virtual_walls: [255, 0, 0]
    color_new_discovered_area: [64, 64, 64]
    color_no_go_zones: [255, 33, 55, 127]
    color_no_go_zones_outline: [255, 0, 0]
    color_no_mop_zones: [163, 130, 211, 127]
    color_no_mop_zones_outline: [163, 130, 211]
    color_charger: [0x66, 0xfe, 0xda, 0x7f]
    color_robo: [75, 235, 149]
    color_room_names: [0, 0, 0]
    color_unknown: [0, 0, 0]
    color_scan: [0xDF, 0xDF, 0xDF]
```
