### ISSUE TITLE
 Vacuum.viomi.v10 does not display the map correctly

### ISSUE THREAD

**Issue by darcarper** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#343]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

The map shown appears as a duplicate, also when you send to a cleaning area it does not correspond to the right place.
![image](https://user-images.githubusercontent.com/69854550/191313396-5663800c-7fc8-4133-b8c4-7351ef9cd575.png)
![Screenshot_2022-09-15-20-11-56-427_com xiaomi smarthome (1)](https://user-images.githubusercontent.com/69854550/191313454-213f1694-b47b-4ebb-bd6c-9d109d651f4d.jpg)

### What version of an integration has described problem?

2.2.0

### What vacuum model do you have problems with?

viomi.vacuum.v10

### What version of Home Assistant do you use?

2022.9.4

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.121
    token: 4b7841XXXXXXX
    username: XXXXX
    password: XXXXXXXXX
    draw: ['all']
    attributes:
      - calibration_points
```

### Additional information

Card:
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.viomi_v10_804a_robot_cleaner
vacuum_platform: send_command
map_locked: false
two_finger_pan: false
map_modes:
  - template: vacuum_clean_zone_predefined
    predefined_selections:
      - zones:
          - - -6.1
            - -7
            - -2.5
            - -4

  - template: vacuum_clean_zone
  - template: vacuum_goto
