### ISSUE TITLE
Xiaomi Vac/Mop Essential (mijia.vacuum.v2) Issues

### ISSUE THREAD

**Issue by 503Dev** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#345]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

When attempting to extract the map from a Xiaomi Mi Vac and Map Essential (shows ID as: mijia.vacuum.v2 in the token extractor) the map does not load.  It appears login to the Xiaomi servers is ok but no mapa data is obtained.  I read for this model the _forced _api __ mode should be roidmi albeit I have tried all available options.

### What version of an integration has described problem?

2.2.0

### What vacuum model do you have problems with?

mijia.vacuum.v2

### What version of Home Assistant do you use?

2022.9.6

### What type of installation are you running?

Home Assistant Supervised

### Camera's configuration

```yaml
camera:
  platform: xiaomi_cloud_map_extractor
  host: [redacted]
  token: "[redacted]"
  username: [redacted]
  password: [redacted]
  store_map_raw: true
  store_map_image: true
  store_map_path: /share
  force_api: roidmi
```

### Errors shown in the HA logs (if applicable)

```shell
`2022-09-23 03:28:36.333 DEBUG (SyncWorker_3) [custom_components.xiaomi_cloud_map_extractor.camera] Logging in...
2022-09-23 03:28:38.801 DEBUG (SyncWorker_3) [custom_components.xiaomi_cloud_map_extractor.camera] Logged in
2022-09-23 03:28:38.801 DEBUG (SyncWorker_3) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map from Xiaomi cloud
2022-09-23 03:28:40.447 WARNING (SyncWorker_3) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map data`
```

### Additional information

The above errors are from the current test using the api as roidmi.  This option appears to be the most viable as it shows the correct server login, etc.  The camera entity is just blank, it does not show any picture. 

I can see the map in the Mi Home app and I have already tried a full robot reset to no avail.
