### ISSUE TITLE
Dreame F9 app_goto_target and vacuum_clean_segment/_zone 'Service not found'

### ISSUE THREAD

**Issue by ButterBetzi** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#348]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

If i try to clean a room (segment) with the UI i get the following error with my dreame f9:
"[...] xiaomi_miio/vacuum_clean_segment. Service not found."

It's the same with xiaomi_miio/vacuum_clean_zone and xiaomi_miio/vacuum_goto.

### What version of an integration has described problem?

 v2.2.0

### What vacuum model do you have problems with?

dreame.vacuum.p2008

### What version of Home Assistant do you use?

2022.9.6

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    country: "de"
    room_colors:
      1: [228, 12, 43]
      2: [29, 29, 44]
      3: [195, 96, 60]
      4: [60, 188, 195]
      5: [235, 166, 63]
      6: [67, 137, 69]
    colors:
      color_map_wall: [255, 255, 255]
    auto_update: true
    attributes:
      - calibration_points
      - charger
      - cleaned_rooms
      - country
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - ignored_obstacles
      - obstacles_with_photo
      - ignored_obstacles_with_photo
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - vacuum_room_name
      - walls
      - zones
    sizes:
      charger_radius: 4
      vacuum_radius: 4
```
