### ISSUE TITLE
Configuration Validator "check configuration" never finishes

### ISSUE THREAD

**Issue by nickdos** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#35]
I've added this custom integration via HACS and can see it is installed as an integration in the HACS interface. I then added the config to my `configuration.yaml` file under an existing `camera` entry I already had.

```yaml
-   platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_robot_host
    token: !secret xiaomi_cloud_robot_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: cn
    draw: ['all']
    attributes:
      - calibration_points
      - vacuum_position
      - charger
```

When I go to the Configuration Validator section in HA and click the "check configuration" button, I see the spinning icon but it never finishes (just spins forever). If I comment out the changes above, the checker returns `"check configuration"`. If I change one of the entries for my secrets file, I get the expected `Configuration invalid` response (e.g. Secret xiaomi_cloud_passwordX not defined). I'm also not able to trigger a restart, as a similar thing happens - restart never gets triggered.

I've confirmed my login details and token using the [Xiaomi-cloud-tokens-extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/blob/master/token_extractor.py) tool. Which is why I added the `country` attribute above, as I noticed my robot vacuum listed for multiple country servers, so went with `cn` attributes.

Can't see anything in my HA logs about this integration or about failed config test.
