### ISSUE TITLE
Trim lost when changing floor (multi-floor)

### ISSUE THREAD

**Issue by starkillerOG** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#350]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

First of all, thanks for the greath work!
When my roborock S7 MaxV is downstairs it shows the map niceley and I can set the Trim values to fit the map and remove the white boarder around the map.
When I then change the map to the upstairs floor (either manually in the app, or by placing the roborock upstairs and using positining which will automattically change map), the cloud map extractor also shows the upstairs floor, so far so good.
But when I then change the map back to downstairs, the Trim values are not applied anymore and the original white boarder is again present around the map.
If I then reload the Xiaomi_Cloud_Map_Extractor (through the Development Tools in HA), the Trim values are applied correctly again.

So it looks like trim values are only applied during startup of the component.
Could you make sure Trim values are also applied when switching map?

For a feature request it would be greath if you could supply multiple sets of Trim values which are conditional, such that I can have diffrent Trim values for each floor (I already know how to make a sensor that will show the current floor index).

### What version of an integration has described problem?

2.2.0

### What vacuum model do you have problems with?

Roborock S7 MaxV

### What version of Home Assistant do you use?

2022.09

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    name: Roborock map
    host: "192.168.1.xxx"
    token: xxx
    username: xxx
    password: xxx
    country: "xx"
    draw: ['all']
    map_transformation:
      scale: 5
      rotate: 180
      trim:
        top: 20
        bottom: 20
        left: 15.5
        right: 15.5
    sizes:
      vacuum_radius: 20
      charger_radius: 20
      path_width: 2
      obstacle_radius: 10
      ignored_obstacle_radius: 10
      obstacle_with_photo_radius: 10
      ignored_obstacle_with_photo_radius: 10
    attributes:
      - calibration_points
      - vacuum_room
    colors:
      color_map_outside: [255, 255, 255]
      color_ignored_obstacle: [0, 50, 0, 20]
      color_ignored_obstacle_with_photo: [0, 50, 0, 20]
      color_obstacle: [50, 0, 0, 127]
      color_obstacle_with_photo: [50, 0, 0, 127]
      color_no_mop_zones: [60, 217, 252, 75]
      color_no_mop_zones_outline: [60, 217, 252, 127]
    room_colors:
      17: [ 255, 87, 51]
      16: [61, 157, 228]
      19: [255, 195, 0]
```
