### ISSUE TITLE
Unikatowy identyfikator

### ISSUE THREAD

**Issue by johnyts** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#351]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Witam

Mam problem po instalacji, pojawia się mapa ale w opcji  "Ustawiania encji" pojawia się poniższy komunikat.

Ta encja ("camera.xiaomi_cloud_map_extractor") nie ma unikalnego identyfikatora, dlatego z poziomu interfejsu użytkownika nie można zarządzać jej ustawieniami. Więcej szczegółów znajdziesz w [dokumentacji](https://www.home-assistant.io/faq/unique_id).

### What version of an integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

viomi.vacuum.v8

### What version of Home Assistant do you use?

Home Assistant 2022.9.7

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 10.1.0.13
    token: *************************
    username: mojadres@gmail.com
    password: haslo
    draw: ['all']
    attributes:
      - calibration_points
```
