### ISSUE TITLE
Unable to retrieve map for Roborock 4

### ISSUE THREAD

**Issue by fire943** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#352]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Failing to retrieve map.  I am able to control my vacuum using vacuum card.

### What version of an integration has described problem?

v2.2.0

### What was the last working version of an integration?

v2.2.0

### What vacuum model do you have problems with?

roborock S4

### What version of Home Assistant do you use?

 Home Assistant 2022.10.5

### What type of installation are you running?

Home Assistant Supervised

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: xxx.xxx.xx.xx
    token: xxxxxxxxxxxxxxxxxxxxxx
    username: xxxxxx@gmail.com
    password: xxxx
    draw: ['all']
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
Logger: homeassistant.components.camera
Source: helpers/entity_platform.py:796
Integration: Camera (documentation, issues)
First occurred: 12:24:52 AM (64 occurrences)
Last logged: 12:30:37 AM
Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
```
