### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by Phobos06** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#36]
Hi everybody

I've just tried to install the "xiaomi vacumm card"  (manually and through HACS) with the integration with the "cloud map extractor".

From the card i can start and stop my vacuum.
The issue is about the rendering. The card shows only half of my flat
![image](https://user-images.githubusercontent.com/35897973/97638656-4f423b80-1a3d-11eb-9668-6f0963afb0c0.png)

I've tried to change "the scale" in the "cloud map extractor configs" configs, i've rebooted the system, cleared the cache, removed and reinstall the component.. but i can't fix this issue.
i changed the rotation and it works, so i think is only a "size problem"

Can anyone help me?

here the card config:
```yaml
type: 'custom:xiaomi-vacuum-map-card'
entity: vacuum.xiaomi_vacuum_cleaner
camera_calibration: true
map_camera: camera.xiaomi_cloud_map_extractor
debug: false
```
and here the config file
``` yaml
vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_ip 
    token: !secret vacuum_token
    
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret vacuum_ip
    token: !secret vacuum_token
    username: !secret vacuum_cloud_username
    password: !secret vacuum_cloud_password
    country: "cn"
    name: "xiaomi_cloud_map_extractor"
    draw:
      - charger
      - path
      - goto_path
      - predicted_path
      - no_go_zones
      - no_mopping_zones
      - vacuum_position
      - virtual_walls
      - zones
    map_transformation:
      scale: 1
      rotate: 180
      trim:
        top: 10
        bottom: 20
        left: 30
        right: 40
    sizes:
      charger_radius: 4
      vacuum_radius: 6.5
    attributes:
      - calibration_points
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - walls
      - zones
    scan_interval:
      seconds: 10
    auto_update: true
```

Thanks
