### ISSUE TITLE
Got exception while fetching the state: Unable to discover the device 192.168.68.55

### ISSUE THREAD

**Issue by cloudbr34k84** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#367]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:273
Integration: xiaomi_cloud_map_extractor ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues))
First occurred: 7:30:38 am (2 occurrences)
Last logged: 7:30:39 am

Got exception while fetching the state: Unable to discover the device XXXXXXXX
Got exception while fetching the state: Unable to discover the device XXXXXXXX

### What version of an integration has described problem?

version v2.1.2

### What was the last working version of an integration?

Unsure

### What vacuum model do you have problems with?

S5 Max, and S6 Pure

### What version of Home Assistant do you use?

Home Assistant 2022.11.2

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
- platform: xiaomi_cloud_map_extractor
  host: -
  token: -
  username: -
  password: -
  country: "sg"
  name: "S6 Vacuum Map"
  draw: ["all"]
  attributes:
    - calibration_points
    - charger
    - cleaned_rooms
    - country
    - goto
    - goto_path
    - goto_predicted_path
    - image
    - is_empty
    - map_name
    - no_go_areas
    - no_mopping_areas
    - obstacles
    - ignored_obstacles
    - obstacles_with_photo
    - ignored_obstacles_with_photo
    - path
    - room_numbers
    - rooms
    - vacuum_position
    - vacuum_room
    - vacuum_room_name
    - walls
    - zones
  scan_interval:
    seconds: 240
  auto_update: true
  store_map_raw: true
  store_map_image: true
  store_map_path: "/tmp"
  force_api: xiaomi
```

### Errors shown in the HA logs (if applicable)

```shell
Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:273
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 7:30:38 am (2 occurrences)
Last logged: 7:30:39 am

Got exception while fetching the state: Unable to discover the device 192.168.68.55
Got exception while fetching the state: Unable to discover the device 192.168.68.57
```

> > why change password??
> 
> I suspect that's because you have posted your full credentials (token/username/password) in your config 😉 (I have edited it)

oFFS! god im stupid
