### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jscherry** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#37]
The card seems to be working but I keep getting the errors below. The other problem I have is that the vacuum doesn’t respond to the commands like zone, go to,etc
```
Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_cloud_map_extractor/map_data_parser.py:94
First occurred: 12:30:25 PM (1 occurrences) 
Last logged: 12:30:25 PM

Update for camera.roborock_camera fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_cloud_map_extractor/camera.py", line 190, in update
    map_data = self._connector.get_map(self._country, map_name, self._colors, self._drawables, self._texts,
  File "/config/custom_components/xiaomi_cloud_map_extractor/xiaomi_cloud_connector.py", line 117, in get_map
    map_data = MapDataParser.parse(unzipped, colors, drawables, texts, sizes, image_config)
  File "/config/custom_components/xiaomi_cloud_map_extractor/map_data_parser.py", line 79, in parse
    map_data.vacuum_room = MapDataParser.get_current_vacuum_room(img_start, raw, map_data.vacuum_position)
  File "/config/custom_components/xiaomi_cloud_map_extractor/map_data_parser.py", line 94, in get_current_vacuum_room
    x = round(vacuum_position.x / MapDataParser.MM - image_left)
AttributeError: 'NoneType' object has no attribute 'x'
```

**Comment by jscherry** [comment]
The card does show the map, vacuum path, vacuum position. I'm not getting room names, room numbers, and the commands don't work. Here's my card config:
type: 'custom:xiaomi-vacuum-map-card'
entity: vacuum.xiaomi_vacuum
map_camera: camera.roborock_camera
camera_calibration: true

**Comment by jscherry** [comment]
![image](https://user-images.githubusercontent.com/13368828/97743306-74719100-1ab3-11eb-80e8-cb7fd9f14866.png)

**Comment by benleb** [comment]
check the readme 😉

**Comment by PiotrMachowski** [comment]
I have added check that will prevent such errors.

Can you show configuration of a camera? Do you have added appropriate values in `attributes` section?

Calling vacuum services is not possible via this component, so problem is probably somewhere else.

**Comment by jscherry** [comment]
I can use the vacuum commands successfully with the vacuum and another lovelace card. What changes would I need to make to get the commands at the bottom of the xiaomi vacuum map card to work? Here's my camera config below. Thanks in advance

- platform: xiaomi_cloud_map_extractor
      host: 192.168.1.149
      token: 33757a4d47743461654b4e3237615335
      username: xxxxxxxxxxxx
      password: xxxxxxxxxx
      country: "us"
      name: "Roborock Camera"
      colors:
        color_map_inside: [32, 115, 185]
        color_map_outside: [19, 87, 148]
        color_map_wall: [100, 196, 254]
        color_map_wall_v2: [93, 109, 126]
        color_grey_wall: [93, 109, 126]
        color_path: [252, 3, 48]
        color_goto_path: [0, 255, 0]
        color_predicted_path: [255, 255, 0, 0]
        color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
        color_zones_outline: [0xAD, 0xD8, 0xFF]
        color_virtual_walls: [255, 0, 0]
        color_no_go_zones: [255, 33, 55, 127]
        color_no_go_zones_outline: [255, 0, 0]
        color_no_mop_zones: [163, 130, 211, 127]
        color_no_mop_zones_outline: [163, 130, 211]
        color_charger: [0x66, 0xfe, 0xda, 0x7f]
        color_robo: [75, 235, 149]
        color_unknown: [0, 0, 0]
        color_scan: [0xDF, 0xDF, 0xDF]
      room_colors:
        1: [240, 178, 122]
        2: [133, 193, 233]
        3: [217, 136, 128]
        4: [52, 152, 219]
        5: [205, 97, 85]
        6: [243, 156, 18]
        7: [88, 214, 141]
        8: [245, 176, 65]
        9: [252, 212, 81]
        10: [72, 201, 176]
        11: [84, 153, 199]
        12: [133, 193, 233]
        13: [245, 176, 65]
        14: [82, 190, 128]
        15: [72, 201, 176]
        16: [165, 105, 18]
      draw:
        - charger
        - path
        - goto_path
        - predicted_path
        - no_go_zones
        - no_mopping_zones
        - vacuum_position
        - virtual_walls
        - zones
      texts:
        - text: "Room 1"
          x: 25
          y: 25
          color: [125, 20, 213]
        - text: "Room 2"
          x: 25
          y: 75
          color: [125, 20, 213, 127]
          font: "FreeSans.ttf"
          font_size: 36
      map_transformation:
        scale: 2
      sizes:
        charger_radius: 4
        vacuum_radius: 6.5
      attributes:
        - calibration_points
        - charger
        - goto
        - goto_path
        - goto_predicted_path
        - image
        - is_empty
        - map_name
        - no_go_areas
        - no_mopping_areas
        - obstacles
        - path
        - room_numbers
        - rooms
        - vacuum_position
        - vacuum_room
        - walls
        - zones
      scan_interval:
        seconds: 10
      auto_update: true

**Comment by jscherry** [comment]
Indentations and script above are correct in config, didn't copy over properly.

**Comment by PiotrMachowski** [comment]
I have removed your comment, because you have pasted your token. Here is corrected version:

I can use the vacuum commands successfully with the vacuum and another lovelace card. What changes would I need to make to get the commands at the bottom of the xiaomi vacuum map card to work? Here's my camera config below. Thanks in advance

```
platform: xiaomi_cloud_map_extractor
host: 192.168.xxx.xxx
token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
username: xxxxxxxxxxxx
password: xxxxxxxxxx
country: "us"
name: "Roborock Camera"
colors:
  color_map_inside: [32, 115, 185]
  color_map_outside: [19, 87, 148]
  color_map_wall: [100, 196, 254]
  color_map_wall_v2: [93, 109, 126]
  color_grey_wall: [93, 109, 126]
  color_path: [252, 3, 48]
  color_goto_path: [0, 255, 0]
  color_predicted_path: [255, 255, 0, 0]
  color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
  color_zones_outline: [0xAD, 0xD8, 0xFF]
  color_virtual_walls: [255, 0, 0]
  color_no_go_zones: [255, 33, 55, 127]
  color_no_go_zones_outline: [255, 0, 0]
  color_no_mop_zones: [163, 130, 211, 127]
  color_no_mop_zones_outline: [163, 130, 211]
  color_charger: [0x66, 0xfe, 0xda, 0x7f]
  color_robo: [75, 235, 149]
  color_unknown: [0, 0, 0]
  color_scan: [0xDF, 0xDF, 0xDF]
room_colors:
  1: [240, 178, 122]
  2: [133, 193, 233]
  3: [217, 136, 128]
  4: [52, 152, 219]
  5: [205, 97, 85]
  6: [243, 156, 18]
  7: [88, 214, 141]
  8: [245, 176, 65]
  9: [252, 212, 81]
  10: [72, 201, 176]
  11: [84, 153, 199]
  12: [133, 193, 233]
  13: [245, 176, 65]
  14: [82, 190, 128]
  15: [72, 201, 176]
  16: [165, 105, 18]
draw:
  - charger
  - path
  - goto_path
  - predicted_path
  - no_go_zones
  - no_mopping_zones
  - vacuum_position
  - virtual_walls
  - zones
texts:
  - text: "Room 1"
    x: 25
    y: 25
    color: [125, 20, 213]
  - text: "Room 2"
    x: 25
    y: 75
    color: [125, 20, 213, 127]
    font: "FreeSans.ttf"
    font_size: 36
map_transformation:
  scale: 2
  sizes:
    charger_radius: 4
    vacuum_radius: 6.5
attributes:
  - calibration_points
  - charger
  - goto
  - goto_path
  - goto_predicted_path
  - image
  - is_empty
  - map_name
  - no_go_areas
  - no_mopping_areas
  - obstacles
  - path
  - room_numbers
  - rooms
  - vacuum_position
  - vacuum_room
  - walls
  - zones
scan_interval:
  seconds: 10
auto_update: true
```
