### ISSUE TITLE
Country should be a required field

### ISSUE THREAD

**Issue by ymatsiuk** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#380]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Using recommended configuration doesn't work anymore:

```
dec 22 18:20:58 nixpi4 hass[48556]: 2022-12-22 18:20:58.965 DEBUG (SyncWorker_3) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device
dec 22 18:21:02 nixpi4 hass[48556]: 2022-12-22 18:21:02.964 ERROR (SyncWorker_3) [custom_components.xiaomi_cloud_map_extractor.camera] Got OSError while fetching the state: [Errno -2] Name or service not known
```

Digging deeper I suspect [this](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/blob/dd5cb2e1af83cef8b80a1c1520ef4ce1ba2cfcf5/custom_components/xiaomi_cloud_map_extractor/common/xiaomi_cloud_connector.py#L192) is the root cause since the `country` is missing from either "Basic" or "Recommended" examples. Documentation states `country` is optional field, that apparently defaults to `None` [here](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/blob/dd5cb2e1af83cef8b80a1c1520ef4ce1ba2cfcf5/custom_components/xiaomi_cloud_map_extractor/camera.py#L69). That leads to API URL rendered to something like `https://.api.io.mi.com/app` 

### What version of an integration has described problem?

master (b4ae1d4bdd8268087cd269c7aeb2207a6dbefb2e)

### What vacuum model do you have problems with?

roborock.vacuum.s5e

### What version of Home Assistant do you use?

core-2022.12.6

### What type of installation are you running?

Home Assistant Core

### Camera's configuration

Basic

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
```

Recommended

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
dec 22 18:20:49 nixpi4 hass[48556]: 2022-12-22 18:20:49.131 DEBUG (SyncWorker_3) [custom_components.xiaomi_cloud_map_extractor.camera] Logged in
dec 22 18:20:49 nixpi4 hass[48556]: 2022-12-22 18:20:49.132 DEBUG (SyncWorker_3) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving device info, country: None
dec 22 18:20:50 nixpi4 hass[48556]: 2022-12-22 18:20:50.970 DEBUG (SyncWorker_3) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieved device model: roborock.vacuum.s5e
dec 22 18:20:50 nixpi4 hass[48556]: 2022-12-22 18:20:50.971 DEBUG (SyncWorker_3) [custom_components.xiaomi_cloud_map_extractor.camera] Created device, used api: xiaomi
dec 22 18:20:50 nixpi4 hass[48556]: 2022-12-22 18:20:50.971 DEBUG (SyncWorker_3) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device
dec 22 18:20:54 nixpi4 hass[48556]: 2022-12-22 18:20:54.964 ERROR (SyncWorker_3) [custom_components.xiaomi_cloud_map_extractor.camera] Got OSError while fetching the state: [Errno -2] Name or service not known
```
