### ISSUE TITLE
Failed to retrieve device

### ISSUE THREAD

**Issue by VitorCastanheiro** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#383]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hi! I have a Roborock S5 and I have configured the card, but for some reason it isnt able to retrieve the device. I am using the same IP and token on another widget and works fine... actually the lovelace component you also build :) works great, but not the map extractor...

### What version of an integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

roborock.vacuum.s5

### What version of Home Assistant do you use?

2022.11.5

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.74
    token: <working token>
    username: <working mail>
    password: <working pass>
    country: de
    draw: ['all']
    attributes:
      - country
```

### Errors shown in the HA logs (if applicable)

```shell
Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:272
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 3:03:12 PM (13 occurrences)
Last logged: 3:14:13 PM

Failed to retrieve model
```

### Additional information

<img width="1093" alt="ha vacuum card error" src="https://user-images.githubusercontent.com/22219747/210587200-b3672337-6632-470a-835d-98048790012b.png">
