### ISSUE TITLE
How can I do multiple vacuums?

### ISSUE THREAD

**Issue by ghallford** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#391]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I saw issue #199 but adding a name, still only gives me one of my vacuums (Vacuum2). How can I add the second one?

### What version of an integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

roborock.vacuum.s5

### What version of Home Assistant do you use?

core-2023.1.6

### What type of installation are you running?

Home Assistant Core

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    name: Vacuum1
    host: 192.168.2.189
    token:  <removed>
    username: <removed>
    password: <removed>
    country: us
    draw: ['all']
    attributes:
      - calibration_points

camera:
  - platform: xiaomi_cloud_map_extractor
    name: Vacuum2
    host: 192.168.2.120
    token: <removed>
    username: <removed>
    password: <removed>
    country: us
    draw: ['all']
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
2023-01-22 11:49:56.419 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "camera". Check lines 121 and 133
```

**Comment by PiotrMachowski** [comment]
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    name: Vacuum1
    host: 192.168.2.189
    token:  <removed>
    username: <removed>
    password: <removed>
    country: us
    draw: ['all']
    attributes:
      - calibration_points
  - platform: xiaomi_cloud_map_extractor
    name: Vacuum2
    host: 192.168.2.120
    token: <removed>
    username: <removed>
    password: <removed>
    country: us
    draw: ['all']
    attributes:
      - calibration_points
```
