### ISSUE TITLE
Cannot change map colors

### ISSUE THREAD

**Issue by mebitek** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#392]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I cannot change map colors with dreame.vacuum.p2041o

### What version of an integration has described problem?

latest

### What vacuum model do you have problems with?

dreame.vacuum.p2041o

### What version of Home Assistant do you use?

2023.1.6

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.240
    token: token
    username: I_have_shared_my_real_credentials@gmail.com 
    password: I_have_shared_my_real_credentials
    country: "de"
    draw: ['all']
    colors: 
      color_map_outside: [0, 0, 0]
    attributes:
      - calibration_points
      - rooms
      - walls
```
