### ISSUE TITLE
Cannot change color_charger_outline

### ISSUE THREAD

**Issue by mebitek** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#395]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

when I set in config color_charger_outline nothing happens.

### What version of an integration has described problem?

latest

### What vacuum model do you have problems with?

dreame.vacuum.p2041o

### What version of Home Assistant do you use?

2023.1.7

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host:  ****
    token: *****
    username: ****
    password: *****
    country: "de"
    draw: ['all']
    colors:
        color_charger: [47, 186, 36]
        color_charger_outline: [26, 146, 16]
        color_robo: [94, 94, 94]
        color_robo_outline: [126,126,126]
        color_map_wall: [128,128,128]
        color_path: [255, 255, 255]
    room_colors:
        1: [188, 157, 62]
        2: [108, 141, 195]
        3: [88, 161, 176]    
    map_transformation:
        scale: 3
        rotate: 90
    sizes:
        charger_radius: 4
        vacuum_radius: 6        
    attributes:
      - calibration_points
      - rooms
    force_api: dreame
    store_map_raw: true
    store_map_image: true
    store_map_path: "/media"
```
