### ISSUE TITLE
Unable to add Map Extractor Integration

### ISSUE THREAD

**Issue by loganYdid** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#409]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I was able to successfully add the Xiaomi Cloud Map Extractor integration but I ran into an issue and as a part of troubleshooting I clicked the "..." on the integration screen and deleted the integration. I realized later that the problem was that my vacuum changed IP addresses so I tried re-adding the integration but I could not. I tried uninstalling the Xiaomi Cloud Map Extractor integration from HACS, removed the config for the map extractor from the configuration.yaml, and completly restarting the host PC. Then I tried reinstalling everything and adding the same config back to configuration.yaml but I can not get the integration to show back up in the integrations page.

### What version of an integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

roborock s7 maxV ultra

### What version of Home Assistant do you use?

2023.2.5

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: "192.168.1.2"
    token: "##############################"
    username: "##########@######.###"
    password: "##############"
    colors:
      color_path: [255, 255, 255]
      color_map_outside: [255, 255, 255, 0]
    room_colors:
        1: [242, 176, 119]
        2: [217, 102, 61]
        3: [166, 85, 78]
    draw: ['all']
    map_transformation:
      scale: 1
      trim:
        top: 20
        bottom: 20
        left: 20
        right: 20
    auto_update: true
    scan_interval:
      seconds: 10 
    attributes:
      - calibration_points
```
