### ISSUE TITLE
Vacuum position not updating correctly

### ISSUE THREAD

**Issue by bkr1969** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#413]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I used to be able to follow the vacuum around "live" but now the vacuum position takes anywhere from 10-30 seconds to update.

### What version of an integration has described problem?

v2.2.0

### What was the last working version of an integration?

v2.2.0

### What vacuum model do you have problems with?

S7 MaxV

### What version of Home Assistant do you use?

2023.03.1

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 172.16.0.247
    token: provided
    username: public
    password: compromised
    draw: ['all']
    attributes:
      - calibration_points
      - vacuum_position
    map_transformation:
      rotate: 180
    scan_interval:
      seconds: 1
    auto_update: true
```

### Errors shown in the HA logs (if applicable)

```shell
N/A
```

### Additional information

Seems to have happened with latest core update.
