### ISSUE TITLE
camera.turn_off does not disable automatic updates

### ISSUE THREAD

**Issue by peterjuras** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#426]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hi! First of all thank you for creating this extension, it's really amazing! 🎉

I am using [your suggested blueprint](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#:~:text=If%20you%20want%20to%20disable%20map%20updates%20when%20a%20vacuum%20is%20not%20running%20you%20can%20use%20this%20blueprint.) to disable automatic updates of the map when the robot is not running, to prevent API rate limit as well as generally preserve resources for me (and Xiaomi 😊).

I have the impression that turning off the camera via the `camera.turn_off` service is not working correctly, it still appears to be updating the map every 5 seconds.

Do you know where the issue could be?

### What version of an integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

roborock.vacuum.s7

### What version of Home Assistant do you use?

2023.4.6

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
- platform: xiaomi_cloud_map_extractor
  name: Roomba
  host: !secret xiaomi_vacuum_host
  token: !secret xiaomi_vacuum_token
  username: !secret xiaomi_cloud_username
  password: !secret xiaomi_cloud_password
  country: de
  draw: ["all"]
  map_transformation:
    rotate: 90
  colors:
    color_map_outside: [34, 42, 48]
  # Color palette from https://colorkit.co/palette/ff595e-ff924c-ffca3a-c5ca30-8ac926-52a675-1982c4-4267ac-6a4c93-b5a6c9/
  room_colors:
    "16":
      - 255
      - 89
      - 94
    "17":
      - 255
      - 146
      - 76
    "18":
      - 255
      - 202
      - 58
    "19":
      - 197
      - 202
      - 48
    "20":
      - 138
      - 201
      - 38
    "21":
      - 82
      - 166
      - 117
    "22":
      - 25
      - 130
      - 196
    "23": 
      - 155
      - 246
      - 255
    "24":
      - 255
      - 255
      - 234
    "25":
      - 181
      - 166
      - 201
  attributes:
    - calibration_points
    - rooms
```

### Errors shown in the HA logs (if applicable)

```shell
2023-04-23 09:06:05.684 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05

(Even after the camera service "turn_off" has been called)
```

**Comment by PiotrMachowski** [comment]
Can you show a yaml code of an automation you have created based on the blueprint?

**Comment by peterjuras** [comment]
Hi Piotr,
thanks for the reply!

This is the code - however the camera updates also don't stop if I call the `camera.turn_off` service manually.

```yaml
- id: '1682202102755'
  alias: Disable vacuum camera update when docked
  description: ''
  use_blueprint:
    path: PiotrMachowski/disable_vacuum_camera_update_when_docked.yaml
    input:
      vacuum: vacuum.roomba
      camera: camera.roomba
```
