### ISSUE TITLE
State attributes exceed maximum size

### ISSUE THREAD

**Issue by luzik** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#427]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

My logs are full of

`WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for camera.xiaomi_cloud_map_extractor exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored`

But integration seams to work ok

### What version of an integration has described problem?

latests

### What vacuum model do you have problems with?

roidmi eve

### What version of Home Assistant do you use?

lastest

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
camera:
    - platform: xiaomi_cloud_map_extractor
      host: !secret xiaomi_vacuum_host
      token: !secret xiaomi_vacuum_token
      username: !secret xiaomi_cloud_username
      password: !secret xiaomi_cloud_password
      force_api: roidmi
      draw: ['all']
      attributes:
        - calibration_points
        - charger
        - goto
        - goto_path
        - goto_predicted_path
        - image
        - map_name
        - obstacles
        - path
        - room_numbers
        - rooms
        - vacuum_position
        - vacuum_room
        - walls
        - zones
```

**Comment by PiotrMachowski** [comment]
Use following config instead:
```yaml
camera:
    - platform: xiaomi_cloud_map_extractor
      host: !secret xiaomi_vacuum_host
      token: !secret xiaomi_vacuum_token
      username: !secret xiaomi_cloud_username
      password: !secret xiaomi_cloud_password
      force_api: roidmi
      draw: ['all']
      attributes:
        - calibration_points
```
