### ISSUE TITLE
Roborock S8 (A51) : failed to retreive map from vacuum

### ISSUE THREAD

**Issue by multinet33** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#433]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Unable to retrieve map from roborock S8

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Interface utilisateur : 20230503.3 - latest

### What version of an integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

roborock.vacuum.a51

### What version of Home Assistant do you use?

core-2023.5.2

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
#############################################
##                                         ##
##            Aspi carto S8                ##
##                                         ##
#############################################  
  - platform: xiaomi_cloud_map_extractor
    host: !secret s8_host
    token: !secret s8_token
    username: !secret xiaomi_username
    password: !secret xiaomi_password
    name: "Roborock S8"
    draw: ['all']
    attributes:
      - calibration_points
      - room_numbers
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - rooms
      - vacuum_position
      - vacuum_room
      - walls
      - zones
    sizes:
      charger_radius: 4
      vacuum_radius: 6
    map_transformation:
      scale: 1
      trim:
        top: 23
        bottom: 23
        left: 23
        right: 23
    colors:
      color_path: [255, 255, 255]
      color_robo : [255, 255, 255] 
      color_map_inside: [32, 115, 185]
      color_map_outside: [32, 44, 69]
      color_map_wall: [100, 196, 254]
      color_map_wall_v2: [93, 109, 126]
      color_grey_wall: [93, 109, 126]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_unknown: [250, 250, 250] #[0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
```

### Errors shown in the HA logs (if applicable)

```shell
no log
```
