### ISSUE TITLE
Increased CPU usage on Home Assistant OS after adding yaml config

### ISSUE THREAD

**Issue by nightshadow931** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#442]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

So, after I add the config to my configuration.yaml and restart my home assistant, CPU usage jumps from about 7-9% to around 16-20%. The config works, I can see the map, there are no errors in the log.
When I comment out my config and restart home assistant again, everything goes back to normal
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/10613880/d1519d1d-55da-40a3-8268-25bfd67e86fb)
You can see what I'm talking about from the picture.

### What version of an integration has described problem?

v2.2.0

### What was the last working version of an integration?

/

### What vacuum model do you have problems with?

Xiaomi Mi Mop 2 Pro+(think it's dreame.vacuum.p2041o)

### What version of Home Assistant do you use?

Home Assistant 2023.6.0

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.9
    token: longtoken
    username: myemail
    password: mypassword
    draw: ['all']
    name: "Boza"
    attributes:
      - calibration_points
```
