### ISSUE TITLE
Cant change colors or dissable icons in map

### ISSUE THREAD

**Issue by cris1410** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#447]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I cant change any colors in map (room, charger, vacuum, ...).
After I edit the config and reload it, it has no impact and nothing in map changes.
Also I want to turn off room icons and labels and number without no success.

### What version of an integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

dreame.vacuum.r2211o

### What version of Home Assistant do you use?

Home Assistant 2023.6.2

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.0.xxx
    token: **************
    username: *********
    password: *********
    attributes:
      - calibration_points
      - charger
      - cleaned_rooms
      - country
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - ignored_obstacles
      - obstacles_with_photo
      - ignored_obstacles_with_photo
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - vacuum_room_name
      - walls
      - zones
    store_map_raw: true
    store_map_path: /config
    colors:
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [255, 0, 0]
    room_colors:
      1: [255, 227, 168]
      2: [255, 168, 168]
      3: [168, 206, 255]
      4: [100, 100, 100]
      5: [168, 168, 168]
      6: [249, 255, 82]
      7: [137, 255, 82]
      8: [255, 138, 241]
      9: [153, 64, 255]
      10: [0, 175, 201]
      11: [249, 255, 82]
      12: [137, 255, 82]
    draw:
      - charger
      - cleaned_area
      - goto_path
      - ignored_obstacles
      - ignored_obstacles_with_photo
      - no_go_zones
      - no_mopping_zones
      - obstacles
      - obstacles_with_photo
      - path
      - predicted_path
      - vacuum_position
      - virtual_walls
      - zones
```

### Additional information

![screenshot_2023-06-24 15_03_32](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/75278121/689ba1a5-d11d-4c75-a4df-f028d5b27a4b)
