### ISSUE TITLE
UTF8 Encoding on room names

### ISSUE THREAD

**Issue by r3pek** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#448]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

When the Room's name contains some special character (ç|á|ó|etc), the text is encoded using URL Encoding (and UTF-8), so for example, the word "Gonçalo" is shown on the map as "Gon%C3%A7alo". 

### What version of an integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

viomi.vacuum.s9

### What version of Home Assistant do you use?

2023.6.3

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
- platform: xiaomi_cloud_map_extractor
  host: 10.0.1.100
  token: !secret xiaomi_vacuum_token
  username: !secret xiaomi_cloud_username
  password: !secret xiaomi_cloud_password
  draw: ["all"]
  country: de
  name: "Viomi S9 Map"
  attributes:
    - calibration_points
    - charger
    - cleaned_rooms
    - country
    - goto_path
    - goto_predicted_path
    - goto
    - ignored_obstacles_with_photo
    - ignored_obstacles
    - image
    - is_empty
    - map_name
    - no_go_areas
    - no_mopping_areas
    - obstacles_with_photo
    - obstacles
    - path
    - room_numbers
    - rooms
    - vacuum_position
    - vacuum_room_name
    - vacuum_room
    - walls
    - zones
```

**Comment by PiotrMachowski** [comment]
The source of the problem is that the only available font doesn't support special characters.
I suggest using the following configuration:
```yaml
- platform: xiaomi_cloud_map_extractor
  host: 10.0.1.100
  token: !secret xiaomi_vacuum_token
  username: !secret xiaomi_cloud_username
  password: !secret xiaomi_cloud_password
  draw:
    - charger
    - cleaned_area
    - goto_path
    - ignored_obstacles_with_photo
    - ignored_obstacles
    - no_go_zones
    - no_mopping_zones
    - obstacles_with_photo
    - obstacles
    - path
    - predicted_path
    - vacuum_position
    - virtual_walls
    - zones
  country: de
  name: "Viomi S9 Map"
  attributes:
    - calibration_points
```
