### ISSUE TITLE
Configuration Issue with Xiaomi Vacuum 1S

### ISSUE THREAD

**Issue by alexlopezcifuentes** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#45]
Hi!

I'm trying to use the custom integration with a Xiaomi Vacuum 1S. I've installed it with HACS and my configuration in `config.yaml` is as follows:

```
camera:
   - platform: xiaomi_cloud_map_extractor
     host: !secret xiaomi_vacuum_host
     token: !secret xiaomi_vacuum_token
     username: !secret xiaomi_cloud_username
     password: !secret xiaomi_cloud_password
     country: "cn"
```

And the information in secrets is as:
```
xiaomi_vacuum_host: 192.168.1.41
xiaomi_vacuum_token: "xxxxxxxxxxxxxxxxx"
xiaomi_cloud_username: "xxxxx@gmail.com"
xiaomi_cloud_password: "xxx"
```

However, the integration is not correctly loaded and the error in Home Assistant Log is not very clarifying. I assume that it is a problem with my configuration but I can not find the error...

I used your script to obtain the token and the vacuum is correctly integrated into Home Assistant with the `xiaomi_miio` Official integration so I assume those values are correct.

Any help would be appreciated.

Thanks!
