### ISSUE TITLE
 Unable to log in, check credentials 

### ISSUE THREAD

**Issue by feu77** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#453]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

After configuration and reboot, I get the following error in the logs:
` Unable to log in, check credentials `

Entity is showing a blue pic with a center text: failed to login

HA and device in the same network, map is showing up in the Mi home app. Device is working with the same credentials as used for the Xiaomi integration.

### What version of an integration has described problem?

v2.2.0

### What vacuum model do you have problems with?

roborock.vacuum.s5e

### What version of Home Assistant do you use?

2023.7.1

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.2.2
    token: {token as provided by extractor}
    username: {user as used to extract token}
    password: {password as used to extract token}
    draw: ['all']
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:270
Integration: xiaomi_cloud_map_extractor ([documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), [issues](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues))
First occurred: 14:14:45 (2 occurrences)
Last logged: 14:25:03
Unable to log in, check credentials
```
