### ISSUE TITLE
map_transformation not working anymore ? 

### ISSUE THREAD

**Issue by Tontze** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#458]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

i have map_transformation, scale 2. It does not seem to be working anymore ? No matter what number it is, scale is not changed ?
 

### What version of an integration has described problem?

v2.2.1

### What vacuum model do you have problems with?

viomi.vacuum.v8

### What version of Home Assistant do you use?

2023.8.1

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
# Robotvacuum configurations
camera:
   - platform: xiaomi_cloud_map_extractor
    name: Viomi
    host: x.x.x.x
    token: !secret viomi_token
    username: !secret xiaomi_username
    password: !secret xiaomi_password
    country: "de"
    draw: ["all"]
    attributes:
      - calibration_points
      - rooms
    map_transformation:
      scale: 2
    scan_interval:
      seconds: 20
    colors:
      color_map_outside: [0, 0, 0, 0]
      color_path: [66, 66, 66]
```
