### ISSUE TITLE
Blueprint update_map_extractor.yaml - Syntax

### ISSUE THREAD

**Issue by mguyard** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#463]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

When using VSCODE module and editing update_map_extractor.yaml blueprint, we have an error about input part :

![CleanShot 2023-08-24 at 12 09 27](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/5262395/a7dddb96-5909-4977-a9f8-7bb1ba618a74)

Right syntax following doc is now :

![CleanShot 2023-08-24 at 12 10 04](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/5262395/53521475-70b1-490f-ba9b-5241f1043aee)

### What version of an integration has described problem?

v2.2.1

### What was the last working version of an integration?

v2.2.1

### What vacuum model do you have problems with?

roborock_vacuum_s5

### What version of Home Assistant do you use?

2023.8.2

### What type of installation are you running?

Home Assistant Supervised

### Camera's configuration

```yaml
- platform: xiaomi_cloud_map_extractor
  host: !secret xiaomi_vacuum_host #secret à créer ou remplacer par l’ip de l’aspirateur
  token: !secret xiaomi_vacuum_token #secret à créer ou remplacer par le token de l’aspirateur
  username: !secret xiaomi_cloud_username #secret à créer ou remplacer par le mail du compte mi-home
  password: !secret xiaomi_cloud_password #secret à créer ou remplacer par le mot de passe du compte mi-home
  name: "Aspirateur Salon" #nommer votre aspirateur
  scan_interval: 30
  draw: ["all"]
  map_transformation:
    scale: 2 #ratio de l’image à tester en fonction de la taille de la carte souhaité
    trim:
      top: 25
      bottom: 25
      left: 20
      right: 20
  attributes:
    - calibration_points
  auto_update: true
```
