### ISSUE TITLE
Blueprint disable_vacuum_camera_update_when_docked.yaml - add "Idle" + "Pause"

### ISSUE THREAD

**Issue by c11umw** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#468]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

The blueprint to disable the camera (to prevent rate limiting) has 3 states.

![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/48920056/5c32a4ef-7f08-409f-b9e9-b8e7c900cf44)

Request to add the following to further reduce the chance of rate limiting (idle + paused)):
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/48920056/3d674cfc-2464-4fb3-ad1f-f78825d7499d)

Reasoning:
1) Pause: Some people have automations to pause the vacuum when they enter the same room/space it's currently cleaning and resume when vacant.
2) Idle: I have my Roborock on a charging cycle rather than leave it powered on all the time. When it's on it's on a discharge cycle it eventually goes to "sleep" and shows as idle, not docked.

Blueprint location: 
`/config/blueprints/automation/PiotrMachowski/disable_vacuum_camera_update_when_docked.yaml`

My install:
```
Home Assistant 2023.9.2
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest
```

### What version of an integration has described problem?

v2.2.1

### What vacuum model do you have problems with?

roborock.vacuum.s4

### What version of Home Assistant do you use?

2023.9.2

### What type of installation are you running?

Home Assistant Supervised

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: de
    scan_interval: 30
    auto_update: false
    draw: ["all"]
    attributes:
      - calibration_points
```
