### ISSUE TITLE
Platform error

### ISSUE THREAD

**Issue by Sakynet** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#473]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hi,

I am trying to set up Roborock S50 to HA, and I am getting this error:

"Configuration invalid!
Platform error camera.xiaomi_cloud_map_extractor - Integration 'xiaomi_cloud_map_extractor' not found."

In the configuration file, I input the data needed:
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    attributes:
      - calibration_points
```
(with correct info in secret.yaml)

Please, help me to understand what i wrong in my configuration.

Thank you for your development.

### What version of an integration has described problem?

v2.2.1

### What vacuum model do you have problems with?

roborock.vacuum.s5

### What version of Home Assistant do you use?

Supervisor 2023.10.0

### What type of installation are you running?

Home Assistant Supervised

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
Platform error camera.xiaomi_cloud_map_extractor - Integration 'xiaomi_cloud_map_extractor' not found.
```
