### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Wang1998** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#474]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Found an unsupported model 'roborock.vacuum.a69' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

请求支持一下石头G20,非常感谢

### What version of an integration has described problem?

HA 2023.8+ compatibility

### What vacuum model do you have problems with?

roborock.vacuum.a69

### What version of Home Assistant do you use?

Operating System 10.5

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 你的扫地机ip
    token: 你的扫地机token
    username: 你的米家账号
    password: 你的米家密码
    draw: ['all']
    attributes:
      - calibration_points 
      - rooms
```
