### ISSUE TITLE
Vacuum cleaner v1. Erorr camera and dont started clean

### ISSUE THREAD

**Issue by arbuzovan** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#476]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Some thing broken. Vacuum cleaner not started clean and in control panel card error: Incorrect calibration, check your configuration.
On map image wroten: failed to retrieve device

### What version of an integration has described problem?

2.2.1

### What vacuum model do you have problems with?

vacuum.rockrobo_vacuum_v1

### What version of Home Assistant do you use?

Home Assistant 2023.9.3

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
type: custom:xiaomi-vacuum-map-card
title: Кракен
entity: vacuum.kraken_dom
vacuum_platform: default
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
map_modes:
  - template: vacuum_clean_zone
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.2.108
    token: 5048724f506861765641765072335537
    username: arbuzovan@yandex.ru
    password: cEiabh?9
    draw:
      - all
    attributes:
      - calibration_points
map_locked: false
two_finger_pan: false
```

### Errors shown in the HA logs (if applicable)

```shell
Logger: miio.miioprotocol
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:320
Integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 16:16:01 (84 occurrences)
Last logged: 16:45:46

Got error when receiving: timed out
```
