### ISSUE TITLE
Generate room error

### ISSUE THREAD

**Issue by lmanik** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#479]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

After pressing the "Generate Rooms Config" button, no rooms are generated. The map contains only the color layout of the rooms, the last vacuum cleaner path (enabled from the xiaomi app) and the current position.

In the log I found this message.

### What version of an integration has described problem?

v2.2.2

### What vacuum model do you have problems with?

roborock.vacuum.s5e

### What version of Home Assistant do you use?

Home Assistant 2023.10.3

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 
    token: 
    username: 
    password: 
    draw: ['charger', 'cleaned_area', 'goto_path', 'vacuum_position', 'path', 'predicted_path', 'room_names']
    attributes:
      - calibration_points
      - rooms
      - vacuum_room_name
      - vacuum_position
      - cleaned_rooms
    scan_interval:
      seconds: 15
```

### Errors shown in the HA logs (if applicable)

```shell
Logger: frontend.js.latest.202310050
Source: components/system_log/__init__.py:300
First occurred: 22:44:58 (1 occurrences)
Last logged: 22:44:58

Uncaught error from Chrome 118.0.0.0 on Mac OS 10.15.7 TypeError: Cannot add property 2, object is not extensible qs._handleRoomConfig (/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:261:969) wc._handleRoomsConfigGet (/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:1222:5028) qs._generateRoomsConfig (/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:163:1144) qs.<anonymous> (/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:250:42) ee.handleEvent (/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js:17:7351)
```
