### ISSUE TITLE
Help with integration

### ISSUE THREAD

**Issue by codeoutin** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#48]
Hey!
I'm cant get the cloud map extractor with the live map to work. As i'm using custom cards and all that the first time - it is really hard for newbies to know what to do and what to configure where.

What i've did is to install both the cloud map extractor and the Lovelace Xiaomi Vacuum Map card using HACS. Now how do i configure this step by step? I've managed to extract my roborock s5 max's token and ip from the iOS backup.

I've added this to my configuration.yaml:
```
vacuum:
  - platform: xiaomi_miio
    host: !secret 10.0.0.105 
    token: !secret my_token

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret 10.0.0.105
    token: !secret my_token
    username: !secret my_mi_username
    password: !secret my_mi_password
    draw: ['all']
    attributes:
      - calibration_points    
```

and i created a ui-lovelace.yaml and added this:
```
resources:
  - url: /local/custom_lovelace/xiaomi_vacuum_map_card/xiaomi-vacuum-map-card.js
    type: module
```

How do i get a working card now? What do i need to add to make it function?
Thank you so much! <3
