### ISSUE TITLE
Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds

### ISSUE THREAD

**Issue by perseus177** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#480]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds - in log file

### What version of an integration has described problem?

v2.2.1

### What vacuum model do you have problems with?

roborock.vacuum.s5

### What version of Home Assistant do you use?

2023.10.3

### What type of installation are you running?

Home Assistant Supervised

### Camera's configuration

```yaml
""
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.0.149
    token: !secret vacuum_tokken
    username: !secret vacuum_username
    password: !secret vacuum_passwd
    country: "cn"
    draw: ['all']
    attributes:
      - calibration_points      
 ""
```

### Errors shown in the HA logs (if applicable)

```shell
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:961
First occurred: 10:52:45 (1 occurrences)
Last logged: 10:52:45

Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
```
