### ISSUE TITLE
Zones are misplaced on trimming the map

### ISSUE THREAD

**Issue by angadsingh** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#49]
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.#$
    token: @#$#$!#$
    username: !@#$!@#$@!
    password: #!@$!@#$!
    country: "us"
    name: "Roborock S5 Max Camera"
    draw: ['all']
    attributes:
      - calibration_points
    map_transformation:
      trim:
        top: 15
        bottom: 15
        left: 15
        right: 15
    colors:
      color_robo: [255, 255, 255]
      color_charger: [214, 186, 122]
      color_map_outside: [255, 255, 255]
      color_path: [255, 255, 255]
      color_goto_path: [250, 241, 117]
    room_colors:
      16: [245, 176, 65]
      17: [88, 214, 141]
      18: [217, 136, 128]
      19: [214, 178, 209]
      20: [72, 201, 176]
      21: [52, 152, 219]
      22: [133, 193, 233]
      24: [240, 178, 122]
      25: [205, 97, 85]
```

i just realized this isn't really a `xiaomi-cloud-map-extractor` issue but rather a [lovelace-xiaomi-vacuum-map-card](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card) issue but its kind of related to both working together so creating the issue here since the fix can actually be done in this integration - i got the zones from the room definitions reported by this integration as an attribute. maybe it could offset the zones by the trimming percentages and report them, so one could copy paste that into the `lovelace-xiaomi-vacuum-map-card` definition.

when the map is trimmed in `xiaomi-cloud-map-extractor` (like above) then the room coordinates reported do not honor the trims. so in case you copy them over to a frontend integration like `lovelace-xiaomi-vacuum-map-card` as your defined zones, they will appear misplaced like this:

![04694648-7BC9-48BB-9848-778CCE01B09C](https://user-images.githubusercontent.com/1623026/100733499-4b1a8c80-33f4-11eb-84e9-13e6c37a9412.jpg)
