### ISSUE TITLE
Warning after upgrading to Core 2024.1.0

### ISSUE THREAD

**Issue by Doktor2003** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#503]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

After upgrading НА to Core 2024.1.0, the following warning appeared in the server log:
Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF: 1>

### What version of an integration has described problem?

2.2.1

### What was the last working version of an integration?

2.2.1

### What vacuum model do you have problems with?

xiaomi mijia 1s

### What version of Home Assistant do you use?

Core 2024.1.0

### What type of installation are you running?

Home Assistant Supervised

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF: 1>
```
