### ISSUE TITLE
SUPPORT_ON_OFF is deprecated

### ISSUE THREAD

**Issue by LennardPlay** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#505]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I don't understand the error message completely, but it says, that I should report this error message:

"SUPPORT_ON_OFF was used from xiaomi_cloud_map_extractor, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues"

### What version of an integration has described problem?

v2.2.1

### What vacuum model do you have problems with?

roborock s5

### What version of Home Assistant do you use?

2024.1.2

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
- platform: xiaomi_cloud_map_extractor
  host: 192.168.0.213
  token: XXXXXXXXXXX
  username: XXXXXXXXXXX
  password: XXXXXXXXXXX
  name: Staubsauger Karte
  draw: ['all']
  attributes:
    - calibration_points
    - rooms
  map_transformation:
      scale: 3
      trim:
        top: 20
        bottom: 30
        left: 23
        right: 20
  sizes:
    charger_radius: 8
    vacuum_radius: 10
  colors:
#    color_map_inside: [32, 115, 185]
    color_map_outside: [28,28,28]
    color_map_wall: [44, 44, 44]
    color_path: [225, 225, 225]
    color_robo: [225, 225, 225]
```

### Errors shown in the HA logs (if applicable)

```shell
"SUPPORT_ON_OFF was used from xiaomi_cloud_map_extractor, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues"
```
