### ISSUE TITLE
Rotate by Map ID

### ISSUE THREAD

**Issue by cataseven** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#506]
### Description

At present, rotate config is applied all saved maps. I have 4 maps but I want to rotate only 1 of them

### Solution

Is it possible to config like?;

```
    map_transformation:
      map_id: 123456789
        rotate: 90
      map_id: 456456456
        rotate: 180
```

**Comment by cataseven** [comment]
Find an alternative:

Use card_mod on your vacuum map card

```
card_mod:
  style: I
    #map-image {
       transform: rotate(270deg);
     }
```

```
                type: custom:xiaomi-vacuum-map-card
                entity: vacuum.viomi_se
                preset_name: Downstairs
                map_source:
                  camera: camera.xiaomi_cloud_map_extractor
                  crop:
                    top: 435
                    bottom: 280
                    left: 490
                    right: 160
                calibration_source:
                  camera: true
                clean_selection_on_start: true
                map_locked: true
                two_finger_pan: true
                icons: []
                tiles: []
                map_modes:
                  - selection_type: ROOM
                    name: Room Cleaning
                    icon: mdi:floor-plan
                    max_selections: 5
                    repeats_type: NONE
                    predefined_selections:
                      - id: 10
                        label:
                          text: Kitchen
                          x: 10.3
                          'y': -0.9
                        icon:
                          name: mdi:water-plus
                          x: 10.3
                          'y': -1.5
                      - id: 11
                        label:
                          text: Living Room
                          x: 3.7
                          'y': -2.1
                        icon:
                          name: mdi:water-plus
                          x: 3.7
                          'y': -2.7
                      - id: 12
                        label:
                          text: Hallway
                          x: 9.7
                          'y': -3.7
                        icon:
                          name: mdi:water-plus
                          x: 9.7
                          'y': -4.2
                      - id: 13
                        label:
                          text: Guest Room
                          x: 12.1
                          'y': -5.8
                        icon:
                          name: mdi:water-plus
                          x: 12.1
                          'y': -6.3
                      - id: 15
                        label:
                          text: Staircase
                          x: 8.3
                          'y': -5.2
                        icon:
                          name: mdi:water-plus
                          x: 8.3
                          'y': -5.7
                    service_call_schema:
                      service: xiaomi_miot.call_action
                      service_data:
                        entity_id: vacuum.viomi_v13
                        siid: 4
                        aiid: 15
                        params:
                          - piid: 21
                            value: 0
                          - piid: 22
                            value: 1
                          - piid: 20
                            value: '[[selection_unwrapped]]'
                        force_params: true
                  - template: vacuum_clean_zone
                    name: Zone Cleaning
                  - template: vacuum_clean_point
                    name: Point Cleaning
                vacuum_platform: marotoweb/viomise
                card_mod:
                  style: |
                    ha-card {
                      --map-card-room-label-color: rgb(255, 255, 255);
                      --map-card-room-label-color-selected: rgb(255, 255, 255);
                      --map-card-room-icon-wrapper-size: 18px;
                      --map-card-room-icon-size: 14px;
                    }

                    #map-image {
                      transform: rotate(270deg);
                    }
```
