### ISSUE TITLE
Add two cameras on configuration.yaml

### ISSUE THREAD

**Issue by maorgeter** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#508]
### Checklist

- [x] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Hi, I have two Xiaomi robots, when im trying to add camera: twice on configuration .yaml im getting warning:
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/96653678/523d659a-9698-4736-a6c4-6cbc7db5ee07)

How can I define two different "cameras"?

### What version of an integration has described problem?

v2.2.1

### What was the last working version of an integration?

v2.2.1

### What vacuum model do you have problems with?

roborock s5

### What version of Home Assistant do you use?

2024.1.5

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: cc
    token: cc
    username: cc@gmail.com
    password: ccc
    name: ccc
    draw: ['all']
    attributes:
      - calibration_points
```

**Comment by PiotrMachowski** [comment]
You have to merge them and provide names to both of them:
```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    name: camera 1
    host: cc
    token: cc
    username: cc@gmail.com
    password: ccc
    name: ccc
    draw: ['all']
    attributes:
      - calibration_points
  - platform: xiaomi_cloud_map_extractor
    name: camera 2
    host: cc
    token: cc
    username: cc@gmail.com
    password: ccc
    name: ccc
    draw: ['all']
    attributes:
      - calibration_points
```
