### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by adonixis** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#513]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/1766863/0bd9a8e7-2c93-4485-83cd-a3a4148413e3)
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/1766863/ce2c6b35-56b6-4b75-b8d6-50cf348bc4fc)
I'm getting this error with my vacuum cleaner Xiaomi Robot Vacuum S10 https://home.miot-spec.com/s/ijai.vacuum.v17

### What version of an integration has described problem?

v2.2.1

### What vacuum model do you have problems with?

ijai.vacuum.v17

### What version of Home Assistant do you use?

Core 2024.2.2

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
    store_map_raw: true
    store_map_image: true
    store_map_path: "/tmp"
```

### Errors shown in the HA logs (if applicable)

```shell
Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
Got error when receiving: timed out
```
