### ISSUE TITLE
Error: Failed to retreive map from vacuum. Was working flawlesly, stopped working without any updates

### ISSUE THREAD

**Issue by vajnorcan** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#516]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I've set it up this morning, was working all day, happy, sent the paypal as a token of appreciation. However, it's unable to retreive the map few hours later without doing any updates on the system. I've double checked the IP (which is static) of the vacuum, token, and passwords, however I'm unable to get the map rendered. It doesn't even show up when the vacuum is running (other controls are working fine)

**Update**
Well, it seems like I'm unable to see the map in the mi home app neither, this never happened. I wonder if this integration could've deleted it / corrupted it?

### What version of an integration has described problem?

v2.2.1

### What was the last working version of an integration?

v2.2.1

### What vacuum model do you have problems with?

roborock.vacuum.s5

### What version of Home Assistant do you use?

2024.2.5

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.....46
    token: 6----6
    username: m----@gmail.com
    password: V----3
    country: sg
    draw: ["all"]
    attributes:
      - calibration_points
      - vacuum_position
```

### Errors shown in the HA logs (if applicable)

```shell
-- I don't think this is related as it's just a warning. not sure if there are any other log entries elsewhere

2024-03-06 17:44:03.786 WARNING (MainThread) [homeassistant.helpers.entity] Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF: 1>, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```
