### ISSUE TITLE
Deprecated supported features values

### ISSUE THREAD

**Issue by z-master42** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#519]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Entity camera.roborock_s5 (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF: 1>
See https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

### What version of an integration has described problem?

2.2.1

### What was the last working version of an integration?

2.2.1

### What vacuum model do you have problems with?

roborock.vacuum.s5

### What version of Home Assistant do you use?

2024.3.0

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
- platform: xiaomi_cloud_map_extractor
    scan_interval: 10
    host: 192.168.42.24
    token: zzz
    username: xxx
    password: yyy
    country: "de"
    name: "Roborock S5"
    map_transformation:
      scale: 2
      trim:
        top: 19
        bottom: 17
        left: 18
        right: 19
    colors:
      color_path: [255, 255, 255]
      color_map_outside: [0, 0, 0, 0]
    room_colors:
      1: [0x91, 0xc8, 0xff]
      2: [0xf5, 0x8e, 0x6f]
      3: [0xf5, 0x8e, 0x6f]
      16: [0xfc, 0xd4, 0x51]
      17: [0x70, 0xcb, 0xde]
    draw: ['all']
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
Entity camera.roborock_s5 (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF: 1>
See https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```
