### ISSUE TITLE
Failed to retrieve device

### ISSUE THREAD

**Issue by txitxo0** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#524]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I was experimenting a non-map in both, Xiaomi cloud map extractor and mi home app. Following this thread: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/422 I could get the mi home map working. But, in Home Assistant side, I can not get the map working again as in old times. In the map a "failed to retrieve device" label appears

### What version of an integration has described problem?

V2.2.1

### What was the last working version of an integration?

Don't know

### What vacuum model do you have problems with?

Roborock S7

### What version of Home Assistant do you use?

2024.3.3

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
- platform: xiaomi_cloud_map_extractor
  host: !secret xiaomi_vacuum_host
  token: !secret xiaomi_vacuum_token
  username: !secret xiaomi_cloud_username
  password: !secret xiaomi_cloud_password
  draw: ['all']
  country: cn
  auto_update: false
  attributes:
  - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
Failed to retrieve model
```

### Additional information

I found similar topics, but for different models and behaviours (shared houses, new models...) but this was working great time ago
