### ISSUE TITLE
Record details (WARNING)

### ISSUE THREAD

**Issue by jurdikla** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#525]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

SUPPORT_ON_OFF was used from xiaomi_cloud_map_extractor, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues

### What version of an integration has described problem?

v2.2.1

### What vacuum model do you have problems with?

Mi Robot Vacuum-Mop

### What version of Home Assistant do you use?

Core - 2024.3.3

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
   - platform: xiaomi_cloud_map_extractor
     host: 192.168.1.166
     token: ************************
     username: *************
     password: ***********
     draw: ['all']
     attributes:
       - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
Logger: homeassistant.components.camera
Source: helpers/deprecation.py:205
Integration: Camera (documentation, issues)
First Occurred: 09:39:42 (2 occurrences)
Last logged in: 09:39:42

SUPPORT_ON_OFF was used from xiaomi_cloud_map_extractor, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues
```
