### ISSUE TITLE
Xiaomi Vacuum E5

### ISSUE THREAD

**Issue by jramirezcolombia** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#533]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

My problem is that when performing the integration, a login error and invalid calibration appear, how can I solve it? thank you

### What version of an integration has described problem?

v2.2.1

### What vacuum model do you have problems with?

Xiaomi E5

### What version of Home Assistant do you use?

2024.6.0

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.XXX.XXX
    token: XXXXXXXXXXXXXXXXX
    username: xxxxxxx@xxxxx.com
    password: xxxxxxxxxxxx
    country: us
    draw: ['all']
    attributes:
      - calibration_points
```
