### ISSUE TITLE
Deprecated supported features values which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by Ursli71** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#537]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

besides the already reported 'SUPPORT_ON_OFF' needed upgrade for HA Core 2025.1 I have another log warning as per below:
Logger: homeassistant.helpers.entity
Quelle: helpers/entity.py:1628
Erstmals aufgetreten: 15:01:25 (1 Vorkommnisse)
Zuletzt protokolliert: 15:01:25

Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF: 1>, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

Thanks for keeping this great integration alive!
Cheers Urs

### What version of an integration has described problem?

v2.2.1

### What was the last working version of an integration?

still working 

### What vacuum model do you have problems with?

roborock_s7_maxv

### What version of Home Assistant do you use?

core 2024.6.4

### What type of installation are you running?

Home Assistant Supervised

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    store_map_raw: true
    draw: ['all']
    attributes:
      - calibration_points
      - rooms
    store_map_image: true
    store_map_path: "/tmp"
    scan_interval: 8
```

### Errors shown in the HA logs (if applicable)

```shell
n/a
```

### Additional information

n/a
