### ISSUE TITLE
Actual home scheme and vacuum are mispointed on map

### ISSUE THREAD

**Issue by semyonchetvertnyh** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#539]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

There is a shift between my scheme of apartment and actual vacuum (and `no_go_area` red box as well). I guess something is wrong with my calibration points, but I have no idea how to fix it.

Just compare MiHome app and map in HA to see the issue.

**Mi Home**

![mihome](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/2598761/e89e4096-c59e-4d32-8718-077402a06f34)

**Home Assistant**

![homeassistant](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/2598761/dd2e740d-3622-455d-94e4-0f7e4673ef0a)

### What version of an integration has described problem?

 v2.2.1

### What vacuum model do you have problems with?

viomi.vacuum.v8

### What version of Home Assistant do you use?

2024.6.0

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
```
