### ISSUE TITLE
Error displaying the map

### ISSUE THREAD

**Issue by GeorgePatsias** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#540]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I have problem showing the map. Previously was working ok but a day after having problems. 
Check images attached.
Also removed and cleared the intergrations and added it again.
The configurations - creds are ok.

### What version of an integration has described problem?

v2.2.1

### What vacuum model do you have problems with?

vacuum.viomi_v8_abb6_robot_cleaner

### What version of Home Assistant do you use?

core-2024.6.4

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: "de"
    draw: ["all"]
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell
This error originated from a custom integration.

Logger: custom_components.xiaomi_cloud_map_extractor.camera
Source: custom_components/xiaomi_cloud_map_extractor/camera.py:356
integration: xiaomi_cloud_map_extractor (documentation, issues)
First occurred: 00:09:51 (103 occurrences)
Last logged: 00:18:20

Unable to retrieve map data
```

### Additional information

![Screenshot 2024-07-03 001424](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/7280295/2f829975-521e-4c1f-9670-95601b76ae50)
![Screenshot 2024-07-03 001449](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/7280295/e47b88db-8f3c-422c-86c4-b2bbf1b5ea83)
![Screenshot 2024-07-03 001516](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/assets/7280295/83bc7e62-ae3f-4273-89d0-0669bddc690d)
