### ISSUE TITLE
Failed to retrieve map from vacuum

### ISSUE THREAD

**Issue by hugomickael** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#541]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

The map doesn't appear, only the message "Failed to retrieve map from vacuum" and "Invalid calibration, please check your configuration".

Here is the card configuration:

type: custom:xiaomi-vacuum-map-card
title: Xiaomi Vacuum Map Card
preset_name: Live map
entity: vacuum.ramiro
map_source:
  camera: camera.my_camera
calibration_source:
  camera: true
vacuum_platform: default

### What version of an integration has described problem?

v2.2.1

### What vacuum model do you have problems with?

rockrobo.vacuum.v1

### What version of Home Assistant do you use?

2024.7.2

### What type of installation are you running?

Home Assistant Container

### Camera's configuration

```yaml
- platform: xiaomi_cloud_map_extractor
  host: 192.168.1.91
  token: !secret token
  username: !secret email
  password: !secret xiaomi_password
  name: "My Camera"
  country: "de"
  draw: ["all"]
  attributes:
    - calibration_points
```

**Comment by Smarthome-Creator** [comment]
I have exactly the same problem.
Unfortunately, I do not understand the problem and do not know how it comes about. I have set up everything as described in the documentation, but unfortunately it doesn't work.

`- platform: xiaomi_cloud_map_extractor
  name: Wall-E Floor plan
  host: XXX.XXX.XXX.XXX
  token: !secret 
  username: !secret 
  password: !secret 
  draw: ['all']
  attributes:
    - calibration_points`

It only worked once when I set it up, since then I always get this message.
What I find very strange is when I “turn on” the HA entity, I can no longer load the map in the original Xiaomi App. (“Network too slow”)

If I switch the entity “off” again in HA, the map can be loaded again in the app. I don't know what's going on.

**Comment by neiker** [comment]
Same here, it worked perfectly and without changing anything it started to fail.
Just in case I checked that the device's IP is still the same and it hasn't changed. Same with the token

**Comment by neiker** [comment]
It looks like Xiaomi bans you if you perform many requests too often. I added the blueprint mentioned [here](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor?tab=readme-ov-file#updates) to disable the polling when the vacuum is docked. Now I guess I should wait until Xiaomi decides to lift the ban

**Comment by hugomickael** [comment]
Ok thanks, I applied the blueprint, let's see.

**Comment by vchatela** [comment]
> Ok thanks, I applied the blueprint, let's see.

Any updates on your unban ? I am ban too...

**Comment by TrasteCC** [comment]
> Ok thanks, I applied the blueprint, let's see.

Hey! I'm struggling with the same problem. Just applied the blueprint. 

Did you get your ban lifted? How long did it take?

Thanks

**Comment by vchatela** [comment]
Myself it resolved 2 days after added the removal of refresh and local storage.
I had contacted roborock support at same time but there were useless in solving this.

**Comment by TrasteCC** [comment]
> Myself it resolved 2 days after added the removal of refresh and local storage. I had contacted roborock support at same time but there were useless in solving this.

Thanks! I'll wait :-)

**Comment by neiker** [comment]
In my case, they lift the ban after 24 hours. But they don't disclose the duration or if it's longer in case of a repeat "offense"

**Comment by Smandurlo** [comment]
I have the same problem, but I have my camera off when it is docked since the very first time I used this custom component, so this is not the problem. Any idea?

**Comment by obsthaendler91** [comment]
i have the same issue

**Comment by obsthaendler91** [comment]
in my case:
configuration.yaml edit  "auto_update: true" to false
i use the blueprint: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/blob/master/blueprints/automation/disable_vacuum_camera_update_when_docked.yaml

this works for me.

**Comment by ireun** [comment]
I use `PiotrMachowski/update_map_extractor.yaml` but it seems to work only when docked.. Otherwise the map does not update at all.. Xiaomi Vacuum here, `rockrobo.vacuum.v1` 

Blueprint settings:
```
alias: Update Map Extractor camera 
description: ""
use_blueprint:
  path: PiotrMachowski/update_map_extractor.yaml
  input:
    vacuum: vacuum.rockrobo_v1_a259_robot_cleaner
    camera: camera.gorgie
    mode_to_handle: two_intervals
    interval_docked: 3600
```

Camera:
```
camera:
  - platform: xiaomi_cloud_map_extractor
    name: Gorgie
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token_gorgie
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: "de"
    draw: ["all"]
    auto_update: false
    attributes:
      - calibration_points
 ```
