### ISSUE TITLE
Scale limit?

### ISSUE THREAD

**Issue by firstcolle** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#565]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

with scale = 20 HA goes into a boot loop. maybe there some sort of limit to this value?

### What version of an integration has described problem?

2.2.1

### What vacuum model do you have problems with?

xiaomi mi 1s

### What version of Home Assistant do you use?

2024.11.3

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
# camera per mappa aspirapolvere xiaomi
- platform: xiaomi_cloud_map_extractor
  name: mappa_box
  host: 192.168.10.69
  token: 58716f56415472614d6f516b71326c52
  username: !secret username
  password: !secret password
  draw: ["all"]
  attributes:
    - calibration_points
  map_transformation:
    scale: 20
    rotate: 0
```
