### ISSUE TITLE
Cloud Extractor unable to retrieve data

### ISSUE THREAD

**Issue by Melaxx19** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#583]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Recently I've noticed that cloud extractor can't fetch map data from xiaomi cloud. I know it was working before updating to newest version but now it's not even if I rollback to previous version. Pretty much just wanted to check if anyone has the same problem or problem is only on my end.

### What version of an integration has described problem?

2.2.3

### What vacuum model do you have problems with?

Viomi.vacuum.v8

### What version of Home Assistant do you use?

2025.1.0

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.89.8
    token: token
    username: email
    password: password
    country: de
    colors:
      color_map_inside: [32, 115, 185]
      color_map_outside: [19, 87, 148]
      color_map_wall: [100, 196, 254]
      color_map_wall_v2: [93, 109, 126]
      color_grey_wall: [93, 109, 126]
      color_ignored_obstacle: [0, 0, 0, 127]
      color_ignored_obstacle_with_photo: [0, 0, 0, 127]
      color_obstacle: [0, 0, 0, 127]
      color_obstacle_with_photo: [0, 0, 0, 127]
      color_path: [147, 194, 238]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_cleaned_area: [127, 127, 127, 127]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_new_discovered_area: [64, 64, 64]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_robo: [75, 235, 149]
      color_room_names: [0, 0, 0]
      color_unknown: [0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
    room_colors:
      10: [240, 178, 122]
      11: [133, 193, 233]
      12: [217, 136, 128]
      13: [52, 152, 219]
      14: [205, 97, 85]
      15: [243, 156, 18]
      16: [88, 214, 141]
      17: [245, 176, 65]
      18: [252, 212, 81]
      19: [72, 201, 176]
      20: [84, 153, 199]
      21: [133, 193, 233]
      22: [245, 176, 65]
      23: [82, 190, 128]
      24: [72, 201, 176]
      25: [165, 105, 18]
    draw:
      - charger
      - cleaned_area
      - goto_path
      - ignored_obstacles
      - ignored_obstacles_with_photo
      - no_go_zones
      - no_mopping_zones
      - obstacles
      - obstacles_with_photo
      - path
      - predicted_path
      - room_names
      - vacuum_position
      - virtual_walls
      - zones
    map_transformation:
      scale: 2
      rotate: 0
      trim:
        top: 48
        bottom: 32
        left: 48
        right: 21
    attributes:
      - calibration_points
      - charger
      - cleaned_rooms
      - country
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - ignored_obstacles
      - obstacles_with_photo
      - ignored_obstacles_with_photo
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - vacuum_room_name
      - walls
      - zones
```

### Errors shown in the HA logs (if applicable)

```shell
2025-01-07 09:08:50.330 DEBUG (SyncWorker_13) [custom_components.xiaomi_cloud_map_extractor.camera] Logging in...
2025-01-07 09:08:50.761 DEBUG (SyncWorker_13) [custom_components.xiaomi_cloud_map_extractor.camera] Logged in
2025-01-07 09:08:50.761 DEBUG (SyncWorker_13) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map from Xiaomi cloud
2025-01-07 09:08:51.024 WARNING (SyncWorker_13) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map data
```
