### ISSUE TITLE
Map extractor is not working after Home Assistant Core update

### ISSUE THREAD

**Issue by tomass0328** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#594]
### Checklist

- [x] I have updated the integration to the latest version available
- [x] I have checked if the problem is already reported

### The problem

after latest Home Assistant Core update (I think so) Map extractor is not working anymore, please see screenshot below.

![Image](https://github.com/user-attachments/assets/06ade467-defe-4b32-a7cd-6bf7e80e4eb4)

### What version of an integration has described problem?

V3.0.0-alpha-1

### What was the last working version of an integration?

V3.0.0-alpha-1

### What vacuum model do you have problems with?

Xiaomi S1

### What version of Home Assistant do you use?

2025.2.3

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: my_ip
    token: my_token
    username: my_username
    password: my_password
    draw: ["all"]
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell

```
