### ISSUE TITLE
XCME not working as yaml configuration of home assitant since core-2025-2-4

### ISSUE THREAD

**Issue by multinet33** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#600]
### Checklist

- [x] I have updated the integration to the latest version available
- [x] I have checked if the problem is already reported

### The problem

Hello 

with my last Home assistant core update (2025.2.4) i get this error : 
`Configuration YAML inutilisée pour l'intégration xiaomi_cloud_map_extractor
Erreur ⸱ Rapporté par Home Assistant Core Integration
Il n'est pas possible de configurer xiaomi_cloud_map_extractor camera en ajoutant platform: xiaomi_cloud_map_extractor à la configuration camera. Veuillez consulter la documentation pour plus d'informations sur la configuration de cette intégration.

Pour résoudre ce problème :

Supprimez les occurrences platform: xiaomi_cloud_map_extractor de la configuration camera : dans votre fichier de configuration YAML.
Redémarrez l'Home Assistant.
Exemple à supprimer :

camera:
  - platform: xiaomi_cloud_map_extractor`

Could you help me ?

Before update it was working without errors

Best
Multinet

### What version of an integration has described problem?

v3.0.0-alpha2

### What was the last working version of an integration?

v3.0.0-alpha2

### What vacuum model do you have problems with?

roborock.vacuum.a51

### What version of Home Assistant do you use?

core-2025-2-4

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
#############################################
##                                         ##
##            Aspi carto S8                ##
##                                         ##
#############################################  
  - platform: xiaomi_cloud_map_extractor
    host: !secret s8_host
    token: !secret s8_token
    username: !secret xiaomi_username
    password: !secret xiaomi_password
    country: de
    name: "Roborock S8"
    draw: ['all']
    scan_interval: 30
    attributes:
      - calibration_points
      - room_numbers
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - rooms
      - vacuum_position
      - vacuum_room
      - walls
      - zones
    sizes:
      charger_radius: 4
      vacuum_radius: 6
    map_transformation:
      scale: 1
      trim:
        top: 23
        bottom: 23
        left: 23
        right: 23
    colors:
      color_path: [255, 255, 255]
      color_robo : [255, 255, 255] 
      color_map_inside: [32, 115, 185]
      color_map_outside: [32, 44, 69]
      color_map_wall: [100, 196, 254]
      color_map_wall_v2: [93, 109, 126]
      color_grey_wall: [93, 109, 126]
      color_goto_path: [0, 255, 0]
      color_predicted_path: [255, 255, 0, 0]
      color_zones: [0xAD, 0xD8, 0xFF, 0x8F]
      color_zones_outline: [0xAD, 0xD8, 0xFF]
      color_virtual_walls: [255, 0, 0]
      color_no_go_zones: [255, 33, 55, 127]
      color_no_go_zones_outline: [255, 0, 0]
      color_no_mop_zones: [163, 130, 211, 127]
      color_no_mop_zones_outline: [163, 130, 211]
      color_charger: [0x66, 0xfe, 0xda, 0x7f]
      color_unknown: [250, 250, 250] #[0, 0, 0]
      color_scan: [0xDF, 0xDF, 0xDF]
```

### Errors shown in the HA logs (if applicable)

```shell

```
