### ISSUE TITLE
Xiaomi Cloud Map extractor blocking integration Home Connect Local

### ISSUE THREAD

**Issue by proasnet** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#609]
### Checklist

- [x] I have updated the integration to the latest version available
- [x] I have checked if the problem is already reported

### The problem

Dear @PiotrMachowski ,
Your integration works fine for me, but now I have found one major problem that your integration for importing Home Connect Local from HACS causes.
When your integration is active in HA, it is not possible to integrate Home Connect Local. I have already informed the integration developer.
https://github.com/chris-mc1/homeconnect_local_hass
Now to be able to control the dishwasher, I had to disable the Xiaomi Cloud Map Extractor integration.

### What version of an integration has described problem?

v2.2.3

### What was the last working version of an integration?

v2.2.3

### What vacuum model do you have problems with?

Mi Robot Vacuum 1S

### What version of Home Assistant do you use?

2025.4.1

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
    colors:
      color_path: [0xFF,0xFF,0xFF]
```

### Errors shown in the HA logs (if applicable)

```shell
homeassistant.requirements.RequirementsNotFound: Requirements for homeconnect_ws not found: ['homeconnect-websocket==1.2.6'].
```

### Additional information

After comment integration in configuration.yaml, Home Connect Local working.
