### ISSUE TITLE
FailedMapDownloadException - No map retrieved

### ISSUE THREAD

**Issue by fablav76** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#610]
### Checklist

- [x] I have updated the integration to the latest version available
- [x] I have checked if the problem is already reported

### The problem

Questo errore ha avuto origine da un'integrazione personalizzata.

Registratore: custom_components.xiaomi_cloud_map_extractor.connector.vacuums.base.vacuum_base
Fonte: custom_components/xiaomi_cloud_map_extractor/connector/vacuums/base/vacuum_base.py:83
Integrazione: Xiaomi Cloud Map Extractor (documentazione, problemi)
Prima occorrenza: 15:44:33 (19 occorrenze)
Ultimo accesso: 15:49:52

FailedMapDownloadException

### What version of an integration has described problem?

2.2.3 & v3.0.0-alpha-1-2-3

### What was the last working version of an integration?

2.2.0 & 2.2.1

### What vacuum model do you have problems with?

viomi.vacuum_v8 (STYJ02YM)

### What version of Home Assistant do you use?

core-2025.4.2 in a VM in Proxmox Virtual Environment

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret viomi_vacuum_v8_token
    username: !secret xiaomi_cloud_user
    password: !secret xiaomi_cloud_pwd
    country: "de"
    draw: ["all"]
    attributes:
      - calibration_points
      - rooms
    map_transformation:
      scale: 3
      rotate: 90
      trim:
        top: 42
        bottom: 22
        left: 46
        right: 29
```

### Errors shown in the HA logs (if applicable)

```shell
Questo errore ha avuto origine da un'integrazione personalizzata.

Registratore: custom_components.xiaomi_cloud_map_extractor.connector.vacuums.base.vacuum_base
Fonte: custom_components/xiaomi_cloud_map_extractor/connector/vacuums/base/vacuum_base.py:83
Integrazione: Xiaomi Cloud Map Extractor (documentazione, problemi)
Prima occorrenza: 15:44:33 (220 occorrenze)
Ultimo accesso: 16:23:22

FailedMapDownloadException
```

### Additional information

I've tried all versions included alpha 1,2 and 3

[home-assistant_2025-04-15T14-43-54.178Z.log](https://github.com/user-attachments/files/19760270/home-assistant_2025-04-15T14-43-54.178Z.log)

In log I got this error now
2025-04-15 15:44:33.695 ERROR (MainThread) [custom_components.xiaomi_cloud_map_extractor.connector.vacuums.base.vacuum_base] FailedMapDownloadException
Previously It was something similar to "error retrieving map".
Some months ago I noticed in log an error about 2FA but my account has no setting about 2FA.
Apparently https://account.xiaomi.com/ seems to work very bad, I've no possibility to change email or reset password.
Server is in Germany.

![Image](https://github.com/user-attachments/assets/0d412104-d987-4039-af29-2c0485b2bbfe)
Integrations Xiaomi Miot Auto & Viomi Vacuum tykarol are working fine.
