### ISSUE TITLE
2fa not effective

### ISSUE THREAD

**Issue by chike-he** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#611]
### Checklist

- [x] I have updated the integration to the latest version available
- [x] I have checked if the problem is already reported

### The problem

I performed 2FA on the same pc running HA with "ok" result, no map; I tried restarting extrator and HA, no map; I changed my xiaomi password, no map; I wonder if there is anything else I can try? or it's simply random chance?
I am alway using xiaomi account in xiaomi miot auto

### What version of an integration has described problem?

2.2.3

### What was the last working version of an integration?

2.2.3

### What vacuum model do you have problems with?

vacuum.roborock_a11_f077_robot_cleaner

### What version of Home Assistant do you use?

2023.11.2

### What type of installation are you running?

Home Assistant Core

### Camera's configuration

```yaml
- platform: xiaomi_cloud_map_extractor
   host: 192.168.1.11
   token: 51306f5a5a4c7a5530636a364c754f66
   username: userID
   password: !secret xiaomi_password
   country: cn
```

### Errors shown in the HA logs (if applicable)

```shell
Additional authentication required
```
