### ISSUE TITLE
Error in config

### ISSUE THREAD

**Issue by bkr1969** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#619]
### Checklist

- [x] I have updated the integration to the latest version available
- [x] I have checked if the problem is already reported

### The problem

I get this error when checking my config.  Doesn't break anything but wanted to report.

```
Platform error 'camera' from integration 'xiaomi_cloud_map_extractor' - cannot import name 'SUPPORT_ON_OFF' from 'homeassistant.components.camera' (/usr/src/homeassistant/homeassistant/components/camera/__init__.py)

```

### What version of an integration has described problem?

Is there a version number?

### What was the last working version of an integration?

Don't know

### What vacuum model do you have problems with?

none

### What version of Home Assistant do you use?

2025.5.2

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 172.16.0.247
    token: 4543356e58654b356c5753586b316f31
    username: xxxxxxxxxxxxx@gmail.com
    password: xxxxxxxxx
    draw: ['all']
    attributes:
      - calibration_points
      - vacuum_position
    map_transformation:
      rotate: 180
    scan_interval: 2
    auto_update: true
```

### Errors shown in the HA logs (if applicable)

```shell

```
