### ISSUE TITLE
two factor auth request for map extractor

### ISSUE THREAD

**Issue by txitxo0** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#622]
### Checklist

- [x] I have updated the integration to the latest version available
- [x] I have checked if the problem is already reported

### The problem

Hello there, 

I have checked for the same problem but they are old and they were not useful for me :s
I had the map extractor and lovelace card working, but now a two factor authentication is requested to load the map. The token is already retrieved and share to the integration.

![Image](https://github.com/user-attachments/assets/41f0a23e-e3e3-4ba9-b22a-c872cd0fa415)

I do not see anything in the logs:

![Image](https://github.com/user-attachments/assets/420c97f6-ff07-489e-913d-24a281ab0374)

I am trying to re get the token. While trying to execute the token extractor, it prompts:
```
Logging in...
Two factor authentication required, please use following url and restart extractor:
```

![Image](https://github.com/user-attachments/assets/f8b7d383-6e1f-44d5-b59e-7df3102bd2d1)

I did it multiple times (and get an ok webpage), but restarting the token extractor didn't work at all

I think is not needed, but here is the lovelace card I am using

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.xiaomi_cloud_map_extractor
calibration_source:
  camera: true
entity: vacuum.roborock_vacuum_a15
vacuum_platform: default
two_finger_pan: true
tiles:
  - tile_id: status
    entity: vacuum.roborock_vacuum_a15
    label: Status
    attribute: status
    icon: mdi:robot-vacuum
    translations:
      starting: Starting
      charger disconnected: Charger disconnected
      idle: Idle
      remote control active: Remote control active
      cleaning: Cleaning
      returning home: Returning home
      manual mode: Manual mode
      charging: Charging
      charging problem: Charging problem
      paused: Paused
      spot cleaning: Spot cleaning
      error: Error
      shutting down: Shutting down
      updating: Updating
      docking: Docking
      going to target: Going to target
      zoned cleaning: Zoned cleaning
      segment cleaning: Segment cleaning
      emptying the bin: Emptying the bin
      charging complete: Charging complete
      device offline: Device offline
  - tile_id: battery_level
    entity: vacuum.roborock_vacuum_a15
    label: Battery
    attribute: battery_level
    icon: mdi:battery-charging-100
    unit: "%"
  - tile_id: fan_speed
    entity: vacuum.roborock_vacuum_a15
    label: Fan speed
    attribute: fan_speed
    icon: mdi:fan
    translations:
      silent: Silent
      standard: Standard
      medium: Medium
      turbo: Turbo
      auto: Auto
      gentle: Gentle
  - tile_id: sensor_dirty_left
    label: Sensors left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: sensor_dirty_time
        entity_id: vacuum.roborock_vacuum_a15
    entity: sensor.roborock_vacuum_a15_sensor_dirty_left
    icon: mdi:eye-outline
    precision: 0
    translations: {}
  - tile_id: filter_left
    label: Filter left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: filter_work_time
        entity_id: vacuum.roborock_vacuum_a15
    entity: sensor.roborock_vacuum_a15_filter_left
    icon: mdi:air-filter
    precision: 0
    translations: {}
  - tile_id: main_brush_left
    label: Main brush left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: main_brush_work_time
        entity_id: vacuum.roborock_vacuum_a15
    entity: sensor.roborock_vacuum_a15_main_brush_left
    icon: mdi:brush
    precision: 0
    translations: {}
  - tile_id: side_brush_left
    label: Side brush left
    unit: h
    multiplier: 0.0002777777777777778
    hold_action:
      action: call-service
      service: vacuum.send_command
      confirmation: true
      service_data:
        command: reset_consumable
        params: side_brush_work_time
        entity_id: vacuum.roborock_vacuum_a15
    entity: sensor.roborock_vacuum_a15_side_brush_left
    icon: mdi:brush
    precision: 0
    translations: {}
  - tile_id: cleaning_count
    label: Cleanings
    entity: sensor.roborock_vacuum_a15_total_clean_count
    icon: mdi:counter
    precision: 0
    translations: {}
  - tile_id: tank_percentage
    label: Tank
    entity: sensor.robot_tank_percentage
    icon: mdi:trash-can
    hold_action:
      action: call-service
      service: script.vacuum_clean_me
      confirmation: true
    precision: 0
    unit: "%"
    translations: {}
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.roborock_vacuum_a15
        value_not: cleaning
      - entity: vacuum.roborock_vacuum_a15
        value_not: error
      - entity: vacuum.roborock_vacuum_a15
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.roborock_vacuum_a15
  - icon: mdi:pause
    conditions:
      - entity: vacuum.roborock_vacuum_a15
        value_not: docked
      - entity: vacuum.roborock_vacuum_a15
        value_not: idle
      - entity: vacuum.roborock_vacuum_a15
        value_not: error
      - entity: vacuum.roborock_vacuum_a15
        value_not: paused
    tooltip: Pause
    tap_action:
      action: call-service
      service: vacuum.pause
      service_data:
        entity_id: vacuum.roborock_vacuum_a15
  - icon: mdi:stop
    conditions:
      - entity: vacuum.roborock_vacuum_a15
        value_not: docked
      - entity: vacuum.roborock_vacuum_a15
        value_not: idle
      - entity: vacuum.roborock_vacuum_a15
        value_not: error
      - entity: vacuum.roborock_vacuum_a15
        value_not: paused
    tooltip: Stop
    tap_action:
      action: call-service
      service: vacuum.stop
      service_data:
        entity_id: vacuum.roborock_vacuum_a15
  - icon: mdi:home-map-marker
    conditions:
      - entity: vacuum.roborock_vacuum_a15
        value_not: docked
      - entity: vacuum.roborock_vacuum_a15
        value_not: returning
    tooltip: Return to base
    tap_action:
      action: call-service
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.roborock_vacuum_a15
  - icon: mdi:target-variant
    conditions:
      - entity: vacuum.roborock_vacuum_a15
        value_not: docked
      - entity: vacuum.roborock_vacuum_a15
        value_not: error
      - entity: vacuum.roborock_vacuum_a15
        value_not: cleaning
      - entity: vacuum.roborock_vacuum_a15
        value_not: returning
    tooltip: Clean spot
    tap_action:
      action: call-service
      service: vacuum.clean_spot
      service_data:
        entity_id: vacuum.roborock_vacuum_a15
  - icon: mdi:map-marker
    tooltip: Locate
    tap_action:
      action: call-service
      service: vacuum.locate
      service_data:
        entity_id: vacuum.roborock_vacuum_a15
  - icon: mdi:fan-remove
    conditions:
      - entity: vacuum.roborock_vacuum_a15
        attribute: fan_speed
        value: Silent
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_vacuum_a15
        fan_speed: Standard
  - icon: mdi:fan-speed-1
    conditions:
      - entity: vacuum.roborock_vacuum_a15
        attribute: fan_speed
        value: Standard
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_vacuum_a15
        fan_speed: Medium
  - icon: mdi:fan-speed-2
    conditions:
      - entity: vacuum.roborock_vacuum_a15
        attribute: fan_speed
        value: Medium
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_vacuum_a15
        fan_speed: Turbo
  - icon: mdi:fan-speed-3
    conditions:
      - entity: vacuum.roborock_vacuum_a15
        attribute: fan_speed
        value: Turbo
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_vacuum_a15
        fan_speed: Silent
  - icon: mdi:fan-alert
    conditions:
      - entity: vacuum.roborock_vacuum_a15
        attribute: fan_speed
        value_not: Silent
      - entity: vacuum.roborock_vacuum_a15
        attribute: fan_speed
        value_not: Standard
      - entity: vacuum.roborock_vacuum_a15
        attribute: fan_speed
        value_not: Medium
      - entity: vacuum.roborock_vacuum_a15
        attribute: fan_speed
        value_not: Turbo
    tooltip: Change fan speed
    tap_action:
      action: call-service
      service: vacuum.set_fan_speed
      service_data:
        entity_id: vacuum.roborock_vacuum_a15
        fan_speed: Silent
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_goto
  - template: vacuum_follow_path
  - name: Clean me
    icon: mdi:map-marker
    selection_type: PREDEFINED_POINT
    max_selections: 1
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: vacuum.do_point
      service_data:
        point: "[[selection]]"
        repeats: "[[repeats]]"
        point_x: "[[point_x]]"
        point_y: "[[point_y]]"
        predefined: "true"
      target:
        entity_id: "[[entity_id]]"
    predefined_selections:
      - position:
          - 21214
          - 29610
        label:
          text: Clean me
          x: 21214
          "y": 29610
          offset_y: 35
        icon:
          name: mdi:broom
          x: 21214
          "y": 29610


```

### What version of an integration has described problem?

v2.2.3

### What vacuum model do you have problems with?

roborock.vacuum.a15

### What version of Home Assistant do you use?

core-2025.5.3

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
- platform: xiaomi_cloud_map_extractor
  host: !secret xiaomi_vacuum_host
  token: !secret xiaomi_vacuum_token
  username: !secret xiaomi_cloud_username
  password: !secret xiaomi_cloud_password
  draw: ["all"]
  country: de
  auto_update: true
  attributes:
    - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell

```
