### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by pznamenskii** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#629]
### Checklist

- [x] I have updated the integration to the latest version available
- [x] I have checked if the problem is already reported

### The problem

about a week ago I noticed I no longer have vacuum map, instead a blank screen about failed login.
I though something went wrong with my xiaomi account so I checked the phone app, no issues but I still changed the password and updated secrets in HA - still same issue. I am able to login at https://account.xiaomi.com with updated password successfully.
logs aren't telling me much.
I am sure my vacuum's token hasn't changed which I verified by logging into it over ssh.

### What version of an integration has described problem?

2.2.4

### What was the last working version of an integration?

2.2.3

### What vacuum model do you have problems with?

roborock.vacuum.s5

### What version of Home Assistant do you use?

2025.6.3

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
- platform: xiaomi_cloud_map_extractor
    name: "Vacuum Map"
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: "cn"
    colors:
      color_map_inside: [0, 0, 0]
      color_map_outside: [0, 0, 0]
      color_map_wall: [100, 196, 254]
      color_map_wall_v2: [255, 238, 199]
      color_grey_wall: [255, 107, 107]
      color_path: [178, 255, 153]
      color_goto_path: [218, 255, 207]
      color_predicted_path: [231, 252, 225]
      color_zones: [212, 234, 255, 50]
      color_zones_outline: [168, 212, 255, 50]
      color_virtual_walls: [255, 0, 0, 100]
      color_no_go_zones: [255, 0, 0, 50]
      color_no_go_zones_outline: [255, 0, 0, 50]
      color_no_mop_zones: [255, 100, 100, 50]
      color_no_mop_zones_outline: [255, 100, 100, 50]
      color_charger: [255, 255, 255, 100]
      color_robo: [255, 255, 255, 200]
      color_unknown: [0, 0, 0]
      color_scan: [158, 158, 158]    
    sizes:
      charger_radius: 5
      vacuum_radius: 6.5
    draw: ["all"]
    map_transformation:
      scale: 2
      trim:
        top: 31
        bottom: 32
        left: 34
        right: 18
    attributes:
      - calibration_points
      - charger
      - goto
#      - goto_path
#      - goto_predicted_path
      - image
      - no_go_areas
      - no_mopping_areas
      - obstacles
#      - path
      - vacuum_position
      - walls
      - zones
    scan_interval:
      seconds: 3
    auto_update: true
    # store_map: false
```

### Errors shown in the HA logs (if applicable)

```shell
2025-06-25 17:08:26.720 DEBUG (SyncWorker_5) [custom_components.xiaomi_cloud_map_extractor.camera] Logging in...
2025-06-25 17:08:27.020 DEBUG (SyncWorker_5) [custom_components.xiaomi_cloud_map_extractor.camera] Failed to log in
2025-06-25 17:08:27.021 DEBUG (SyncWorker_5) [custom_components.xiaomi_cloud_map_extractor.camera] Asking device for map name... (1/10)
2025-06-25 17:08:27.026 DEBUG (SyncWorker_5) [custom_components.xiaomi_cloud_map_extractor.camera] Map name robomap%2F259637793%2F17
2025-06-25 17:08:27.026 DEBUG (SyncWorker_5) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map, reasons: Logged in - False, map name - robomap%2F259637793%2F17, device retrieved - False
```
