### ISSUE TITLE
DNS Name resolution of host key

### ISSUE THREAD

**Issue by breti** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#63]
It would be great if DNS Name resolution of "host" key would be supported.

e.g.
host: robot.fritz.box

**Comment by PiotrMachowski** [comment]
Is it possible in HA miio integration?

**Comment by breti** [comment]
Yes, it  is:

vacuum:
  - platform: xiaomi_miio
    host: robot.fritz.box
    token: !secret xiaomi_vacuum_token
    name: Staubsauger-Roboter

**Comment by PiotrMachowski** [comment]
Have you checked that it doesn't work with this integration? It uses the same library to communicate with a vacuum

**Comment by breti** [comment]
Yes, I've tried that, didn't work. I had to change the !secret from DNS Hostname to IP address to see the map.

**Comment by PiotrMachowski** [comment]
Ok, I will check it out

**Comment by PiotrMachowski** [comment]
Do you have a country defined in config?

**Comment by breti** [comment]
No, I haven't:

```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
```

**Comment by PiotrMachowski** [comment]
If you want to use hostname instead of IP address you have to provide a country in a configuration. You can find it out using [token extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor)

**Comment by breti** [comment]
OK, ... but why does host name resolution of the vacuum cleaner host depend on the country code in the configuration file? I don't get it.

**Comment by PiotrMachowski** [comment]
Actually it's the other way around: country code discovery depends on IP provided in a configuration

**Comment by PiotrMachowski** [comment]
@breti Have you tried adding country to config?

**Comment by breti** [comment]
No, I haven't. I don't have a system set up where I can run your token extractor to reveal the country code.

**Comment by PiotrMachowski** [comment]
In v1.0.4 I have added `country` attribute, it will return a discovered server in entity's attributes

**Comment by breti** [comment]
Thanks a lot! :-)

I've just updated to 1.0.4, but I still can't see a country attribute?

access_token: xxx
calibration_points:
  - vacuum:
      x: 25500
      'y': 25500
    map:
      x: 227
      'y': 132
  - vacuum:
      x: 26500
      'y': 25500
    map:
      x: 247
      'y': 132
  - vacuum:
      x: 26500
      'y': 26500
    map:
      x: 247
      'y': 112
friendly_name: Xiaomi Cloud Map Extractor
entity_picture: >-
  /api/camera_proxy/camera.xiaomi_cloud_map_extractor?token=xxx
supported_features: 0

**Comment by PiotrMachowski** [comment]
You have to add it in attributes first:
```
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
      - country
```
