### ISSUE TITLE
Add possibility to scan map only when vacuum not in dock

### ISSUE THREAD

**Issue by pplucky** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#77]
Hello.

First of all, thanks a lot for this great component, it was definitely missing in my setup for a long time.

Still then, having to define a larger scan_interval just for the sake of not consuming too many machine resources is a bit overkill. It is actually too much to do it every 5 seconds (even from the perspective of checking Xiaomi Cloud, I suppose), when most probably no map changes occurred.

I don't see much advantage in having it updating every 5 seconds when most the time the vacuum is docked and there are no changes in the map. Even if you'd like it to update in specific situations, you can always run service home assistant_update_entity, right?

Would it be an option to add a possibility to scan map only when vacuum is not in dock? I think that would be a much more lighter approach in all senses.

Thanks for letting me know if I can somehow help in turning this into a reality.

**Comment by pplucky** [comment]
FYI for anyone else that may be interested, as a workaround I added the following automation and script to allow keeping auto-update off in the custom integration configuration, updating automatically the map only while vacuum is not docked (via automation) and allow manual update if needed (via script).

```
automation:
### Update vacuum map only when vacuum not in dock ###
  - alias: 'Update vacuum map while not docked'
    trigger:
      - platform: state
        entity_id: vacuum.aspirador
        from: 'docked'
### Avoid automation being triggered if vacuum is temporarily unavailable ###
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'unavailable' and trigger.to_state.state != 'unknown' }}"
    action:
      - alias: Keep updating map until vacuum returns to dock
        repeat:
### Until vacuum is back in dock, update map every 5 seconds ###
          sequence:
            - service: homeassistant.update_entity
              data:
                entity_id: camera.mapa_casa
            - delay:
                seconds: 5
          until:
            - condition: state
              entity_id: vacuum.aspirador
              state: 'docked'

script:
### Manual update vacuum map ###
  update_vacuum_map:
    alias: "Update Vacuum Map"
    icon: mdi:robot-vacuum
    sequence:
      - service: homeassistant.update_entity
        data:
          entity_id: camera.mapa_casa
```
